### ISSUE TITLE
Feature Request: ESP

### ISSUE THREAD

**Issue by MichaelDavidGK** [winstxnhdw/lc-hax#10]
### What happened?

Can you add ESP, Scrap Value modifier and adding/removing money?
A good example is in [source code](https://www.unknowncheats.me/forum/downloads.php?do=file&id=42969) of [P1st](https://www.unknowncheats.me/forum/members/1100399.html) from UC.

It also contains simple GUI you might consider adding since there is already too many /cmds already.
You could also do something like this:
```
if (GUILayout.Button("Visuals", new GUILayoutOption[] { GUILayout.Height(30f) }))
	{
		this.currentTab = 0;
	}
```
and then simply:
```
 switch (this.currentTab)
 	{
 	case 0:
 	{
 		GUILayout.Label("Visuals", Array.Empty<GUILayoutOption>());
                this.b_ItemESP = GUILayout.Toggle(this.b_ItemESP, "Item ESP", new GUILayoutOption[] { GUILayout.ExpandWidth(true) });
```

Would be nice if you could add command to tp to main entrance, inside and spawn (although spawn is /home already).
Also to tp all to player/home/entrance/inside.
I've put values in C# below.

> 71 Gordion (Company):
> 
> - spawn = Vector3(7f, 0.2f, -14.3f)
> - seller = Vector3(-25f, -2.6f, -31.1f)
> 
> 7 Dine:
> 
> - spawn = Vector3(-7.1f, 0.3f, -13.8f)
> - main entrance = Vector3(160f, -15.1f, -41f)
> - Inside = Vector3(-6.5f, -220f, 65.8f)
> 
> 56 Vow:
> 
> - spawn = Vector3(7.4f, 0.3f, -14f)
> - main entrance = Vector3(-29f, 1.15f, 148.3f)
> - Inside = Vector3(-8.3f, -220f, 66f)
> 
> 85 Rend:
> 
> - spawn = Vector3(7.4f, 0.3f, -14f)
> - main entrance = Vector3(50f, -16.8f, -150f)
> - Inside = Vector3(9.3f, 5.2f, 1021f)
> 
> 8 Titan:
> 
> - spawn = Vector3(8f, 0.3f, -14.4f)
> - main entrance = Vector3(-32.7f, 48f, 7.1f)
> - Inside = Vector3(-8f, -220f, 66f)
> 
> 61 March:
> 
> - spawn = Vector3(7.6f, 0.2f, -14.1f)
> - main entrance = Vector3(-155.4f, -4f, 22f)
> - Inside = Vector3(-7.4f, -220f, 66f)
> 
> 21 Offense:
> 
> - spawn = Vector3(7.3f, 0.3f, 14f)
> - main entrance = Vector3(128.4f, 16.4f, -57f)
> - Inside = Vector3(-8.3f, -220f, 65.9f)
> 
> 220 Assurance:
> 
> - spawn = Vector3(7.45f, 0.3f, 14f)
> - main entrance = Vector3(132.2f, 6.5f, 74.48f)
> - Inside = Vector3(-6.8f, -220f, 66f)
> 
> 41 Experimentation:
> 
> - spawn = Vector3(8.1f, 0.2f, -14.2f)
> - main entrance = Vector3(-111f, 3f, -17.5f)
> - Inside = Vector3(-13.3f, -220f, 66f)

### Current Commit Hash

cdd88da

### Injector

- [x] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Hey, there’s actually a method you can call for teleporting a player to the main entrance, so there’s no need to hard-code the coordinates.

ESP is in plan but a GUI is not. I find it difficult and time consuming to maintain a GUI that I will be happy with. However, if there’s anyone who would like to contribute a good GUI, I wouldn’t mind reviewing the PR.

**Comment by winstxnhdw** [comment]
I missed this earlier but isn't adding/removing money already supported with `/money`?

I have tried modifying the scrap value before but I can't get it to sync with the server :/

**Comment by louieeAd** [comment]
Would something like far reach/ grab items through walls be something that would be looked into?

**Comment by winstxnhdw** [comment]
We've been looking at that too, but so far, it looks pretty complicated to implement.

**Comment by winstxnhdw** [comment]
> Would something like far reach/ grab items through walls be something that would be looked into?

Actually, I haven't tested this but I think `M3` + `E` can do this?

**Comment by louieeAd** [comment]
I actually cannot build the project? Requirements throws an error of
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
and launch.bat says that windows cannot find SharpMonoInjector.exe

**Comment by winstxnhdw** [comment]
Make sure you `requirements.bat` completes the install completely. There's also a possibility that Windows Defender is automatically quarantining the built injector.

**Comment by winstxnhdw** [comment]
I see.. Unfortunately, we are avoiding all host-only features in this mod, so unless we find some way to do it without, we won't implement it yet.

**Comment by winstxnhdw** [comment]
ESP is finally added!

**Comment by xAstroBoy** [comment]
would be nice if the ESP does involve as well items.

**Comment by winstxnhdw** [comment]
it actually sucks, especially when you're in base.

**Comment by xAstroBoy** [comment]
> it actually sucks, especially when you're in base.

you could make it show up whenever a item is close by?

**Comment by winstxnhdw** [comment]
it sucks even still. especially, when you're looking for your teammates that are in the ship and you see 20 million other boxes there.

**Comment by xAstroBoy** [comment]
> it sucks even still. especially, when you're looking for your teammates that are in the ship and you see 20 million other boxes there. i think scan works well enough.

Wouldnt be better just a text exp saying the item name and the price? No hitbox and such

**Comment by winstxnhdw** [comment]
Sure. So [Name] $[Price]?

**Comment by xAstroBoy** [comment]
> Sure. So [Name] $[Price]?

that would work.

**Comment by xAstroBoy** [comment]
@winstxnhdw i noticed enemy esp doesn't turn off when a enemy is dead.

**Comment by winstxnhdw** [comment]
I think it takes a while to update?

**Comment by xAstroBoy** [comment]
> It takes about 2s to update. Is it like that permanently?

yup, it stays permanently.

**Comment by winstxnhdw** [comment]
Okay, I've pushed a fix.
