### ISSUE TITLE
make triggermod shut the door in experimentation or break the bridge in vow 

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#100]
@winstxnhdw

**Comment by yujispin990** [comment]
HOSTO ONLY DESU~~

**Comment by winstxnhdw** [comment]
Actually, might be possible LOL

**Comment by winstxnhdw** [comment]
> shut the door

You mean the garage door, right?

**Comment by AverageVirusTotalEnjoyer** [comment]
Yeah

**Comment by winstxnhdw** [comment]
Okay, after investigating, the bridge trigger is 100% server sided.

**Comment by winstxnhdw** [comment]
I added `/garage`. It doesn't close the door all the way, but you can just call it multiple times for it to do so.
