### ISSUE TITLE
would it be possible to control when a monster attacks while possessing it?

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#108]
it doesnt attack unless you press on a key for example

**Comment by winstxnhdw** [comment]
Yeah, it's possible, but why? I am trying to be more conservative about what I add now to prevent bloating up the codebase.

**Comment by AverageVirusTotalEnjoyer** [comment]
maybe make it a toggle then

**Comment by AverageVirusTotalEnjoyer** [comment]
im testing a mod with my friends but i keep killing them by accident

**Comment by winstxnhdw** [comment]
> maybe make it a toggle then

It's the same complexity.

**Comment by winstxnhdw** [comment]
> im testing a mod with my friends but i keep killing them by accident

Why not tell them to go God mode?

**Comment by AverageVirusTotalEnjoyer** [comment]
fair
