### ISSUE TITLE
[Bug]: Cannot run requirements.bat

### ISSUE THREAD

**Issue by louieeAd** [winstxnhdw/lc-hax#11]
### What happened?

Running requirements.bat throws this error at me. I have no av installed or enabled.

MSBuild version 17.7.3+8ec440e68 for .NET
MSBUILD : error MSB1001: Unknown switch.
    Full command line: 'C:\Program Files\dotnet\sdk\7.0.401\MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary lc-hax -C Release -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.401\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.401\dotnet.dll'
  Switches appended by response files:
Switch: -C

For switch syntax, type "MSBuild -help"
MSBuild version 17.7.3+8ec440e68 for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Press any key to continue . . .

### Current Commit Hash

.

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Okay, this was my mistake. I used `-C` instead of `-c`. I have pushed the fix. You can pull latest and the error should be no more.

**Comment by louieeAd** [comment]
When launching i get this error.

**Comment by louieeAd** [comment]
When launching i now get this error 
![image](https://github.com/winstxnhdw/lc-hax/assets/59982030/f34df856-6996-4d05-aeef-58bb6d7a73ae)
![image](https://github.com/winstxnhdw/lc-hax/assets/59982030/666bed10-bf4e-484b-ab35-00f85955259a)

**Comment by winstxnhdw** [comment]
> Full command line: 'C:\Program Files\dotnet\sdk\7.0.401\MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary

Seems like you are on .NET 7.0 not 8.0..

**Comment by winstxnhdw** [comment]
Search for `Virus & threat protection` and see if defender is removing the injector every time you build it.

**Comment by louieeAd** [comment]
> > Full command line: 'C:\Program Files\dotnet\sdk\7.0.401\MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary
> 
> Seems like you are on .NET 7.0 not 8.0..

yeah i fixed this issue after i posted the comment

**Comment by louieeAd** [comment]
> Search for `Virus & threat protection` and see if defender is removing the injector every time you build it.

it isnt as i have the injector on my pc anyways and my ac is disabled

**Comment by winstxnhdw** [comment]
Okay, run `requirements.bat` and screenshot the full log.

**Comment by louieeAd** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/59982030/42b1b7e8-946f-4aea-b379-c1d0e3efabee)

**Comment by winstxnhdw** [comment]
Ahh.. You didn't recursively clone didn't you..

**Comment by louieeAd** [comment]
...My bad.

**Comment by winstxnhdw** [comment]
Not a problem. Glad you got it working now!

**Comment by MythicalTrashcan** [comment]
What about those warnings. I know they are warnings and programmers just skip them a lot if they don't break anything. But why are they even there and could they be fixed?

**Comment by winstxnhdw** [comment]
They are lint warnings because @LTYGUY doesn’t wanna write clean code and I have to clean up his mess. I’ll eventually fix all the warnings but it’ll take some time.
