### ISSUE TITLE
[Bug]: doesn't see commands in chat

### ISSUE THREAD

**Issue by M4gnuson** [winstxnhdw/lc-hax#113]
### What happened?

All hacking functions work except commands. When I enter '/players' into the chat, for example, the cheat simply does not see the command and the command is stupidly sent to the chat for all players

### Current Commit Hash

9f7b883

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
you double injected didn't you

**Comment by M4gnuson** [comment]
> you double injected didn't you

no, I injected once

**Comment by winstxnhdw** [comment]
that only happens if you double inject. restart your game.

**Comment by winstxnhdw** [comment]
oh and of course if another mod conflicts with this cheat.
