### ISSUE TITLE
[Bug]: Helmet model moves further into player head when entering Phantom

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#12]
### What happened?

When entering Phantom, the player helmet model thing covers the top of the screen more and more until it completely clips into the player head.

### Current Commit Hash

07d72d57f040bfd9ed00fb80d2f5716d578bcb9a

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Thank you for submitting this. You’ve actually found something we’ve been trying to solve for a really long time. The helmet you are seeing is the visor camera which forces fog and limits of view distance. By removing it, we’ve incidentally fixed ClearVision once and for all.
