### ISSUE TITLE
toggleable name hider

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#120]
please make a feature where we can toggle on and off our nametag when looked at and in chat

**Comment by AverageVirusTotalEnjoyer** [comment]
@winstxnhdw

**Comment by winstxnhdw** [comment]
I don't understand. You mean you don't want your name to be shown in chat?

**Comment by AverageVirusTotalEnjoyer** [comment]
basically, and also my nametag

**Comment by AverageVirusTotalEnjoyer** [comment]
yk, the name that shows over your head?

**Comment by winstxnhdw** [comment]
Sure, I'll take a look to see if it's possible.

**Comment by AverageVirusTotalEnjoyer** [comment]
alright keep me updated

**Comment by armorfid** [comment]
@AverageVirusTotalEnjoyer be aware, if you don't have a proper name, some hosts will start saying "who the fuck are you" and kicking you, I speak from experience from having my name set to `'''` 😅

**Comment by winstxnhdw** [comment]
I am not even sure if it's possible to change your username in runtime via RPCs. They have a method that is called when you join a lobby but the method only accepts the Steam ID, and your username is resolved on their client 

```cs
private void SendNewPlayerValuesServerRpc(ulong newPlayerSteamId)`
```

**Comment by AverageVirusTotalEnjoyer** [comment]
@armorfid each time hosts try to kick me it never works for some reason

**Comment by armorfid** [comment]
what happens then? do they start raging? 😆

**Comment by AverageVirusTotalEnjoyer** [comment]
@armorfid sometimes, or they just restart the lobby

**Comment by AverageVirusTotalEnjoyer** [comment]
> I am not even sure if it's possible to change your username in runtime via RPCs. They have a method that is called when you join a lobby but the method only accepts the Steam ID, and your username is resolved on their client 
> 
> ```cs
> private void SendNewPlayerValuesServerRpc(ulong newPlayerSteamId)
> ```

Could you spoof the userid?

**Comment by AverageVirusTotalEnjoyer** [comment]
Hypothetically speaking

**Comment by armorfid** [comment]
very good question... 😈

**Comment by winstxnhdw** [comment]
Maybe @armorfid can try? 👉👈

**Comment by armorfid** [comment]
I dunno if it will prevent kicking, but looking at the code, it seems as it might possibly permit rejoining? 😆 will test!

**Comment by armorfid** [comment]
So if you spoof your Steam ID to a random value, the game will kick you on join due to this:

    if (!GameNetworkManager.Instance.steamIdsInLobby.Contains(newPlayerSteamId))
    {
        NetworkManager.Singleton.DisconnectClient(this.actualClientId);
        return;
    }

However, if you cancel out `SendNewPlayerValuesServerRpc` with `static bool Prefix() => false;`, it seems the server is never aware of your Steam ID, it gives your an empty name tag and you can most likely rejoin after being kicked (unconfirmed). Although, I can't tell so far if this prevents being kicked. Looking at the kicking code, I'm still not sure how a player would become unkickable.

**Comment by winstxnhdw** [comment]
The host keeps tracks of all players that it kicks.

```cs
if (StartOfRound.Instance.KickedClientIds.Contains(newPlayerSteamId))
{
	NetworkManager.Singleton.DisconnectClient(this.actualClientId);
	return;
}
```

**Comment by winstxnhdw** [comment]
`KickPlayer` eventually uses Unity's `NetworkConnectionManager` to kick you. Since the host receives an incorrect Steam ID, `NetworkConnectionManager` may not be able to resolve your actual Steam ID and fail to kick you.

**Comment by armorfid** [comment]
> The host keeps tracks of all players that it kicks.

Yes but in `KickPlayer`, the value added to `KickedClientIds` is `StartOfRound.Instance.allPlayerScripts[playerObjToKick].playerSteamId`, which is never instantiated for you if your `SendNewPlayerValuesServerRpc` didn't run.

> If we randomise our steam ID every time we join, we can rejoin a lobby we've been kicked from.

I tried that, like I said, it doesn't work for the aforementioned reason, you simply get instakicked on join.

**Comment by winstxnhdw** [comment]
You're right. Let me test.

**Comment by winstxnhdw** [comment]
Looks like they can't kick me LOL

**Comment by winstxnhdw** [comment]
Okay, so our names don't show up on their lobby. They can't kick me. They can only restart the server.

**Comment by armorfid** [comment]
with `static bool Prefix() => false` ?

**Comment by winstxnhdw** [comment]
Yeap.

**Comment by winstxnhdw** [comment]
Problem now is how do we make this a feature. I am sure not everybody wants to play without a name.

**Comment by armorfid** [comment]
Replace `false` with a `Setting` entry? 🤣 Although, you'd have to join/host a game first to toggle it on, then join a public game. I most definitely think having this enabled by default is _not_ a good idea 😅

**Comment by winstxnhdw** [comment]
Feels bad but I might actually have to introduce a GUI :(

**Comment by winstxnhdw** [comment]
No, I refuse. I will make it a keybind instead.

**Comment by winstxnhdw** [comment]
Alright, I've pushed. `Anti-kick` has been added! It's funny as hell because your name becomes a random teammate's name and they kick their own friends thinking it's you.

**Comment by armorfid** [comment]
![evil laugh](https://c.tenor.com/qhSnfrZCuIwAAAAd/tenor.gif)

**Comment by winstxnhdw** [comment]
Oh, and 100% thanks to @armorfid.

**Comment by armorfid** [comment]
I do feel like we may have opened a Pandora's box with this, but only time will tell

**Comment by armorfid** [comment]
I don't think your `SendNewPlayerValuesClientRpc` call works as intended, it's a `ClientRpc` so it's never sent to the server. All it seems to do is mangle up the player names on our end.

**Comment by winstxnhdw** [comment]
Names are mangled either way. With this, at least locally, you can see your own name.

**Comment by armorfid** [comment]
ah you're right, I got mixed up, with the anti-kick we don't receive any names until someone else connects either way
