### ISSUE TITLE
[Bug]: how would i disable infinite scan range?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#126]
### What happened?

sdasda

### Current Commit Hash

wedqe124

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Duplicate of #107
