### ISSUE TITLE
[Bug]: can you make the no light toggleable? 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#129]
### What happened?

saddawqdqer

### Current Commit Hash

646g

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
If enough people want this, sure. As of now, no.
