### ISSUE TITLE
[Bug]: The system cannot find the file ./submodules/SharpMonoInkectorCor/dist/SharpMonoInjector.exe.

### ISSUE THREAD

**Issue by bravetiger2** [winstxnhdw/lc-hax#130]
### What happened?

Just downloaded a fresh install of lc-hax, and I was met with this on starting:

Time Elapsed 00:00:02.58
The system cannot find the file ./submodules/SharpMonoInjectorCore/dist/SharpMonoInjector.exe.
Press any key to continue . . .

I looked further into it, the file simply doesn't exist. The folder ./submodules/SharpMonoInjectorCore/ exists, but there is no dist/sharpmonoinjector.exe

I'm guessing it was left out?

### Current Commit Hash

N/A

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I am begging you to follow the install instructions. Running `requirements.bat` builds `SharpMonoInjector.exe`. If it’s still not there. Check your antivirus.
