### ISSUE TITLE
[Bug]: Old bug allowed infinite masks

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#131]
### What happened?

Like a week-2 weeks ago you could get killed by mask while on god mode and you could create infinite masks. Now that doesn't work. Could you bring that back?

### Current Commit Hash

5252vg

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
@armorfid ah, someone has complained 😂

**Comment by armorfid** [comment]
@joep26020 bruh, that was actually an unintended side effect of god mode, which I fixed because it made some players ragequit, but I guess we can bring it back as a feature? 😆

**Comment by winstxnhdw** [comment]
i’m not even sure how we should handle this 🥲

**Comment by armorfid** [comment]
2 untargetable settings, `/ignore` and `/ignore god`, with the non-god disabled and the god one enabled by default?

**Comment by winstxnhdw** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/1f211ada-7f52-448c-8b9a-cee952530c14)

Funnily enough, the dev actually had a failsafe for those in God mode LOL

**Comment by winstxnhdw** [comment]
I've found a way to infinitely spawn masked enemies as long as you have a mask in your hand. You can even define a position to spawn them in.

**Comment by winstxnhdw** [comment]
It's `/mask <player>`

**Comment by joep26020** [comment]
how would we define the position? and thank you!

**Comment by winstxnhdw** [comment]
With the target player. Anyways, if you are not the host, it seems you can only spawn 1 mask per round without using up the mask.

**Comment by joep26020** [comment]
> It's `/mask <player>`

so can you stil bring back mask glitch spawn with godmode?

**Comment by joep26020** [comment]
> > It's `/mask <player>`
> 
> so can you stil bring back mask glitch spawn with godmode?

@winstxnhdw

**Comment by winstxnhdw** [comment]
I am thinking how we can best do this. I can see how annoying it is to be permanently stuck the whole game as well.

**Comment by joep26020** [comment]
> I am thinking how we can best do this. I can see how annoying it is to be permanently stuck the whole game as well.

what if we could god another player and do this to them??? if you can heal and kill why cant you god?

**Comment by joep26020** [comment]
> I am thinking how we can best do this. I can see how annoying it is to be permanently stuck the whole game as also i gotta download telegram first to send the vid. ill do it tmrw

**Comment by winstxnhdw** [comment]
> what if we could god another player and do this to them??? if you can heal and kill why cant you god?

Because God is client-side. Whenever you die, we literally tell your game that you can't die. You can't tell another player they can't die because their computers control whether they are dying instead. The masked enemy does an instant kill attack that cannot be out-healed.

**Comment by winstxnhdw** [comment]
> > I am thinking how we can best do this. I can see how annoying it is to be permanently stuck the whole game as also i gotta download telegram first to send the vid. ill do it tmrw


Sure, much appreciated.

**Comment by joep26020** [comment]
> > > I am thinking how we can best do this. I can see how annoying it is to be permanently stuck the whole game as also i gotta download telegram first to send the vid. ill do it tmrw
> 
> Sure, much appreciated.

Yep. I also have to ask theres a mod some hosts have which says "jimmy" has started the ship!". and it don't launch. any way to fix?

**Comment by winstxnhdw** [comment]
Without knowing what mod it is, there's not much I can do.

**Comment by joep26020** [comment]
> Without knowing what mod it is, there's not much I can do.

maybe one of these:
https://thunderstore.io/c/lethal-company/p/CharlesE2/HostFixes/
https://thunderstore.io/c/lethal-company/p/usb/Anticheese/
https://thunderstore.io/c/lethal-company/p/Ozone/Lockdown/
https://thunderstore.io/c/lethal-company/p/gamendegamer/Lethal_Admin/
https://thunderstore.io/c/lethal-company/p/TeamTinyAdmin/Lethal_Company_Tiny_Admin/
probably one of the top 3
