### ISSUE TITLE
[Bug]: Funny revive

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#132]
### What happened?

funny revive doesn't make mobs do damage to other players and the hoarding buck doesn't make noise when revived. and masks dont revive also. and noise command doesn't work at all.

### Current Commit Hash

12451545q

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
This is intentional. We haven’t found a way to truly revive them. That’s why it’s titled as such. It’s nothing serious.

**Comment by joep26020** [comment]
> This is intentional. We haven’t found a way to truly revive them. That’s why it’s titled as such. It’s nothing serious.

I see. Ok and the noise part what is the other person supposed to hear? Because so far nobody has actually showed any sign of hearing 'things'.

**Comment by winstxnhdw** [comment]
What noise part?

**Comment by joep26020** [comment]
> What noise part?

the noise command

**Comment by winstxnhdw** [comment]
See  #134
