### ISSUE TITLE
[Bug]: Game Master

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#133]
### What happened?

Check out Game Master mod, it allows u to toggle night vision and tp without a teleporter.

### Current Commit Hash

1252352525

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Pretty sure the point of their mod is for you to be the host.
