### ISSUE TITLE
[Bug]: Gamemaster blocks virtually all functions of this mod. Only usable one is start and end. Any way to bypass? 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#137]
### What happened?

fsfasdfsafsfgs

### Current Commit Hash

253252536

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Tell their maintainers instead.
