### ISSUE TITLE
Cant Find sharpmonoinjector.exe

### ISSUE THREAD

**Issue by endivex** [winstxnhdw/lc-hax#14]
![image](https://github.com/winstxnhdw/lc-hax/assets/153818910/56e7e424-c2b6-40d1-9cb4-59e8e815fd30)

I already cloned the repository using the given code but after i tried to launch it still cant find sharpmonoinjector.exe

**Comment by winstxnhdw** [comment]
Send the full log when you do `requirements.bat`.

**Comment by KORVAAXX** [comment]
Hello, i have it too 
![issue](https://github.com/winstxnhdw/lc-hax/assets/154364126/586719a8-bdd8-4272-91f9-9b170094cfba)
this is the requirement.bat
and when the launch.bat:
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/d2ed4c49-ba86-4cac-91b8-bcff6ff4b4b9)

Sorry for my bad english as you can see, but in the error window it says : windows cannot find "./submodule.........."
check that you entered the correct name, then try again.

i'm new in this kind of cheats i don't know how to do, maybe drop a setup/instal tutorial for all the not english persons.

**Comment by winstxnhdw** [comment]
Vous devez cloner récursivement le référentiel en utilisant l'indicateur --recursive

```bash
git clone --recursive https://github.com/winstxnhdw/lc-hax.git
```

**Comment by KORVAAXX** [comment]
that's what I did, I'll show you what that tells me:
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/8295841e-ed7e-4bcf-8b8c-71f567518542)

**Comment by winstxnhdw** [comment]
You should delete the original folder first before cloning again.

**Comment by winstxnhdw** [comment]
Delete `lc-hax`, yes.

**Comment by KORVAAXX** [comment]
i deleted the lc-hax and type git clone --recursive https://github.com/winstxnhdw/lc-hax.git in the cmd but :
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/45be379c-141f-4d0c-8be6-9d29c480e222)

**Comment by KORVAAXX** [comment]
add me on discord to explain me please xDD 
discord: korvaaxx

**Comment by winstxnhdw** [comment]
What did you do to get that message?

**Comment by KORVAAXX** [comment]
> Qu'avez-vous fait pour recevoir ce message ?

i just deleted the lc-hax and type git clone --recursive https://github.com/winstxnhdw/lc-hax.git in the CMD

**Comment by winstxnhdw** [comment]
Okay, now follow the steps in the [README](https://github.com/winstxnhdw/lc-hax#installation).

**Comment by KORVAAXX** [comment]
> Okay, now follow the steps in the [README](https://github.com/winstxnhdw/lc-hax#installation).

just to clarify i delete the entire lc-hax file?

**Comment by winstxnhdw** [comment]
Yes. The entire thing. Make sure you don't even see the folder `lc-hax`.

**Comment by KORVAAXX** [comment]
> Yes. The entire thing. Make sure you don't even see the folder `lc-hax`.

ok so that's what I did and after deleting and doing git clone --recursive https://github.com/winstxnhdw/lc-hax.git, I run the requirement.bat and it's done. puts message:

MSBuild version 17.8.3+195e7f5a3 for .NET
MSBUILD: error MSB1009: The project file does not exist.
Switch: lc-hax
MSBuild version 17.8.3+195e7f5a3 for .NET
MSBUILD: error MSB1003: Specify a project or solution file. The active working directory contains none.
Press any key to continue...

**Comment by KORVAAXX** [comment]
j

> > Yes. The entire thing. Make sure you don't even see the folder `lc-hax`.
> 
> ok so that's what I did and after deleting and doing git clone --recursive https://github.com/winstxnhdw/lc-hax.git, I run the requirement.bat and it's done. puts message:
> 
> MSBuild version 17.8.3+195e7f5a3 for .NET MSBUILD: error MSB1009: The project file does not exist. Switch: lc-hax MSBuild version 17.8.3+195e7f5a3 for .NET MSBUILD: error MSB1003: Specify a project or solution file. The active working directory contains none. Press any key to continue... ![Capture](https://private-user-images.githubusercontent.com/154364126/291680237-05134e84-53e8-4d31-ae6d-9746494f541d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTA2OTcsIm5iZiI6MTcwMzAxMDM5NywicGF0aCI6Ii8xNTQzNjQxMjYvMjkxNjgwMjM3LTA1MTM0ZTg0LTUzZTgtNGQzMS1hZTZkLTk3NDY0OTRmNTQxZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxODI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODRiN2I1MTcwYmNjZTFhMmE2YmU0YWQ1OWM1N2E0YjVmYjg1MTI0MDUzZDRhMWE1NDAyNjM5OGFmZjVjNmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h8JdNr6Es3ehGkcf6BwQ9B50Eo2Ok5iP-JuTnXZnO5A)

**Comment by winstxnhdw** [comment]
Can you look inside your submodules folder? Is SharpMonoInjectorCore there? You should see this.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/d48e6a83-d75f-4ac3-a0a8-eccc46777fe2)

**Comment by KORVAAXX** [comment]
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/3aec5f63-45f6-44c8-b082-22092536c237)
no there is nothing

**Comment by winstxnhdw** [comment]
Hahaha, it is because you are not using the folder that you have cloned. Click on `requirements.bat` inside your `lc-hax` folder, not `lc-hax-main`.

**Comment by KORVAAXX** [comment]
i don't have requirements.bat inside my lc-hax folder 
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/5895a6fe-9765-4c83-bbd4-198e4c714e04)

**Comment by winstxnhdw** [comment]
You misunderstand.

I know what you did. You downloaded the repository as zip and extracted the files right? This is wrong. If you download as a zip, you will not download `SharpMonoInjectorCore`.

Instead, use the folder that you clone. When you clone a repository, a folder named `lc-hax` will be created.

**Comment by winstxnhdw** [comment]
Click on `Open Git Bash Here` and recursively clone the repository again. I think you can't find the folder because Git Bash defaults to `%USERPROFILE%`.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/ec04074e-828c-4a37-ad5b-a9d3f804be68)

**Comment by KORVAAXX** [comment]
I don't understand, I can't, it seems simple but I'm useless xD I don't know how you're going to help me,

despite what you told me I don't see how to open with GitBashHere you can, maybe make a video tutorial or make me a list of what I have to do in order, your cheat is really interesting I want to trolling my friends xD

**Comment by winstxnhdw** [comment]
Okay, let's try this. Open Git Bash however you did before. Then type the following.

```bash
explorer.exe  .
```

You should see a folder pop up. In this folder, you should also see a folder named `lc-hax`. From there, follow the instructions in the README.

**Comment by KORVAAXX** [comment]
> D'accord, essayez ça. Ouvrez Git Bash comme vous le feriez auparavant. Tapez ensuite ce qui suit.
> 
> ```powershell
> explorer.exe  .
> ```
> 
> Vous devriez voir un dossier apparaître. Dans ce dossier, vous devriez également voir un dossier nommé `lc-hax`. À partir de là, suivez les instructions du README.

When i open git bash and i type explorer.exe it opens me all my windows folders

**Comment by winstxnhdw** [comment]
Correct. Do you see `lc-hax` in there?

**Comment by KORVAAXX** [comment]
> us voyez `lc-hax`là-ded

no it opens me this folder 
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/9e1ebeb5-5e8e-48a2-a013-1c73125c6353)

**Comment by winstxnhdw** [comment]
You forgot to add `.`

**Comment by KORVAAXX** [comment]
i type explorer.exe in git bash cmd
![1](https://github.com/winstxnhdw/lc-hax/assets/154364126/7cf67599-fb5a-4750-8b5e-2148c651d410)
![2](https://github.com/winstxnhdw/lc-hax/assets/154364126/a980b78f-24d6-4389-9b36-977170c6cb21)

**Comment by winstxnhdw** [comment]
You forgot the period again.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/e655ac26-45b0-4850-a4b6-4b86c142aa99)

**Comment by KORVAAXX** [comment]
okay i see it, and now
![Capture](https://github.com/winstxnhdw/lc-hax/assets/154364126/fe995209-4660-46aa-9a3c-3115cc3e6201)

**Comment by winstxnhdw** [comment]
merci mon dieu..

**Comment by KORVAAXX** [comment]
> merci mon dieu..

now i find it what i do

**Comment by winstxnhdw** [comment]
Follow the instructions in the [README](https://github.com/winstxnhdw/lc-hax#installation).

**Comment by KORVAAXX** [comment]
> Suivez les instructions du [fichier README](https://github.com/winstxnhdw/lc-hax#installation) .

ITS WORKIIIIIING !!!!, is there a activable menu or just commands ?

**Comment by KORVAAXX** [comment]
> Toutes nos félicitations. Juste des commandes et des raccourcis clavier.
I'm sorry to have bothered you so much but I really wanted your mod, it's unique I've never seen such new options in the mod, thank you again and continue to do beautiful things that are at least evil ;)

good luck to you.
