### ISSUE TITLE
[Bug]: can't drop gift box after using it a lot.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#141]
### What happened?

adasda

### Current Commit Hash

54154511515

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Yeah, I am still trying to figure out why this happens.

**Comment by winstxnhdw** [comment]
Tracked in favour of #66
