### ISSUE TITLE
[Bug]: after leaving game or host closing lobby, anti-k on, every time i try to join new server, it says offline.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#142]
### What happened?

f5t56236

### Current Commit Hash

000

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Not a bug. It just means the lobby no longer exists.

**Comment by joep26020** [comment]
> Not a bug. It just means the lobby no longer exists.

no it happens on every lobby

**Comment by FredxDX** [comment]
yeah same problem

**Comment by winstxnhdw** [comment]
Strange. I can't replicate.

**Comment by FredxDX** [comment]
no im not modded
when I turn the feature off I can join games. with it on I cant

**Comment by winstxnhdw** [comment]
I have just tried it a bunch of times, still nothing.

**Comment by joep26020** [comment]
> I have just tried it a bunch of times, still nothing.

you are correct, it is a lobby that is no longer allowing joins
