### ISSUE TITLE
[Feature Request]: Any way to give somebody anxiety and make them haunted by the little girl? like a /haunt

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#143]
### What happened?

adadasd

### Current Commit Hash

5655666

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Nope, can't give a player fear but you might be able to take ownership of her and make her target someone else.

**Comment by winstxnhdw** [comment]
I think we should put this on the backlog. Looks like a lot of people are having issues with achieving this as well.
