### ISSUE TITLE
[Bug]: A no teleport command which turns off teleporting so that way other hackers cant mess with you

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#144]
### What happened?

55151

### Current Commit Hash

35525

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Yeah, I had this idea too. But I had some trouble so I gave up for a while.

**Comment by winstxnhdw** [comment]
Added in latest. Do `/block radar`.
