### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#147]
### What happened?

Anyway to bypass that?

### Current Commit Hash

4t

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
The only way is to be the last person to join. So once you join, immediately do `/start`, they shouldn't be able to resolve your username anymore.

**Comment by joep26020** [comment]
> The only way is to be the last person to join. So once you join, immediately do `/start`, they shouldn't be able to resolve your username anymore.

ok will it change right when i start it or after it loads?

**Comment by winstxnhdw** [comment]
What do you mean?

**Comment by joep26020** [comment]
after map loads??? or after i do /start command

**Comment by winstxnhdw** [comment]
As soon as possible I guess
