### ISSUE TITLE
[Bug]: New ESP targeting dead bodies outside the map near "/void" location 

### ISSUE THREAD

**Issue by Isuckwithusernames** [winstxnhdw/lc-hax#148]
### What happened?

When anyone dies it shows their dead body location very far away from the actual map. not a major issue whatsoever but could use a touch up 

### Current Commit Hash

1f556a30dc2a57280a6703482ecf0539df0ba220

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Done.
