### ISSUE TITLE
[Bug]: Anti-Kick messes up player names

### ISSUE THREAD

**Issue by Isuckwithusernames** [winstxnhdw/lc-hax#149]
### What happened?

When using the new Anti-Kick feature, it changes all player names to Player #0, Player #1, Player #2, Player #3 (i think after staying in the lobby for a while without starting it resets, but if you use /start or the host starts the game while it still shows Player #_ the names will be like that permanently). This makes it impossible to use all commands that use `/____ <player>` format. It also takes away the "Crew:" portion of the pause menu which would normally allow you to see player names from there, although sometimes it glitches and will show player names from previous servers that you've joined. 
![image](https://github.com/winstxnhdw/lc-hax/assets/102493377/1eecb9dc-20e3-400d-873a-45b2f9bad8e6)

1 more thing on the topic of Anti-Kick bugs is that the anti-kick works for the 1st initial kick but if they attempt to kick you again it will go through, and you will be sent back to the main menu (although if the server is still available it allows you to join back again)

### Current Commit Hash

1f556a30dc2a57280a6703482ecf0539df0ba220

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You can always use their ID instead. For example, `/player 0`.

**Comment by winstxnhdw** [comment]
> 1 more thing on the topic of Anti-Kick bugs is that the anti-kick works for the 1st initial kick but if they attempt to kick you again it will go through, and you will be sent back to the main menu (although if the server is still available it allows you to join back again)

This is wrong. When a new player joins after you, the host is able to resolve your Steam ID and can then kick you. If you are the last player to enter the lobby, you can't get kicked. Not sure how to fix this yet.

**Comment by Isuckwithusernames** [comment]
> You can always use their ID instead. For example, `/player 0`.

Ive just tried this in a lobby with the /pumpkin <player> command, i tried /pumpkin #0 Player #0 (which is what the ESP name shows) then i tried /pumpkin Player 0 (which is what you recommended), ive noticed that the vanilla player tag only shows Player #  i am guessing this is what messes it up because there is no value that clarifies who is who.

**Comment by winstxnhdw** [comment]
Yes, the broken names are client-side only. They still keep their real names. If you use the player index, it will never lie.

**Comment by Isuckwithusernames** [comment]
I got that, im just wondering if there is a possible fix to be made the client-sided name changes because it makes it impossible to use all commands with the /___ <player> format. 

As for the player index, which i assume is the section of the pause menu that says Crew: followed by each players name with the voice volume slider under them; it does not show up if the player names are all bugged with Player #_

**Comment by winstxnhdw** [comment]
>  it makes it impossible to use all commands with the /___ <player> format

I don't understand this. Why can't you just do `/pumpkin 0`. All `<player>` queries can be substituted by their indices. `/<command><player/playerIndex>`.

> As for the player index, which i assume is the section of the pause menu that says Crew: followed by each players name with the voice volume slider under them; it does not show up if the player names are all bugged with Player #_

I'll be honest. `Anti-kick` is still really experimental. It's the first of its kind and we don't know a lot of things yet. It'll probably be a while before a fix comes.

**Comment by Isuckwithusernames** [comment]
> I don't understand this. Why can't you just do `/pumpkin 0`. All `<player>` queries can be substituted by their indices. Basically, `/<command> <player/playerIndex>`.

I just tried the command with the Index instead of player names and it works, didn't realize you could substitute it for that. thanks for clarifying

**Comment by armorfid** [comment]
So, the way the anti-kick works is by not broadcasting our Steam ID to the server. However, the server only sends player name updates when someone joins the server and broadcasts their Steam ID. Therefore, if you are the last player to join the game before it starts, you won't see the correct names, unless the host has Late Company and someone joins late. I don't think this is gonna be fixable unless Unity somehow provides the Steam IDs via another pathway inside the game.
