### ISSUE TITLE
[Feature Request]: Phantom doesn't have Invert Y Axis for mouse.

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#15]
### What happened?

I know this may sound pretty dumb to make a bug report about. But if you turn on the Invert mouse Y axis in the settings for example, then enter phantom and move your screen. There is no Invert Y. It is pretty inconvient to have to switch directions everytime you use phantom.

### Current Commit Hash

0a99eaf73f32cb55a79541ea239eedccfd3c0a22

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Not dumb at all. I think the controls are really bad too. I prefer the Minecraft creative controls where you can just press `Shift` to go down.

I'll work on it sometime soon.

**Comment by MythicalTrashcan** [comment]
Minecraft creative is well made, but what about spectator mode? Spectator mode has those creative aspects like shift to go down and space to go up. If you plan to use shift to move down, make sure you also change that phantom tphere keybind. Spectator has a highlight player option too. Not sure if you have thought of some type of ESP, but you could add that too.

**Comment by winstxnhdw** [comment]
> make sure you also change that phantom tphere keybind

This isn't necessary because 'tphere' requires a combination of `Shift` + `=`, so there's no conflict here.

> Not sure if you have thought of some type of ESP

ESP is definitely in plan.

**Comment by MythicalTrashcan** [comment]
>hold Shift to invert and fly down.
If you fly down, when you press shift, then wouldn't that be annoying to teleport where you want? I though ```Ctrl``` already moved you down anyways.

**Comment by winstxnhdw** [comment]
You're right. What a pain.. I hate using `ctrl` to move down..

**Comment by winstxnhdw** [comment]
Fixed as of latest.
