### ISSUE TITLE
[Feature Request]: Allow inviting people all the time

### ISSUE THREAD

**Issue by FredxDX** [winstxnhdw/lc-hax#156]
### What happened?

It would be nice to be alble to invite people even after the game started

### Current Commit Hash

d5ab9d6

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think there's a mod for this and I don't want to include that in fear of losing compatibility with these mods.
