### ISSUE TITLE
[Bug]: how does esp work? also might send a screenshot sometime but not today

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#157]
### What happened?

rqwrqrqr

### Current Commit Hash

325552

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
ESP is turned on by default. You should be able to see it the moment you join a match.

**Comment by joep26020** [comment]
> ESP is turned on by default. You should be able to see it the moment you join a match.

I will update again but I updated 1 hour ago. Also the look at player for name isn't working for me. (where the weight is at)

**Comment by joep26020** [comment]
> ESP is turned on by default. You should be able to see it the moment you join a match.

git bash says 'already up to date'

**Comment by winstxnhdw** [comment]
I have removed the `NameInWeight` mod as it is now redundant due to ESP.

**Comment by joep26020** [comment]
> I have removed the `NameInWeight` mod as it is now redundant due to ESP.

Oh I see. Well ESP isn't working for me... Will try to turn off mods and see if those affect it.

**Comment by joep26020** [comment]
> I have removed the `NameInWeight` mod as it is now redundant due to ESP.

Weird thing is I can see player names far away, just not through walls (no box)

**Comment by joep26020** [comment]
> I have removed the `NameInWeight` mod as it is now redundant due to ESP.

Started vanilla, issue persist.

**Comment by winstxnhdw** [comment]
Hmm, that is worrying. I am not at my computer at the moment so I can't test it personally.

**Comment by winstxnhdw** [comment]
You should never do this but could you double inject while you are in the game and let me know if the issue still persists.

**Comment by joep26020** [comment]
> You should never do this but could you double inject while you are in a game and let me know if the issue still persists.

Ok twice in game or first in menu and second in lobby?

**Comment by FredxDX** [comment]
I have never seen any esp? How does it even look like? I dont see names far away but I do see the crosshair

**Comment by winstxnhdw** [comment]
Preferably when the ship lands.

**Comment by winstxnhdw** [comment]
> I have never seen any esp? How does it even look like? I dont see names far away but I do see the crosshair

It's a bounding box around the player or enemy. It's really obvious once you see it.

**Comment by joep26020** [comment]
> 

double injected, doesn't work. also please bring back player name in weight, that way i can see player number. very annoying to keep type full name. or put it with player esp name so that way its already there.

**Comment by winstxnhdw** [comment]
Yeap, with ESP, you should be able to see their ID.

**Comment by joep26020** [comment]
> Yeap, with ESP, you should be able to see their ID.

Well esp is not working.

**Comment by winstxnhdw** [comment]
For now, you can revert to the last working commit.

```  
git reset --hard dd2b3ce03046db1f9010a4b0c98e6e29b70d11e7
```

**Comment by joep26020** [comment]
any features i should know that were removed?

> For now, you can revert to the last working commit.
> 
> ```
> git reset --hard dd2b3ce03046db1f9010a4b0c98e6e29b70d11e7
> ```

**Comment by joep26020** [comment]
allow offensive lobby names???

**Comment by winstxnhdw** [comment]
Nothing else. You can look at the commit history. Any commits starting with `feat` are changes to the cheat that will affect users.

**Comment by winstxnhdw** [comment]
> allow offensive lobby names???

Yup, that commit should have ESP working.

**Comment by joep26020** [comment]
> Nothing else. You can look at the commit history. Any commits starting with `feat` are changes to the cheat that will affect users.



> > allow offensive lobby names???
> 
> Yup, that commit should have ESP working.

uhm how do i see commit history?

**Comment by winstxnhdw** [comment]
> > Nothing else. You can look at the commit history. Any commits starting with `feat` are changes to the cheat that will affect users.
> 
> 
> 
> 
> 
> 
> 
> > > allow offensive lobby names???
> 
> > 
> 
> > Yup, that commit should have ESP working.
> 
> 
> 
> uhm how do i see commit history?

https://github.com/winstxnhdw/lc-hax/commits/main/

**Comment by joep26020** [comment]
> > > Nothing else. You can look at the commit history. Any commits starting with `feat` are changes to the cheat that will affect users.
> > 
> > 
> > > > allow offensive lobby names???
> > 
> > 
> > > 
> > 
> > 
> > > Yup, that commit should have ESP working.
> > 
> > 
> > uhm how do i see commit history?
> 
> https://github.com/winstxnhdw/lc-hax/commits/main/

thanks

**Comment by FredxDX** [comment]
https://youtu.be/olu6MPQUx2k

**Comment by winstxnhdw** [comment]
> https://youtu.be/olu6MPQUx2k

Can't really tell with this since ESP are for players/enemies/dangerous objects. Why not go into `Phantom` and look at yourself from more than 5m away?

**Comment by FredxDX** [comment]
Does the land mine count as a dangerous object?

**Comment by FredxDX** [comment]
https://youtu.be/EyezGDqytb0

**Comment by FredxDX** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/95638755/9a3a8938-9012-4a6d-90f4-498bc55716d8)
![image](https://github.com/winstxnhdw/lc-hax/assets/95638755/641187ff-9879-4544-afd8-e6f44e422db5)

**Comment by joep26020** [comment]
> Does the land mine count as a dangerous object?

yeah it shows on the old version im on. can you addd the fire exit and main entrance on esp too

**Comment by FredxDX** [comment]
yeah it works on the old version for me aswell

**Comment by joep26020** [comment]
> > https://youtu.be/olu6MPQUx2k
> 
> Can't really tell with this since ESP are for players/enemies/dangerous objects. Why not go into `Phantom` and look at yourself from more than 5m away?

can you make player id easier to se? like bigger text because its too small i have to be close to see

**Comment by winstxnhdw** [comment]
Fixed in latest.

> can you make player id easier to se? like bigger text because its too small i have to be close to see

I can't change the font size for some reason. I'll look into it.
