### ISSUE TITLE
[Feature Request]: press q to quick tp to mouse position?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#159]
### What happened?

551515

### Current Commit Hash

004

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think this feature is not worth implementing afterall. I am not sure how to differentiate between the ground and walls, or how best to do the interaction. Might add it long in the future but not anytime soon.
