### ISSUE TITLE
What is M3.

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#16]
Also sounds quite stupid to ask. I thought this was some type of keybind. I also checked if this was Mouse 3, but I didn't see that do anything either.

**Comment by winstxnhdw** [comment]
It's `Mouse 3`. Your middle click. Read [this](https://github.com/winstxnhdw/lc-hax#triggermod) to understand what it does.

**Comment by MythicalTrashcan** [comment]
I looked at some of that. I think I was supposed to be looking at it, but randomly stuff would happen without me looking at it.

**Comment by winstxnhdw** [comment]
You’ll have to elaborate.

**Comment by MythicalTrashcan** [comment]
I was at the Company Building and when I pressed ```Mouse 3```, Jeb attacked and I didn't look at him.

**Comment by winstxnhdw** [comment]
Jeb’s collider spans the entire map, so doing `M3` anywhere would trigger him.
