### ISSUE TITLE
/visit command

### ISSUE THREAD

**Issue by ManuelSvQ** [winstxnhdw/lc-hax#160]
It seems that whenever you change the moon to something else the host's pc will turn off, this surprises me as I've tested this with friends and with randoms, it seems to crash them somehow.

**Comment by joep26020** [comment]
> It seems that whenever you change the moon to something else the host's pc will turn off, this surprises me as I've tested this with friends and with randoms, it seems to crash them somehow.

is this recently on the new update? and are you sure it's not only your friend?

**Comment by winstxnhdw** [comment]
Probably a mod?
