### ISSUE TITLE
[Feature Request]: Make anti-k make you get stuck in the wall and host cant see you join so host doesn't kick instantly

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#162]
### What happened?

dadadsada1242

### Current Commit Hash

51515

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
LOL, I'll see what I can do.

**Comment by winstxnhdw** [comment]
I can’t make the player go into the wall. There’s strong game code that forces you back in. Patching it would cause a lot of problems. Instead, I am thinking of a new command that makes you go invisible?

**Comment by winstxnhdw** [comment]
Completed with `/invis`
