### ISSUE TITLE
[Bug]: Please add back player id on weight number, because sometimes players are too far or fast to see number.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#163]
### What happened?

5154151

### Current Commit Hash

566666

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
The size of the text doesn't change no matter how far they are.

**Comment by joep26020** [comment]
> The size of the text doesn't change no matter how far they are.

yes but they still move. i don't see why you have to keep player weight number removed. i just ask could you please put it back in.

**Comment by winstxnhdw** [comment]
I removed it because like all mods, it has a performance cost. If the player is moving, don't you also have to track the player with your mouse so that it shows up on your HUD?

**Comment by joep26020** [comment]
> I removed it because like all mods, it has a performance cost. If the player is moving, don't you also have to track the player with your mouse so that it shows up on your HUD?

well could you make it toggleable or optional? or could i have the code so i can input it into my mod?

**Comment by winstxnhdw** [comment]
Sure, the code is here: https://github.com/winstxnhdw/lc-hax/commit/dab252b25066c474f90e15c2740ce4d3ce3a6008

**Comment by joep26020** [comment]
> Sure, the code is here: [dab252b](https://github.com/winstxnhdw/lc-hax/commit/dab252b25066c474f90e15c2740ce4d3ce3a6008)
> 
> If more people want it back, I'll add it back.

so what do i do with that??? im sorry i dont understand what i do with codes

**Comment by winstxnhdw** [comment]
You just have to copy-paste them back into your code. Highlighted in red means they've been removed.
