### ISSUE TITLE
[Feature Request]: make it so you can do /start instantly so host cant kick you right away and a constant join so host has to sit there and keep kicking lol

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#164]
### What happened?

14154

### Current Commit Hash

515151

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think with `/invis` this is probably no longer necessary.
