### ISSUE TITLE
[Bug]: There's a mod that blocks you from starting ship. It says "player has tried to start the ship!"

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#165]
### What happened?

dfaffsfsfsfs

### Current Commit Hash

23556252

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
If they are doing something similar to what I am doing, I can't bypass that unfortunately.
