### ISSUE TITLE
[Bug]: Anti-kick toggle not working.

### ISSUE THREAD

**Issue by Slyrex** [winstxnhdw/lc-hax#166]
### What happened?

I've managed to press activate it once, but other than that I don't really understand why but pressing \ doesn't turn the toggle on tried restarting, no idea how i managed to get it working the first time as I can't enable it again; not sure if the mb3 is working for me either.
the commands work fine.

### Current Commit Hash

d5ab9d677fcaba848f9835d3ca28adc13dbed81d

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by Slyrex** [comment]
For some reason on my keyboard it is the # key, uk-layout.

**Comment by winstxnhdw** [comment]
The real crime here is using a US labelled keyboard but with UK bindings 😭
