### ISSUE TITLE
[Bug]: Flowerman makes your game lag

### ISSUE THREAD

**Issue by ManuelSvQ** [winstxnhdw/lc-hax#168]
### What happened?

Whenever I use lc-hax the Flowerman makes me game start flashing and choppy, going at about 30 FPS then chopping each time, I don't know how this happens.

### Current Commit Hash

rrytwryry

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Can someone else confirm? I just tried earlier today, it was fine to me.

**Comment by winstxnhdw** [comment]
The error says it can't find your game. Can you open the game and post a screenshot of your Task Manager?

**Comment by ManuelSvQ** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139501748/52d9d3a1-9fb7-48ee-ae1c-c8bf427c3b37)
It launches but after 3 seconds of the launch.bat opening my LC freezes and then crashes.

**Comment by winstxnhdw** [comment]
What's the error for that?

**Comment by UltraStuff** [comment]
game crash upon opening launch.bat latest commit

```
Already up to date.
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored F:\Stuff\modss\lc-hax\lc-hax\lc-hax.csproj (in 1.13 sec).
  lc-hax -> F:\Stuff\modss\lc-hax\bin\lc-hax.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.21
Injection failed: SharpMonoInjector.InjectorException: mono_object_get_class() returned NULL
   at SharpMonoInjector.Injector.ThrowIfNull(IntPtr ptr, String methodName)
   at SharpMonoInjector.Injector.GetClassName(IntPtr monoObject)
   at SharpMonoInjector.Injector.RuntimeInvoke(IntPtr method)
   at SharpMonoInjector.Injector.Inject(Byte[] rawAssembly, String namespace, String className, String methodName)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
Press any key to continue . . .
```

**Comment by winstxnhdw** [comment]
Yeah, it might be the new command I just added.

Try doing this for now.

```
git reset --hard 87562d464855cf7f05c3fc2fb0f7509a8203e8e8
```

**Comment by winstxnhdw** [comment]
I don't have access to my computer now so I've just commented it out for now. It should work on latest again.

**Comment by UltraStuff** [comment]
> Yeah, it might be the new command I just added.
> 
> Try doing this for now.
> 
> ```
> git reset --hard 87562d464855cf7f05c3fc2fb0f7509a8203e8e8
> ```

Works thanks

**Comment by ManuelSvQ** [comment]
> I don't have access to my computer now so I've just commented it out for now. It should work on latest again.

Works now, thank you

**Comment by joep26020** [comment]
> > Can someone else confirm? I just tried earlier today, it was fine to me.
> 
> It seems that continuously aiming at enemies and using the M3 button can cause monsters to teleport outside of the facility (as observed through ESP, where you can see the monsters in the map outside the facility). This can result in the game flickering and stuttering, as well as reducing FPS.
> 
> If this issue can be resolved, it might be possible to utilize this aspect to teleport monsters to external maps without the need for mods.

Interesting. So do other players see that or is it client-side? Also, do you only do this in phantom mode?

**Comment by joep26020** [comment]
> > Can someone else confirm? I just tried earlier today, it was fine to me.
> 
> It seems that continuously aiming at enemies and using the M3 button can cause monsters to teleport outside of the facility (as observed through ESP, where you can see the monsters in the map outside the facility). This can result in the game flickering and stuttering, as well as reducing FPS.
> 
> If this issue can be resolved, it might be possible to utilize this aspect to teleport monsters to external maps without the need for mods.

omg it works lmao i got a nutcracker outside and chased people. his kick effect didnt work but the shotgun effect did! and killed some people!

**Comment by winstxnhdw** [comment]
> 
> 
> 
> 
> > Can someone else confirm? I just tried earlier today, it was fine to me.
> 
> 
> 
> It seems that continuously aiming at enemies and using the M3 button can cause monsters to teleport outside of the facility (as observed through ESP, where you can see the monsters in the map outside the facility). 
> 
> This can result in the game flickering and stuttering, as well as reducing FPS.
> 
> 
> 
> If this issue can be resolved, it might be possible to utilize this aspect to teleport monsters to external maps without the need for mods.

We can already teleport mobs outside of the factory. We don't do that because it breaks the game. The game expect factory-only mobs to remain in the factory and vice-versa.

**Comment by winstxnhdw** [comment]
If someone has the time to test this, you can change this [line](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Mixins/IEnemyPrompter.cs#L114) in your code to this and see if the game is still stable?

```cs
this.TeleportEnemyToPlayer(nutcracker, targetPlayer, willTeleportEnemy, true, true)
```

This will allow the Nutcracker to teleport outside when you do `/mob`. If all is well, we can push this feature.

**Comment by joep26020** [comment]
> > > Can someone else confirm? I just tried earlier today, it was fine to me.
> > 
> > 
> > It seems that continuously aiming at enemies and using the M3 button can cause monsters to teleport outside of the facility (as observed through ESP, where you can see the monsters in the map outside the facility).
> > This can result in the game flickering and stuttering, as well as reducing FPS.
> > If this issue can be resolved, it might be possible to utilize this aspect to teleport monsters to external maps without the need for mods.
> 
> We can already teleport mobs outside of the factory. We don't do that because it breaks the game. The game expect factory-only mobs to remain in the factory and vice-versa. But I think this may mainly just be Bracken's problem..

check out my reply in the gifs discussion!

**Comment by joep26020** [comment]
> If someone has the time to test this, you can change this [line](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Mixins/IEnemyPrompter.cs#L114) in your code to this and see if the game is still stable?
> 
> ```cs
> this.TeleportEnemyToPlayer(nutcracker, targetPlayer, willTeleportEnemy, true, true)
> ```
> 
> This will allow the Nutcracker to teleport outside when you do `/mob`. If all is well, we can push this feature.

where do i put that at?

**Comment by winstxnhdw** [comment]
If you click on the link, it brings you to the file and line you need to change.

**Comment by joep26020** [comment]
> If you click on the link, it brings you to the file and line you need to change.

ok thanks. i need to ask though can you re add invis?

**Comment by joep26020** [comment]
> If you click on the link, it brings you to the file and line you need to change.

so how do i use this new feature?

**Comment by joep26020** [comment]
> If you click on the link, it brings you to the file and line you need to change.

i changed the code and it says build failed

**Comment by joep26020** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/143763241/3f66c5d5-eae6-4197-8edf-d0adfd4c1515)

**Comment by joep26020** [comment]
> > Can someone else confirm? I just tried earlier today, it was fine to me.
> 
> It seems that continuously aiming at enemies and using the M3 button can cause monsters to teleport outside of the facility (as observed through ESP, where you can see the monsters in the map outside the facility). This can result in the game flickering and stuttering, as well as reducing FPS.
> 
> If this issue can be resolved, it might be possible to utilize this aspect to teleport monsters to external maps without the need for mods.

i have tried the bracken. i can get him out of the area and by the ship, but its very laggy, and his inf jump wont work even if movement mode is switched. sometimes the lag turns off when i'm watching a player, but then i think if the player maybe sees the bracken, it lags again

**Comment by winstxnhdw** [comment]
> i changed the code and it says build failed

Oops, I forgot to add a semicolon at the end. My bad.

**Comment by winstxnhdw** [comment]
This issue has been fixed.
