### ISSUE TITLE
[Bug]: Stamina not working

### ISSUE THREAD

**Issue by qunumtumtum** [winstxnhdw/lc-hax#17]
### What happened?

infinite stamina only works about 25% of the time when launching the game.

### Current Commit Hash

most recent

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think @Quesotoric mentioned this in #4. Can you take a look at that first?

**Comment by Quesoteric** [comment]
I have been summoned

Anyway, IIRC how I replicated it was injecting before I was 'in game' (main menu, server browser, etc)
My best guess is the script can't find anything to do with the stamina outside of when you're 'in game' and thus fails to load the module

**Comment by winstxnhdw** [comment]
I usually inject in the main menu though.

**Comment by winstxnhdw** [comment]
I’ll close this for now, we can move the discussion to the initial issue.
