### ISSUE TITLE
Translate ESP texts to Chinese

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#174]
### What happened?

How to translate enemy esp display into Chinese, I can only do landmines and entrances and exits，In addition, the esp of electric shock bees is invalid，The enemy cannot be modified directly. For example, the hoarding bug displays "Hoardering bug" in esp. I can't even search for this string in all codes.
![QQ截图20240105143539](https://github.com/winstxnhdw/lc-hax/assets/155458839/9b210f6d-ece9-4b4b-9007-40e32f39792c)
![QQ截图20240105143551](https://github.com/winstxnhdw/lc-hax/assets/155458839/b68f81e0-fd13-4cc7-9b57-fda5839a391a)

### Current Commit Hash

dddd

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Hi @Taogun,

For enemies, you can replace this [line](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Modules/ESPMod.cs#L157C1-L162C11) like this. Here's an example for Bracken.

```cs
    Action<Vector3> RenderEnemy(EnemyAI enemy) => rendererCentrePoint => {
        string translatedEnemyName = ""

        if (enemy is FlowermanAI) {
              translatedEnemyName = "小黑";
        }

        Helper.DrawLabel(
            rendererCentrePoint,
            enemy.enemyType.enemyName,
            Color.red
        );
};
```

**Comment by Taogun** [comment]
> Bracken
Are you Chinese? “小黑”It's a popular name in China，flowerman literal translation is “花男”

**Comment by winstxnhdw** [comment]
Hi @Taogun, I don't think there's a direct translation for Bracken, but in my experience with playing with other Chinese players, they call Bracken, 小黑.

**Comment by Taogun** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/4a0fc163-63a9-4688-9bb6-9b74794b1ad6)
can you teach me how to fix the code，i am a green hand

**Comment by winstxnhdw** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/8ddf81f7-b367-4de7-b2bc-fa6482ba20b0)

**Comment by Taogun** [comment]
> ![图像](https://private-user-images.githubusercontent.com/56998716/294428202-8ddf81f7-b367-4de7-b2bc-fa6482ba20b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDE3MTIsIm5iZiI6MTcwNDQ0MTQxMiwicGF0aCI6Ii81Njk5ODcxNi8yOTQ0MjgyMDItOGRkZjgxZjctYjM2Ny00ZGU3LWIyYmMtZmE2NDgyYmEyMGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3NTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMGYxMjZiMzkyNWVkN2NiZTQ1YzM0YzM2YzU5NTVlMGQwMDU5YTg2YzFlNjQ0MmQzNWMyOWIyMGU5MDkyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JelUfYC64UAVs94DJgpWW7o3dIFXogTuNntYovA6lqc)

By the way, bee's esp has no effect

**Comment by winstxnhdw** [comment]
Yes, it's being fixed in #172.

**Comment by Taogun** [comment]
> 是的，它已在#172中修复。

There seems to be no esp for the blob

**Comment by Taogun** [comment]
> 是的，它已在#172中修复。

![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/4e81e1f1-9e4f-476e-9887-9f45467d4a6e)
Can you tell me how to translate this into Chinese?

**Comment by Taogun** [comment]
> > 是的，它已在#172中修复。
> 
> ![图像](https://private-user-images.githubusercontent.com/155458839/294433469-4e81e1f1-9e4f-476e-9887-9f45467d4a6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDMyMjQsIm5iZiI6MTcwNDQ0MjkyNCwicGF0aCI6Ii8xNTU0NTg4MzkvMjk0NDMzNDY5LTRlODFlMWYxLTllNGYtNDc2ZS05ODg3LTlmNDU0NjdkNGE2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwODIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTMxNTY4ZTJhYzBjYzkyZmViM2VlZGZlMmViYjk5ZjBjYjBmYjYyYzNmOTY2ODY4ZWM0YmMyOWU4MmIwNGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AmnP8Ai0sH33syEgY04OhGQUd2dTaSnuP_AybEA4S-4) 你能告诉我如何把这个翻译成中文吗？
this is another enemy esp

**Comment by winstxnhdw** [comment]
I think you should ask their maintainers.

**Comment by Taogun** [comment]
> 我认为你应该问他们的维护者。

They ignored my request

**Comment by winstxnhdw** [comment]
我不做免费工作。

**Comment by Taogun** [comment]
> 我不做免费工作。

![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/f4a136fe-ad56-42ae-9402-2e24e5498bd6)
Okay, I've finished translating your project, and I'm currently solving the problem of some monsters not displaying esp, and the player's void display.

**Comment by Taogun** [comment]
> > 我不做免费工作。
> 
> ![image](https://private-user-images.githubusercontent.com/155458839/294445701-f4a136fe-ad56-42ae-9402-2e24e5498bd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDYxOTUsIm5iZiI6MTcwNDQ0NTg5NSwicGF0aCI6Ii8xNTU0NTg4MzkvMjk0NDQ1NzAxLWY0YTEzNmZlLWFkNTYtNDJhZS05NDAyLTJlMjRlNTQ5OGJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwOTExMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTM3NmJiYzNlMzRjMzIyYmQwNWVhNDEyNzY2ZjM3YTFlNjQyODc4MWNhZTA0ZTM3ZDU5ZmJjNDQ4N2VkMTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3nDBWzXCbJmy9k212x9hk005zt5tPMT5eq1l4R6XzOc) Okay, I've finished translating your project, and I'm currently solving the problem of some monsters not displaying esp, and the player's void display.

![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/5caacf5c-13ee-45b2-b442-cfd4ad45094a)

**Comment by Taogun** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/b5b8a0e2-d9bd-4246-aea6-503ab56d5613)
1

**Comment by winstxnhdw** [comment]
漂亮

**Comment by Taogun** [comment]
> 漂亮

![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/50e3d6a7-10c9-4d10-b08c-07ff30a6ead1)
i don't konw why

**Comment by Taogun** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/24180098-cc25-4920-90ff-3c670ef7450f)
and where have solution?

**Comment by winstxnhdw** [comment]
I am not sure. Maybe we must make a special exception for bees.

**Comment by Taogun** [comment]
Are you considering making item esp?

**Comment by winstxnhdw** [comment]
It's very simple to add but it's very hard to see.

**Comment by Taogun** [comment]
Is only bee's esp currently invalid?

**Comment by winstxnhdw** [comment]
I am not sure.

**Comment by QWEWSY** [comment]
问一下 你的囤积虫和弹簧头的英文命名时什么 怎么我这边就这几个不行
未能找到类型或命名空间名“HoardingBugAI”(是否缺少 using 指令或程序集引用?)

**Comment by winstxnhdw** [comment]
是 HoarderBugAI

**Comment by QWEWSY** [comment]
thank you
Can you tell me the names of these people?
EarthLeviathanAI，GirlAI，ManticoilAI，CrawlerAI，MaskedAI，SpringAI.

**Comment by winstxnhdw** [comment]
Can I ask what you are trying to do?

**Comment by QWEWSY** [comment]
Display in Chinese

**Comment by winstxnhdw** [comment]
@Taogun is already doing that. Anyways, you can see this [file](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Mixins/IEnemyPrompter.cs) for all the names.

**Comment by AverageVirusTotalEnjoyer** [comment]
🤓
