### ISSUE TITLE
[Bug]: Complete functions

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#175]
### What happened?

Add distance display

### Current Commit Hash

wwww

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Can be done, but is it worth calculating the distance every frame?
