### ISSUE TITLE
[Bug]: how to tp mobs/nutcracker outside?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#178]
### What happened?

4r5 1555

### Current Commit Hash

5555523

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
`/mob <player>`
