### ISSUE TITLE
[Feature Request]: add a spam terminal mod (the fail sound)

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#181]
### What happened?

555113232312

### Current Commit Hash

555215555d

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think we will just avoid any feature that the sole purpose of is to only create spam.
