### ISSUE TITLE
GUI:  Can we get a GUI?

### ISSUE THREAD

**Issue by ryudious** [winstxnhdw/lc-hax#185]
### What happened?

So this is the best cheat by far.  The issues are for players with very long names you cant type or even put that many characters into the chat box for commands like /pumpkin     

### Current Commit Hash

1

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Query by their IDs instead.

For example, `/pumpkin 0`
