### ISSUE TITLE
[Feature Reques]: add feature to end game and set day to 0 (like when ship leaves everyone gets vacuumed out, make that happen when I join), and change set amount of days. 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#186]
### What happened?

555512

### Current Commit Hash

333231414

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by joep26020** [comment]
> I'm pretty sure all of these are host-only
Okay, thanks for the reply!

**Comment by winstxnhdw** [comment]
Thanks @Quesoteric!
