### ISSUE TITLE
[Bug]: Screen freeze

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#189]
### What happened?

After using out-of-body experience or Possess enemies，This will happen after using out-of-body or monster control and the mission quota is not reached and you are kicked out of the ship.

### Current Commit Hash

dddd

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by Taogun** [comment]
![Uploading {FCF5405A-3749-406d-BE7A-18B0FDF8880C}.png…]()

**Comment by Taogun** [comment]
![Uploading {FCF5405A-3749-406d-BE7A-18B0FDF8880C}.png…]()

**Comment by winstxnhdw** [comment]
Try doing `/fixcamera`

**Comment by Taogun** [comment]
no,i cant type anything

**Comment by winstxnhdw** [comment]
Pretend you can

**Comment by winstxnhdw** [comment]
Can't replicate.
