### ISSUE TITLE
[Bug]: Kill cmd can lead to more deaths than players

### ISSUE THREAD

**Issue by MichaelDavidGK** [winstxnhdw/lc-hax#19]
### What happened?

Right now it will kill the person even if they are already dead and this can cause issue at the end of in game day as it will show more dead ppl and less bodies retrieved.
In addition if deaths ≥ ppl in lobby => it will delete all items in ship, same as if no one survived.

You should add check to see if player is alive for /kill and give error if they are already dead.
Currently every /kill adds +1 to game deaths, stacking infinitely with every use.

You could eventually add troll command to stack up deaths ;)

### Current Commit Hash

6f9cf9a

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
This is really interesting. I'll look into it.

**Comment by winstxnhdw** [comment]
Alright, `/kill` will now check if the player is alive/controlled. Stacking up deaths will be an enhancement I'll do at a later date.

**Comment by winstxnhdw** [comment]
I can't replicate your findings. I tried killing myself several times in a 2 player lobby.

**Comment by winstxnhdw** [comment]
v45, not modded. I am not sure I have time today since I am 8 hours ahead of you.

**Comment by winstxnhdw** [comment]
Tomorrow should be fine.

**Comment by winstxnhdw** [comment]
Hey, I don't have time today, let's arrange another time. How do I contact you?

**Comment by winstxnhdw** [comment]
Alright, I've sent you a Discord request.

**Comment by jezbud** [comment]
Pretty sure this is replicated if you kill a player with godmode

**Comment by winstxnhdw** [comment]
Should be fixed with the new god mode.
