### ISSUE TITLE
[Feature Request]: create spider webs

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#190]
Today encountered this situation, someone can continuously generate spider webs at the player's location, causing immobilization. However, it seems that webs cannot be generated if there are no spiders present.

**Comment by winstxnhdw** [comment]
Might be possible to forcefully hang people's bodies too.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/a834ab5d-29cf-44f0-8cb8-fdbc9293696e)

**Comment by winstxnhdw** [comment]
Aww nevermind. It seems it only accepts the actual dead body object :(

**Comment by winstxnhdw** [comment]
yup, added.
