### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by Slyrex** [winstxnhdw/lc-hax#193]
### What happened?

Latest build crashed on inject.
![image](https://github.com/winstxnhdw/lc-hax/assets/138227334/5dfaa9bf-556e-4c5d-a3be-609b40df728b)

### Current Commit Hash

df0e34503e5d200c2f97474674c4d503422e450f

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
yup my bad, fixed in latest.

**Comment by GigglingMinister** [comment]
that's fast
