### ISSUE TITLE
[Bug]:  Fast Interaction on map doors

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#195]
### What happened?

During game, i noticed the fast interaction allows to open , but not close certain doors in the map.

### Current Commit Hash

Unknown

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Log output

None

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Can someone back his claims? I haven't been able to replicate it.

**Comment by winstxnhdw** [comment]
I am going to close this since no one has complained of this issue yet.
