### ISSUE TITLE
[Feature Request]: add a lightning command?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#196]
### What happened?

gygyhgh

### Current Commit Hash

523523523

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
i'm sure this is server-side only because changing the weather is server-side.

**Comment by winstxnhdw** [comment]
looking at the code, it seems entirely server-sided.
