### ISSUE TITLE
[Bug]: joining most servers gives me an "could not get server data. are you offline?" error

### ISSUE THREAD

**Issue by luhohagaming** [winstxnhdw/lc-hax#199]
### What happened?

everytime i try to join a server most say "could not get server data. are you offline?" please help

### Current Commit Hash

f5b57bf40daced441d4287f9a3808079d4eb7100

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Log output

log output only talks about my antivirus so idk

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by QWEWSY** [comment]
The game has been updated
V47

**Comment by winstxnhdw** [comment]
Will update later today.

**Comment by luhohagaming** [comment]
Do i have to re-download lc-hax? Ik its a stupid question but still

**Comment by QWEWSY** [comment]
The /visit <moon> is invalid in the latest version.
/ct is invalid

**Comment by winstxnhdw** [comment]
Hey guys, sorry for the delay. An hour after I sent that comment, I was hit with a 40C fever which incapacitated me. I'll update soon.

**Comment by GigglingMinister** [comment]
> Hey guys, sorry for the delay. An hour after I sent that comment, I was hit with a 40C fever which incapacitated me. I'll update soon.

I hope you get well soon
fever sucks

**Comment by winstxnhdw** [comment]
Hey everyone! Thanks for the concern and waiting. I've finally added support for `v47`. It took a while to find the DLLs that have changed.

With that said, enjoy!

**Comment by joep26020** [comment]
> Hey guys, sorry for the delay. An hour after I sent that comment, I was hit with a 40C fever which incapacitated me. I'll update soon.

Get well soon Winston!!!!!!
