### ISSUE TITLE
Enemies id for the fatality

### ISSUE THREAD

**Issue by TheLGAOriginal** [winstxnhdw/lc-hax#201]
could you send a list with every enemy name thats used in the command? Already tried braken and flowerman

**Comment by GigglingMinister** [comment]
only jester giant and mask for know I think?

**Comment by winstxnhdw** [comment]
Biggest question right now. Does it work?

**Comment by TheLGAOriginal** [comment]
it kinda works, but it need to be in the right moment, also if possible could you fix the /hate when there is a nutcracker, instead of him walking to the target he just shoot like a damn sniper, even if the target is on the other side of the map and even outdoors

**Comment by winstxnhdw** [comment]
> when there is a nutcracker, instead of him walking to the target he just shoot like a damn sniper, even if the target is on the other side of the map and even outdoors

what's wrong with this?

**Comment by winstxnhdw** [comment]
Okay, I've made him not attack on prompt anymore.
