### ISSUE TITLE
[Bug]: Item ESP (scraps ESP) broken

### ISSUE THREAD

**Issue by Linkis20** [winstxnhdw/lc-hax#206]
### What happened?

Did /grab to get all items and it showed items on esp way outside of the play space
Then i saw that it was just the same esp from the loot that was shown a second time
![esp on loot](https://github.com/winstxnhdw/lc-hax/assets/4784118/b984bc97-9015-44ed-99ed-0ddb734f3d1f)
then when i rotate away form the loot it shows esp in the void
![esp on void](https://github.com/winstxnhdw/lc-hax/assets/4784118/bfa0c513-0b11-404c-8799-2e5db945b148)

Also went down a second time and did /grab and the new items have no esp on them
![no esp on new items](https://github.com/winstxnhdw/lc-hax/assets/4784118/5a167a93-02e1-49cf-8b08-34dbce2c189f)

### Current Commit Hash

10c999daf394c8d82646aec4081b50c164b5e68b

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Log output

[lc-hax.log](https://github.com/winstxnhdw/lc-hax/files/13881315/lc-hax.log)

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
oh cool, it seems `grab` somehow doesn't update the renderers.

**Comment by winstxnhdw** [comment]
Fixed in latest.
