### ISSUE TITLE
What is a Thumper?

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#214]
### What happened?

which enemy is "thumper"??

### Current Commit Hash

a

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
https://lethal-company.fandom.com/wiki/Thumper

**Comment by Taogun** [comment]
emmmm,i used call him Twoleg

**Comment by winstxnhdw** [comment]
His real name is Thumper.

**Comment by GigglingMinister** [comment]
what a discussion
