### ISSUE TITLE
[Bug]: object display

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#215]
### What happened?

Only show some items on the map, not all

### Current Commit Hash

aaaa

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
What does it not show?

**Comment by Taogun** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/b8b56b44-e5c8-4f72-8cb7-9cd9bbed3a23)
as you see............

**Comment by Taogun** [comment]
only show min amount,most cant be display

**Comment by Taogun** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/155458839/fcc35ac0-b757-4158-bfc1-da78eed914df)
and hva bug ，Assuming a key is displayed, it will also display a key in the void outside the map, and this display will change according to the player's perspective.I wonder if it’s the same problem as the player’s display

**Comment by winstxnhdw** [comment]
Fixed.
