### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by Taogun** [winstxnhdw/lc-hax#216]
### What happened?

After rewriting the code related to esp, it seems that the original translation code has become invalid.

### Current Commit Hash

dddd

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Yes, I am constantly refactoring the codebase so it might become different in the future.
