### ISSUE TITLE
[Bug]: Anti kick module always loaded even if i exclude it in loader.cs

### ISSUE THREAD

**Issue by cmmaio** [winstxnhdw/lc-hax#220]
### What happened?

some modded lobbies wont let you join if antikick module is injected even if its off
excluding it in loader.cs file only turns it off but it still gets injected ingame

### Current Commit Hash

b01dfa188f9f90beb98893cd45587ad3cd4e8b0c

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Can we confirm whether it is actually the AntiKick patch? Try deleting this file and see if it still blocks you https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/AntiKickPatch.cs.

**Comment by winstxnhdw** [comment]
Do you know which mod it is?

**Comment by winstxnhdw** [comment]
It's weird that they can kick you considering our names shouldn't even appear on their menu..

**Comment by winstxnhdw** [comment]
Hmm..

I am wondering if we can just patch out this entire section and then spoof our player ID. What do you think @armorfid?

```cs
			if (!GameNetworkManager.Instance.disableSteam && GameNetworkManager.Instance.currentLobby != null)
			{
				if (!GameNetworkManager.Instance.steamIdsInLobby.Contains(newPlayerSteamId))
				{
					NetworkManager.Singleton.DisconnectClient(this.actualClientId);
					return;
				}
				if (StartOfRound.Instance.KickedClientIds.Contains(newPlayerSteamId))
				{
					NetworkManager.Singleton.DisconnectClient(this.actualClientId);
					return;
				}
			}
```

**Comment by winstxnhdw** [comment]
I don't even have to do that. Just patch out `DisconnectClient` instead..

**Comment by winstxnhdw** [comment]
Hmm, I just tried it but it seems like they can still kick me.

**Comment by winstxnhdw** [comment]
I managed to spoof my Steam ID, but the game becomes basically unplayable. You play as the host's body, and you can no longer see the host. Your original character just stands still for the rest of the match. When the round is over, your ship never leaves. When the host disconnects, you still stay in the game.

**Comment by cmmaio** [comment]
> Can we confirm whether it is actually the AntiKick patch? Try deleting this file and see if it still blocks you https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/AntiKickPatch.cs.

deleted the cs files from patches and modules and rebuilt it but still see the Anti Kick: Off in the lobby and prevents me from joining

**Comment by armorfid** [comment]
> I am wondering if we can just patch out this entire section

That chunk of code is server-side, it won't do anything if you patch it client-side, same with `DisconnectClient`

To be confirmed, but I think the anti-kick only actually works if you were the last player to join the lobby. All it does is prevent the game from putting you in the Esc menu player list as long as nobody joins after you, since `AddUserToPlayerList` is called from `SendNewPlayerValuesClientRpc`. If someone else joins, they will invoke the RPC and the whole player list will refreshed. You will probably start showing up on there and can now get kicked.

The mods @tslpy1 mentioned can still kick you directly using your Unity client ID from `allPlayerScripts` even if you don't show up in the Esc menu.

>deleted the cs files from patches and modules and disabled it from Loader.cs rebuilt it but still see the Anti Kick: Off in the lobby and prevents me from joining

What's the error message? Is it "An error occurred", or something else?

**Comment by winstxnhdw** [comment]
> deleted the cs files from patches and modules and disabled it from Loader.cs rebuilt it but still see the Anti Kick: Off in the lobby and prevents me from joining

The `Anti Kick Off` label you see actually has nothing to do with the Anti Kick patch so it's not Anti Kick that is blocking you from joining. It's something else.
