### ISSUE TITLE
[Bug]: Anti-kick feature cannot be enabled

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#222]
In the new version, it seems that the anti-kick feature cannot be enabled. When pressing the backslash key, the font in the top right corner does not toggle on/off, and the font in the top right corner disappears after entering the game.

**Comment by winstxnhdw** [comment]
My bad, fixed in latest.

>the font in the top right corner disappears after entering the game.

This is intended.

**Comment by winstxnhdw** [comment]
Did you use `mask` only once or more than that?

**Comment by hm3826** [comment]
> anti-kick feature cannot be enabled. When pressing the backslash key not change

fixed? same

**Comment by winstxnhdw** [comment]
Yup, fixed.

**Comment by winstxnhdw** [comment]
Ahh, that's why. If you're not host, you can only summon 1 Masked per round.

**Comment by winstxnhdw** [comment]
> but using the /fatality command can force them to be caught xD.

But this is very interesting information. This tells me there might be a way to make the masked enemies attack.
