### ISSUE TITLE
God mode on even tho i never turned it on

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#223]
### What happened?

Basically each match i go im godded and i cant turn it off (not using other mods)

### Current Commit Hash

E

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Weird. I need more info because I can't replicate this:

**Comment by winstxnhdw** [comment]
I’ll close this for now since I can’t replicate it.
