### ISSUE TITLE
[Bug]: void doesn't work

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#226]
### What happened?

just tps target back to ship

### Current Commit Hash

b6d24218509fb83592b86003c6b8b8b121b9fa7d

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Seems like the latest update broke the placement of objects.

**Comment by winstxnhdw** [comment]
See #236 for more info.
