### ISSUE TITLE
Launch issue CA1838 / SharpMonoInjector.exe

### ISSUE THREAD

**Issue by Tkachpavl** [winstxnhdw/lc-hax#229]
### What happened?

Hello, im trying to launch requirements.bat and always getting error CA1838: Avoid StringBuilder parameters for P/Invokes. Is it compiler/injector issue (not a programmer so idk what i say xD)? Could launch cheat only 2 random times thru a lot of tries, one is when launching launch.bat without error of missing SharpMonoInjector.exe (worked only once) and other dont remember which bat but nvm

![изображение_2024-01-11_070732289](https://github.com/winstxnhdw/lc-hax/assets/127883562/75f6e324-8190-4d68-bbf1-50bc235871ff)

### Current Commit Hash

24e19e94027a08875d5d81e0c3417aa6507ced02

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
you can ignore that warning. you only need the two bat files in the README.

**Comment by Tkachpavl** [comment]
as i read requirements.bat adds SharpMonoInjector.exe but seems like it doesnt, so i get that error with missing SharpMonoInjector.exe. antivirus didn`t delete it. Watched all the :issues and :discussions

**Comment by winstxnhdw** [comment]
send me your terminal screenshots
 of launch.bat

**Comment by Tkachpavl** [comment]
yes think i have git, installed it like 4 months ago

![image](https://github.com/winstxnhdw/lc-hax/assets/127883562/01691e2e-e618-484b-b287-4e119279bc41)

![image](https://github.com/winstxnhdw/lc-hax/assets/127883562/943cf981-9f14-41bb-9f1c-6e112891a957)

**Comment by winstxnhdw** [comment]
When you run requirements.bat, is SharpMonoInjector.exe created under your submodules?

**Comment by winstxnhdw** [comment]
Run requirements.bat and send a screenshot

**Comment by Tkachpavl** [comment]
nope, just folders bin dist and obj creating

![image](https://github.com/winstxnhdw/lc-hax/assets/127883562/d1019b12-c512-4ed4-ac39-0e6d7d33f2cb)

**Comment by winstxnhdw** [comment]
bro, it hasn't even finished building 😭

**Comment by Tkachpavl** [comment]
oh XD i forgot it takes longer then 2 seconds, ive just checked already

![image](https://github.com/winstxnhdw/lc-hax/assets/127883562/a71f052e-1642-4b59-8933-7fb24febf52e)

**Comment by winstxnhdw** [comment]
good, should be inside the `dist` folder. it should work now.

**Comment by Tkachpavl** [comment]
oh haha, hidden shi, i thought its supposed to be in SharpMonoInjectorCore but not in dist. Thanks:)
