### ISSUE TITLE
[Bug]: Lure enemy issues

### ISSUE THREAD

**Issue by cmmaio** [winstxnhdw/lc-hax#231]
### What happened?

Dead centipedes will give lured person centipede effects without the actual centipede, jesters plays enraged sounds and kills you without being wound up, spider webs gets tped too. Lured bees stops you from picking up the hive.

### Current Commit Hash

24e19e94027a08875d5d81e0c3417aa6507ced02

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
> Dead centipedes will give lured person centipede effects without the actual centipede, jesters plays enraged sounds and kills you without being wound up, spider webs gets tped too.

these are all intended and from feature requests over time.

> Lured bees stops you from picking up the hive.

i'll see what i can do.

**Comment by winstxnhdw** [comment]
Beehive issue is fixed in latest
