### ISSUE TITLE
[Bug]: Spam and crash command

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#240]
### What happened?

Add a /spam mod. like where you could do /spam [duration] [interval] [message or command]. Also wondering if a /crash [player] or /crash [server] is possible?

### Current Commit Hash

hey1213

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
> Also wondering if a /crash [player] or /crash [server]

Not sure if this counts as Denial of Service and would be illegal for me to distribute LOL

**Comment by joep26020** [comment]
> > Also wondering if a /crash [player] or /crash [server]
> 
> Not sure if this counts as Denial of Service and would be illegal for me to distribute LOL

oh so its illegal to make that lol

**Comment by armorfid** [comment]
I have seen a few hackers do that, they would spam a ton of chat messages and RPCs, to the point of nearly freezing the game, leaving the host no choice but to quit. I strongly believe this kind of feature should not be added to lc-hax.

**Comment by winstxnhdw** [comment]
I agree
