### ISSUE TITLE
[Bug]: /block enemy (Become untargetable) ignored

### ISSUE THREAD

**Issue by Linkis20** [winstxnhdw/lc-hax#241]
### What happened?

In [UntargetablePatch.cs](/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/UntargetablePatch.cs)
some enemies do not use PlayerIsTargetable
I checked all enemies that use PlayerIsTargetable:
- [x] Baboon Bird
- [x] Blob
- [x] Centipede (it will drop down on player)
- [x] Crawler
- [x] Dress Girl
- [x] Flowerman
- [x] Forest Giant
- [x] Hoarder Bug
- [x] Jester
- [x] Masked Player (can hear footsteps, also uses line of sight)
- [x] Mouth Dog (can hear footsteps)
- [x] Nutcracker
- [ ] Puffer
- [x] Red Locust Bees
- [x] Sand Spider (Can find you if you step in web)
- [x] Sand Worm
- [x] Spring Man
- [ ] Landmine 
- [ ] Turret (is server?)

Some use Line of Sight
EnemyAI::CheckLineOfSightForClosestPlayer
PlayerControllerB::CheckLineOfSightForPlayer
NutcrackerEnemyAI::CheckLineOfSightForLocalPlayer

### Current Commit Hash

332800fc594a1454b38be8a98d2c8185139cfb8c

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Thanks for the investigation @Linkis20. I wonder if they all use `targetPlayer` and if that’s the case, maybe I should just patch that variable in the update loop.
