### ISSUE TITLE
[Bug]: Anti-Kick doesn't prevent kicking

### ISSUE THREAD

**Issue by Thorvas** [winstxnhdw/lc-hax#244]
### What happened?

I can freely use Anti-Kick, however Anti-Kick doesn't prevent kicking at all. I appear as "Nameless" or just as standard user with my own nick and host is able to kick me with ease. Sometimes wrong player is kicked but generally it doesn't work well.

### Current Commit Hash

632af24

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Answered in #220
