### ISSUE TITLE
[Bug]: God Mode/Shovel Issues

### ISSUE THREAD

**Issue by zerevoidd** [winstxnhdw/lc-hax#246]
### What happened?

Enabling godmode while also having antikick on (being invisible) makes killing other players (or hitting anything) impossible, as you'll just hit through them and not damage them at all.

### Current Commit Hash

I don't know how to do this, but I'm using the latest version available on github

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by zerevoidd** [comment]
What about when I would like to use normal godmode with it?

**Comment by winstxnhdw** [comment]
You just can't. It's a limitation.

**Comment by zerevoidd** [comment]
But why though?

**Comment by winstxnhdw** [comment]
If I knew, there wouldn't be a `demigod` command.

**Comment by winstxnhdw** [comment]
Okay, I have fixed this and removed `demigod` for good. You can now hit others with `/god`
