### ISSUE TITLE
[Bug]: M3 is stuck and always active?

### ISSUE THREAD

**Issue by MichaelDavidGK** [winstxnhdw/lc-hax#249]
### What happened?

M3 is stuck and always active?

I tried restarting game multiple times and when I press M3 it is then stuck forever (even if you press it again) and doesn't turn off until another restart.
I don't know if it's my mouse, but I don't encounter it outside the game, so probably not.

### Current Commit Hash

e9c1958

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Haven’t touched anything to do with the input listener in a long time. I am watching my friend streaming on latest right now. He’s not having any issue.

**Comment by winstxnhdw** [comment]
I just left my place. Are you using any mod?
