### ISSUE TITLE
[Feature Request]: Enhance control over the enemy.

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#250]
Discovered a mod that controls enemies, but only for the host to use. 
It can controls enemies to attack. Is it possible to utilize it?

https://thunderstore.io/c/lethal-company/p/ControlCompany/ControlCompany/

**Comment by winstxnhdw** [comment]
Always has been possible. Just a lot of time to invest.

**Comment by joep26020** [comment]
> Always has been possible. Just a lot of time to invest.

you couldn't just use the code from this mod, right?

**Comment by winstxnhdw** [comment]
I am not a paster, joep.

**Comment by xAstroBoy** [comment]
@winstxnhdw would be nice to tell if a enemy is controlled by this mod lol, a host spawned a nutcracker in front of me and i tried to kill it while in godmode

**Comment by winstxnhdw** [comment]
Possession doesn't stop a mob from being killed though.

**Comment by xAstroBoy** [comment]
> Possession doesn't stop a mob from being killed though.

i know, but it was hard to kill lol, and i figured it was host controlled by how he was shooting like crazy

**Comment by winstxnhdw** [comment]
I'll be focusing on this over the coming weeks.

**Comment by winstxnhdw** [comment]
Added in latest.
