### ISSUE TITLE
Feature : build anywhere?

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#254]
I dont get why it got removed, i reverted the removal and is still working

**Comment by winstxnhdw** [comment]
See #236

**Comment by xAstroBoy** [comment]
Yeah but still works if you try to overlap multiple objects together

**Comment by winstxnhdw** [comment]
What does that mean?

**Comment by xAstroBoy** [comment]
> What does that mean?

The patch fixed just you cannot build outside the ship, yet inside you can still put multiple stuff overlapped on themself, build everywhere should be renamed no build constraints, which still is similiar

**Comment by winstxnhdw** [comment]
Sure, I'll add it back in with a new name.

**Comment by winstxnhdw** [comment]
Tracked in #258

**Comment by xAstroBoy** [comment]
@winstxnhdw your nullcheck is not working, still breaks the build, just add if(foo != null) and is a easy fix..

**Comment by winstxnhdw** [comment]
no, i just used the wrong conditional like an idiot

**Comment by winstxnhdw** [comment]
Anyways, this is a very good time to reflect the use of `IsNotNull`. It used to be helpful at the start to handle fake nulls but now it has become a burden. It doesn't even provide type guard intellisense.
