### ISSUE TITLE
Bug : picked items are not picked for other players

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#255]
Sometimes picking items will not be synced with other players, im not sure if is this or is a mod, but i dont use any mods that should affect the items

**Comment by armorfid** [comment]
you mean with `/grab`?

**Comment by xAstroBoy** [comment]
@armorfid no, just normal grab, sometimes players still see the item im holding on the floor, or a item becomes ungrabbable.

**Comment by joep26020** [comment]
> @armorfid no, just normal grab, sometimes players still see the item im holding on the floor, or a item becomes ungrabbable.

game issue. i've had it before using lchax. sometimes i would see an object and try to grab it for it to go back to the same spot in a different orientation.

**Comment by armorfid** [comment]
yeah pretty sure it's a vanilla bug, been happening randomly since release
