### ISSUE TITLE
[Bug]: crosshair sometimes doesnt show up after injection

### ISSUE THREAD

**Issue by cmmaio** [winstxnhdw/lc-hax#260]
### What happened?

crosshair sometimes doesnt show up after injection and u can inject it again to fix but double injecting bugs out alot of other stuff

### Current Commit Hash

0a44dee59c1af3aae35941139368fe3a16ec4a8f

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Fixed in latest.
