### ISSUE TITLE
[Feature Request]: ESP and Clear Mod Toggleable Please

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#263]
### What happened?

Winston I know you've been asked about this already, but I really would appreciate it so much if you could make certain esp categories toggleable in game (eg a menu to toggle items/enemies/players and toggle on and off box/name and size of box/name) and the clear vision mod. Or if there is a way you fan make it so we can see in the factory without needing clear mod enabled, because if you don't it will be near pitch black and you can't see people. I like playing the game dark without esp it makes it more fun with randoms, but it sucks not being able to see anything when using possession or just in phantom mode.

### Current Commit Hash

newest

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You want clear vision yet you do not want it?

**Comment by joep26020** [comment]
> You want clear vision yet you do not want it?
Well I would just like it if you could toggle it on and off and adjust its strength. like do /clear [strength 0-100] and for esp a menu to toggle items/enemies/players and toggle on and off box/name and size of box/name

**Comment by joep26020** [comment]
> You want clear vision yet you do not want it?

Well I would just like it if you could toggle it on and off and adjust its strength. like do /clear [strength 0-100] and for esp a menu to toggle items/enemies/players and toggle on and off box/name and size of box/name

**Comment by winstxnhdw** [comment]
The size of the boxes are dynamic and changes according to the enemy’s renderer.

**Comment by winstxnhdw** [comment]
ESP is now toggleable because I understand that there might be performance or screen clutter concerns, but it is honestly hard to justify making `ClearVision` toggleable.

**Comment by joep26020** [comment]
> ESP is now toggleable because I understand that there might be performance or screen clutter concerns, but it is honestly hard to justify making `ClearVision` toggleable.

THank you so much Winston!... I will be using the hell out of this new feature lol

**Comment by winstxnhdw** [comment]
Variant added in #303
