### ISSUE TITLE
[Bug]: Whenever a player dies by a shovel their body and voice stays in the position killed, like if I use a /kill command it happens. 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#266]
### What happened?

Title

### Current Commit Hash

545454321nEW

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Well, I haven't pushed anything that could even contribute to this.

**Comment by joep26020** [comment]
> Well, I haven't pushed anything that could even contribute to this.

interesting well I'll try it in vanilla tommorrow and see if that's the same result.
