### ISSUE TITLE
[Feature Request]: Destroy all enemies on client

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#27]
Is it possible to implement a cmd to kill/destroy enemies on the client side?
just like ServerRpc

**Comment by winstxnhdw** [comment]
Probably, but my guess is that it would be a mod and not a command. I am not sure what would happen if we were to destroy all enemies on the client side and then a teammate sends a Enemy Sync RPC to your client.

**Comment by winstxnhdw** [comment]
I have pushed this feature. You can now kill all enemies, currently alive with `/kill --enemy`.
