### ISSUE TITLE
[Bug]: Enemy ESP broken

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#273]
### What happened?

Idk something with the newest changes			

### Current Commit Hash

adas

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
What's broken about it? I just tested and it seems fine to me.

**Comment by xAstroBoy** [comment]
> What's broken about it? I just tested and it seems fine to me.

i couldn't get it to show, could be that i broke something while patching it and adapting a quick mod, would you make a quick and easy module to disable the menu intro music?

**Comment by xAstroBoy** [comment]
> What's broken about it? I just tested and it seems fine to me.

just redownloaded the repo, enemy esp no longer shows up.

**Comment by winstxnhdw** [comment]
Closing this.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/6f70d780-b46b-42d3-ade2-b50aa12c1477)

**Comment by xAstroBoy** [comment]
> Doesn't look like the problem though.

yeah it happened again, with that mod off as well, im sure the helper that gets the enemies is failing sometimes.

**Comment by xAstroBoy** [comment]
@winstxnhdw can confirm 
<img width="697" alt="image" src="https://github.com/winstxnhdw/lc-hax/assets/92211398/d2fdaf82-48bc-4dc0-b4ad-5d4cf303b92a">

**Comment by winstxnhdw** [comment]
The helper is just a reference pointing to the game's spawned enemies list. So if it's empty, so is the game's.

**Comment by xAstroBoy** [comment]
> The helper is just a reference pointing to the game's spawned enemies list. So if it's empty, so is the game's.

No, the enemies were there around the ship, the helper returns a empty list sometimes.

**Comment by xAstroBoy** [comment]
@winstxnhdw there is a solution and a better reliable one than depending on roundmanager, you could use harmony and make your list based off that, is way better and it syncs even if is client side or server side.

**Comment by winstxnhdw** [comment]
Sure, but what's the difference if they reference each other?

**Comment by xAstroBoy** [comment]
@winstxnhdw also it catches them before they fully spawn, with their animations already, and i see the code automatically detecting new enemies before they came out of the ground.
