### ISSUE TITLE
[FEATURE]: Hide / stop vanilla menu music   

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#274]
i am super pissed that i cannot shut the music up, which i made this small mod, any enchancements are welcome.

private AudioSource? _MenuMusic;

 internal AudioSource MenuMusic {
     get {
         if (this._MenuMusic == null) {
             this._MenuMusic = GameObject.Find("Canvas/MenuManager").GetComponent<AudioSource>();
         }

         return this._MenuMusic;
     }
 }
 
 
    IEnumerator TurnMusicMenuOff() {
        WaitForEndOfFrame waitForEndOfFrame = new();
        while (this.MenuMusic == null) yield return waitForEndOfFrame;
        this.MenuMusic.Stop();
        this.MenuMusic.loop = false;
    }

**Comment by winstxnhdw** [comment]
This is fine but some people may not want to hide the menu music.

**Comment by winstxnhdw** [comment]
Maybe it is time I made a offline config file to allow users to configure these easily before compile-time.
