### ISSUE TITLE
[Bug]:  God Mode breaks ability to pick stuff 

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#276]
### What happened?

I found out now godmode once a enemy tries to kill you, for each damage over the health limit it now scuffs the ability to grab items.

**Comment by winstxnhdw** [comment]
Yeah, if a mob uses an insta-kill move on you, you get blocked.

**Comment by xAstroBoy** [comment]
@winstxnhdw seems a flag is responsible.

**Comment by winstxnhdw** [comment]
Yeah, that's likely, but there's several of them so it's pretty hard to narrow down.

**Comment by xAstroBoy** [comment]
Okay, the best approach would be to make god mode cover as well enemies fatality methods

**Comment by xAstroBoy** [comment]
solved in #317

**Comment by winstxnhdw** [comment]
I found a way better way to solve this in latest.
