### ISSUE TITLE
{Not a bug}  sor i don't understand how to install it

### ISSUE THREAD

**Issue by a66a66a** [winstxnhdw/lc-hax#278]
### What happened?

Windows cannot find      ./submodules/sharpmonoinjectorcore/dist/sharpmonoinjector.exe.

### Current Commit Hash

fatal: not a git repository (or any of the parent directories): .git

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by a66a66a** [comment]
i'm just a passerby who wants to use this modifier, not an engineer     sor

**Comment by a66a66a** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/156866148/fe908a28-c24f-40d3-83bb-08a7017999df)

**Comment by winstxnhdw** [comment]
You have to git clone the repository.

**Comment by a66a66a** [comment]
> You have to git clone the repository.

![image](https://github.com/winstxnhdw/lc-hax/assets/156866148/da1f9308-eab8-4367-a378-1b1d50234f96)
Like this?

**Comment by winstxnhdw** [comment]
Correct. Now open the folder. You can do it with `explorer .`

**Comment by a66a66a** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/156866148/0747cecf-c1fb-43fb-8c46-d8e0fae4a5d5)
i seem to have succeeded but nothing happens in the game

**Comment by winstxnhdw** [comment]
You need to run `requirements.bat` first.

**Comment by a66a66a** [comment]
> You need to run `requirements.bat` first.

omg i succeeded, thank you brother

**Comment by a66a66a** [comment]
thank you very much for taking the time to tell me what to do
