### ISSUE TITLE
[Bug]: A few things are broken in the new update of the game.

### ISSUE THREAD

**Issue by N3onKn1ght** [winstxnhdw/lc-hax#283]
### What happened?

the hilarious /ct command is broken as well as any other commands that teleport objects (/random, /pumpkin) also /void doesn't work. Sometimes when trying to take control of monsters (the issue is inconsistent it happens with monsters outside but not inside ones) they fly really far out of the map.

### Current Commit Hash

Newest

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
See #236
