### ISSUE TITLE
Issues with nameinweight mod i added manually.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#284]
### What happened?

Heres the log: 

Already up to date.
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj (in 298 ms).
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(10,35): error CS1061: 'Camera' does not contain a defin
ition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'Camera' could
be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(11,32): error CS1061: 'HUDManager' does not contain a d
efinition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'HUDManager
' could be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csp
roj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(12,39): error CS1061: 'TextMeshProUGUI' does not contai
n a definition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'TextM
eshProUGUI' could be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\
lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(10,14): warning CS8602: Dereference of a possibly null
reference. [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(11,14): warning CS8602: Dereference of a possibly null
reference. [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]

Build FAILED.

C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(10,14): warning CS8602: Dereference of a possibly null
reference. [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(11,14): warning CS8602: Dereference of a possibly null
reference. [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(10,35): error CS1061: 'Camera' does not contain a defin
ition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'Camera' could
be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csproj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(11,32): error CS1061: 'HUDManager' does not contain a d
efinition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'HUDManager
' could be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\lc-hax.csp
roj]
C:\Users\kaide\lc-hax\lc-hax\Scripts\Modules\NameInWeightMod.cs(12,39): error CS1061: 'TextMeshProUGUI' does not contai
n a definition for 'IsNotNull' and no accessible extension method 'IsNotNull' accepting a first argument of type 'TextM
eshProUGUI' could be found (are you missing a using directive or an assembly reference?) [C:\Users\kaide\lc-hax\lc-hax\
lc-hax.csproj]
    2 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.30
Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\kaide\lc-hax\bin\lc-hax.dll'.
File name: 'C:\Users\kaide\lc-hax\bin\lc-hax.dll'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

### Current Commit Hash

newestbuild

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
```cs
using UnityEngine;
using GameNetcodeStuff;
using Hax;

public sealed class NameInWeightMod : MonoBehaviour {
    RaycastHit[] RaycastHits { get; set; } = new RaycastHit[50];

    void SetWeightCounterText() {
        if (Helper.CurrentCamera is not Camera camera) return;
        if (Helper.HUDManager is not HUDManager hudManager) return;
        if (hudManager.weightCounter is not TMPro.TextMeshProUGUI weightCounter) return;

        foreach (int i in this.RaycastHits.SphereCastForward(camera.transform).Range()) {
            if (!this.RaycastHits[i].collider.TryGetComponent(out PlayerControllerB player)) {
                continue;
            }

            weightCounter.enableWordWrapping = false;
            weightCounter.text = $"#{player.playerClientId} {player.playerUsername}";
            break;
        }
    }

    void LateUpdate() {
        this.SetWeightCounterText();
    }
}
```

**Comment by joep26020** [comment]
> ```cs
> using UnityEngine;
> using GameNetcodeStuff;
> using TMPro;
> using Hax;
> 
> public sealed class NameInWeightMod : MonoBehaviour {
>     RaycastHit[] RaycastHits { get; set; } = new RaycastHit[50];
> 
>     void SetWeightCounterText() {
>         if (Helper.CurrentCamera is not Camera camera) return;
>         if (Helper.HUDManager?.weightCounter is not TextMeshProUGUI weightCounter) return;
> 
>         foreach (int i in this.RaycastHits.SphereCastForward(camera.transform).Range()) {
>             if (!this.RaycastHits[i].collider.TryGetComponent(out PlayerControllerB player)) {
>                 continue;
>             }
> 
>             weightCounter.enableWordWrapping = false;
>             weightCounter.text = $"#{player.playerClientId} {player.playerUsername}";
>             break;
>         }
>     }
> 
>     void LateUpdate() {
>         this.SetWeightCounterText();
>     }
> }
> ```

thank you!
