### ISSUE TITLE
Understanding the function of /shovel

### ISSUE THREAD

**Issue by yujispin990** [winstxnhdw/lc-hax#29]
### What happened?

Tried different values for /shovel did not notice any change when hitting enemies or teammates, i might not properly understand what the shovel force contributes too, could i ask for the devs to educate me, please and thank you. 

p.s beautiful freaking work my dudes, this is the most feature rich enhancement i've ever used.

### Current Commit Hash

49928a4

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
`/shovel 100000`. Apparently, it doesn't work when you are in God mode.

**Comment by yujispin990** [comment]
like for example i thought of maybe shovel force affects teammates who are holding the shovel as well so i set it to 0 so they do not do any damage. But nothing happened.

**Comment by winstxnhdw** [comment]
Nope. `/shovel` only works on yourself.

**Comment by yujispin990** [comment]
ah but i had not used /god at all tbh, so how does the value work? if i put /shovel 10 for example it does 10 points of damage? what happens if i put /shovel 100000 it would instantly kill enemies AND teammates?

**Comment by winstxnhdw** [comment]
For reference, a hoarding bug only has 3 points of HP. By default, your shovel does 1 point of damage.

**Comment by winstxnhdw** [comment]
Looks like I introduced a bug into `shovel` mod somewhere. It's actually broken. I'll fix it in a minute.

**Comment by winstxnhdw** [comment]
It's fixed now.

**Comment by yujispin990** [comment]
alrighty thank you!
