### ISSUE TITLE
git prompt: Permission denied

### ISSUE THREAD

**Issue by sdclkja** [winstxnhdw/lc-hax#293]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/5ca54cc0-1d8e-411a-a21a-f2960658711c)
What should I do?

**Comment by winstxnhdw** [comment]
Looks like you aren't using the default install got `git` or some antivirus is messing with the installation. You can try using PowerShell instead.

**Comment by sdclkja** [comment]
I typed git clone --recursive https://github.com/winstxnhdw/lc-hax.git. It prompts
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/92cce21f-2089-485a-8a27-51b9833bec3d)

**Comment by winstxnhdw** [comment]
I see `lc-hax-main` which means you downloaded the repository as zip. Don't do that. Delete `lc-hax-main` and do a `git clone` there instead.

**Comment by sdclkja** [comment]
I downloaded the zip and did what you said, that's it, what's wrong with that?

**Comment by winstxnhdw** [comment]
Don't download the zip.

**Comment by sdclkja** [comment]
？？？？？？？？？？？？？？？？？

**Comment by sdclkja** [comment]
what do I download?

**Comment by winstxnhdw** [comment]
Just use the `git clone` command to download the repository.

**Comment by winstxnhdw** [comment]
执行 git clone 将会下载仓库。你不需要下载其他任何东西

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/2dd935a5-96b5-448e-a0d0-d42250ca11bc)

**Comment by winstxnhdw** [comment]
Something is wrong with your `git` installation but you can just bypass this temporarily with the following.

```bash
git config --global http.sslVerify false
```

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/9e8b3d15-5225-444d-9579-a7187d3841b1)

**Comment by winstxnhdw** [comment]
Please just reinstall your `git`.

https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe

**Comment by sdclkja** [comment]
还是这样

**Comment by sdclkja** [comment]
so...

**Comment by winstxnhdw** [comment]
Just paste this.

```ps1
cd $env:USERPROFILE\Desktop
git clone --recursive https://github.com/winstxnhdw/lc-hax.git
explorer .
```

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/2882bc1f-4656-4fbc-bdb5-f695a8422495)
ok

**Comment by winstxnhdw** [comment]
Good. Now just run `requirements.bat` then open your game and run `launch.bat`.

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/c3902cc3-3f9d-4198-9b32-9488e441a46f)
but

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/0c76453c-49fe-4f10-9d45-72395762c37f)

**Comment by winstxnhdw** [comment]
There's a problem with your CMD. Use `PowerShell` again and paste the following.

```bash
cd $env:USERPROFILE\Desktop\lc-hax
git submodule upate --init
```

Then from now on, just use `launch-dev.bat` instead.

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/f67c4b80-b799-42a2-bf73-55e8ccc31a38)

**Comment by sdclkja** [comment]
what the fnck......

**Comment by winstxnhdw** [comment]
I wrote the wrong command just now. Use the new one that I updated.

**Comment by sdclkja** [comment]
ok

**Comment by sdclkja** [comment]
issue

**Comment by winstxnhdw** [comment]
All okay?

**Comment by sdclkja** [comment]
Give me your orders.

**Comment by winstxnhdw** [comment]
```bash
cd $env:USERPROFILE\Desktop\lc-hax
dotnet publish submodules/SharpMonoInjectorCore
```

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/7c77aa73-f154-4463-b867-103aba8acf93)

**Comment by winstxnhdw** [comment]
What the…

**Comment by sdclkja** [comment]
No files in the current directory?

**Comment by sdclkja** [comment]
![Uploading image.png…]()

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/cb781a29-ad41-4e62-bc1b-9fb0784e8aec)

**Comment by sdclkja** [comment]
Please change the directory to desktop

**Comment by winstxnhdw** [comment]
Tell you what. Download this https://github.com/winstxnhdw/SharpMonoInjectorCore as zip, extract and put everything inside submodules/SharpMonoInjectorCore folder

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/5921bb71-8b2e-496a-9362-6333ad9fd844)

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/e6ce8a2d-31f1-4327-8d83-b8d203e49ef6)

**Comment by winstxnhdw** [comment]
Take everything out from SharpMonoInjectorCore-main and put it inside submodules/SharpMonoInjectorCore

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/c4af4de7-da8a-4f75-9461-7093f1125bb4)

**Comment by sdclkja** [comment]
but

**Comment by sdclkja** [comment]
?

**Comment by winstxnhdw** [comment]
```bash
cd $env:USERPROFILE\Desktop\lc-hax
dotnet publish submodules/SharpMonoInjectorCore
```

You still need to run this..

**Comment by sdclkja** [comment]
funk

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/e89ad68e-46f1-4af1-9478-afe198a2b2e2)

**Comment by sdclkja** [comment]
Denial of access......

**Comment by winstxnhdw** [comment]
Try running your `PowerShell` as admin

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/ed94b694-4e1a-4206-b64f-de4d23b30a71)

**Comment by sdclkja** [comment]
emmmmm

**Comment by winstxnhdw** [comment]
Good. It's working. Now wait.

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/98793b08-13c8-45f9-bea9-bc6280588a58)

**Comment by winstxnhdw** [comment]
Yes. Done.

**Comment by sdclkja** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/139187715/31d78e3c-b441-476a-96ec-d43fddb82897)

**Comment by winstxnhdw** [comment]
There's no problem.

**Comment by sdclkja** [comment]
![Uploading image.png…]()

**Comment by sdclkja** [comment]
How do I open the menu?

**Comment by sdclkja** [comment]
That's my last question.

**Comment by winstxnhdw** [comment]
There is no menu. Use the chat.

**Comment by sdclkja** [comment]
okok
thank you!!!!!!!!!!!!!!!

**Comment by winstxnhdw** [comment]
You should still try to fix your `git` so you can get future updates.
