### ISSUE TITLE
[Bug]: Home command lists tp help

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#30]
### What happened?

The home command will for some reason display tp help. Maybe you changed the format of /tp and home uses the old one? I was having issue using git to pull old versions so all I know is that home works fine on this commit ```6f9cf9a``` and breaks on this one ```49928a4```.
I also tested the latest commit.
No mods were used. Pure vanilla.

### Current Commit Hash

051786c

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Hey, looks like I misunderstood a feature in C#. I have pushed a fix for it. Sorry about this.
