### ISSUE TITLE
[FEATURE REQUEST]: Silent Join Notification

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#301]
### Silent Join Notification (Main Future)
Add a future that removes your join ship message, it would automatically enable when anti-kick is on like invis,, how it works when enabled joining a game will copy the last 5 or 8 messages in chat from the server and players, then afterwards spams nothing in the chat through a server message so it clears it, then it sends the copied messages in the exact order and type, this would make the effect where your "join ship notification" in chat doesn't appear when you join a server.

**Main Future Note**:
Other than being able to copy previous messages I know everything else individually is possible through other menus.

### Mute Player In Chat (Possibly Secondary Future)
If the first request is possible could possibly rework it where you can mute players in chat, it would function the same but if it detects a certain player that's muted in chat that's not a spoof from you, it does the entire routine but leaves out the players message once it sends the messages back in.

**Comment by winstxnhdw** [comment]
You sir, are very creative. Great idea!

**Comment by winstxnhdw** [comment]
There may not be a way get the previous chat history if you just joined, but you just introduced a really useful concept. I can still make this happen and it might be better than your initial suggestion.

**Comment by joep26020** [comment]
> There may not be a way to get the previous chat history if you just joined, but you just introduced a really unique and useful concept. I can still make this happen and it might be better than your initial suggestion.

I suppose you can still spam blank messages or random other players who are on the player list

**Comment by winstxnhdw** [comment]
Yup, that’s the idea.

**Comment by D1GQ** [comment]
> There may not be a way to get the previous chat history if you just joined, but you just introduced a really unique and useful concept. I can still make this happen and it might be better than your initial suggestion.

True I didn't really think about that, the fact that there's no chat history when you join, another way to do it, this wouldn't be as convincing as the last one but you can also make it where once you join it instantly makes a fake disconnect message with your username like "NAME disconnected.", because when you have anti kick on your original username still appears in the chat when you first join, this would make it less suspicious when your body appears for a split second then disappears when you join.

**Comment by winstxnhdw** [comment]
Seems like I've done it. It's beautiful.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/60b6b5f1-79ce-4d44-9d6e-19ba0015654d)

**Comment by D1GQ** [comment]
> Seems like I've done it. It's beautiful. Thanks @D1GQ again for the great idea.
> 
> ![image](https://private-user-images.githubusercontent.com/56998716/300099874-60b6b5f1-79ce-4d44-9d6e-19ba0015654d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDExMjYsIm5iZiI6MTcwNjMwMDgyNiwicGF0aCI6Ii81Njk5ODcxNi8zMDAwOTk4NzQtNjBiNmI1ZjEtNzljZS00ZDQ0LTlkNmUtMTliYTAwMTU2NTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIwMjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmU4M2U5MDQ2NDM2YzgxYWFmMTVlY2Y5YjU2Nzg0NTlhOGVmYTQ1YmYxODU2YjljYThjZTA1MmJhMDliZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H2YTYnKS0rh3bvj6uLvg6U2pKCuwMhoXTErA8l3pT3A)

np, this is something I usually pulled off with other menus but I thought it would just be nice to have it automatic. if I think of anything else I'll send an future request.

**Comment by winstxnhdw** [comment]
This is now in latest.

**Comment by winstxnhdw** [comment]
> If the first request is possible could possibly rework it where you can mute players in chat, it would function the same but if it detects a certain player that's muted in chat that's not a spoof from you, it does the entire routine but leaves out the players message once it sends the messages back in.

Mute is a great feature but it's quite the challenge to add to the codebase in a clean way without a lot of coupling. I have added `/mute` as a debug command temporarily because I don't have anyone to test it with.

If anyone would like to give it a try, do let me know how it goes.

**Comment by D1GQ** [comment]
> Mute is a great feature but it's quite the challenge to add to the codebase in a clean way without a lot of coupling. I have added `/mute` as a debug command temporarily because I don't have anyone to test it with.
> 
> If anyone would like to give it a try, do let me know how it goes.

I don't mind becoming a tester for you, I know a lot of people have trouble making cheats because they don't have people to test it on.

**Comment by winstxnhdw** [comment]
It's fine. I am not in a rush. I'll let joep and friends play around with it.

**Comment by joep26020** [comment]
> It's fine. I am not in a rush. I'll let joep and friends play around with it.

yessir will do
