### ISSUE TITLE
[FEATURE REQUEST] Night Vision

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#303]
### What happened?

Can you make a way to increase the amount of light from everywhere like PDK's mod menu? Even with clear vision, it is still somewhat hard to see.

### Current Commit Hash

a1b2c3d4

### Injector

- [x] SharpMonoInjectorCore
- [x] Others

### Acknowledgement

- [x] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [x] I have done my due diligence to check for similar issues

**Comment by joep26020** [comment]
> Ah, my bad. Previously, it was so bright that you couldn't see the snow texture on Titan. For now, you can just change the value on this line to a higher one.
> 
> https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Modules/ClearVisionMod.cs#L40
> 
> Setting it to 5 is pretty good.

can you make a command for that? like /night vision (0-10)

**Comment by IntegrityPerson** [comment]
I would appreciate it

> I am not sure if it’s a good experience to play a game where you constantly have to adjust the brightness. Sounds annoying as heck to me.

**Comment by joep26020** [comment]
> I am not sure if it’s a good experience to play a game where you constantly have to adjust the brightness. Sounds annoying as heck to me.

I would appreciate it also

**Comment by winstxnhdw** [comment]
Alright, this has been added in latest with the `F4` and `F5` keys.

**Comment by joep26020** [comment]
> Alright, this has been added in latest with the `F4` and `F5` keys.

GOD BLESS YOU! thank you Winston
