### ISSUE TITLE
[FEATURE REQUEST]: Target Player With Commands

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#304]
### Target Player With Commands
The idea is to pretty much to add a new trigger mod with an extra keybind like Follow Player, but it targets a player, when active it would make it where when you type a command that requires a player Target/Name you can just put "target" at the end and it would automatically use that player for the command, this would be easier to use player commands on players with long names and when you have anti kick on but someone else joined afterwards.

**Comment by winstxnhdw** [comment]
Just use their player IDs instead. `/kill 0`
