### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jax2213** [winstxnhdw/lc-hax#307]
### What happened?

the antikick only works until a player joins and if they join i get named nameless so i need to close and relaunch the game for it to work again could you pls update it or find a work around i tried reinstalling and updating and running it with mods but none of the things i tried worked

### Current Commit Hash

cmd couldn't find anything

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You are not the first to have noticed this. Read #149.
