### ISSUE TITLE
[Help]: How to change colours of ESP?

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#308]
### What happened?

It's kinda hard to see certain items apart from others. How to change the colours of the ESP so I can be more specific?

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [x] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You can add your own filter here: https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Modules/ESPMod.cs#L87

**Comment by IntegrityPerson** [comment]
> You can add your own filter here: https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Modules/ESPMod.cs#L87

Thank you!
