### ISSUE TITLE
[Bug]: Overall Possession Movement

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#309]
**Overall Possession Movement**
the Possession movement may need a rework or something, it works better than any other menu but the velocity is really weird, like you can't go upstairs cases without jumping, it's hard to go up hills and you get a lot of speed going down Hills, just wondering if there's a way to use the normal Movement like a player or control company, and maybe even have different monsters have different speeds.

**Side Note**:
it seems that Possessing/Phantom breaks after a while and once it breaks you can't possess or interact with anything in Phantom Mode, the only way to fix it is to restart the game.
Also I know this is way easier to be said than done but maybe one day in the future add support where you can use the abilities of monsters like a control company.

**Comment by winstxnhdw** [comment]
Already tracked in #250 and #102
