### ISSUE TITLE
[Bug]: Crash Failed to Inject

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#314]
### What happened?

![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/69afeef8-2beb-4586-b67b-87ee3c4b5142)

What do I do if this happens?

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You report it because I broke something. I fixed in latest. You can try again.
