### ISSUE TITLE
[Bug]: Another Failed Inject

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#315]
### What happened?

![image_2024-01-28_000155552](https://github.com/winstxnhdw/lc-hax/assets/157595981/709b981d-3e9b-43b9-8244-67f574847ec0)

Now it shows this.

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Try again.

**Comment by IntegrityPerson** [comment]
> Try again.

All good. I'm sorry for disturbing you if it's been a lot of trouble.
