### ISSUE TITLE
[Feature Request]: Force Disconnect Keybind

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#318]
### Force Disconnect Keybind
Plain and simple make a keybind combination that forcibly disconnects you from the server you're connected to, when you mess around with Phantom mode it seems like a lot of bugs happen especially in Modded where you can't pause or spectate so you have to restart your game, and sometimes you just get stuck in the wall when you join modded. So it would be nice if you were able to just force disconnect.

### Some Other Random Future
Also this is completely unrelated but it also be nice if there is a silent way and a way to choose a player id to end game, silent where once you end the game it automatically clears the chat, then the other option would to choose a player ID to end the game.

**Comment by D1GQ** [comment]
> `/fixcamera` exists

Well when it happens you can't even type in chat.

**Comment by winstxnhdw** [comment]
If you can’t even type, nothing I do can help you. Something is breaking at an even more fundamental level.

**Comment by winstxnhdw** [comment]
Alright, I’ll see what I can do.

**Comment by winstxnhdw** [comment]
This is added in latest with `Shift` + `F4`.
