### ISSUE TITLE
[Bug]: This keeps reverting to gray

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#319]
### What happened?

![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/5faec4a0-20fe-4609-b30f-c6646bdecf23)

How to permanantly change gray to different colour

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by IntegrityPerson** [comment]
To clarify, when I put in "green" it always reverts to gray on inject.

**Comment by winstxnhdw** [comment]
Are you saving the file? Try using launch-dev.bat instead?

**Comment by winstxnhdw** [comment]
Nvm, this is an issue with the new launch file. Fixed in latest.
