### ISSUE TITLE
M3 trigger mode BUG

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#32]
There seems to be a small bug in the trigger mode of M3, where sometimes when triggering players in multiplayer games, it causes oneself to have no collision, resulting in passing through the ground and falling. After multiple tests, it was found that this bug only occurs when using the trigger mode on other players, and the trigger mode now seems to make enemies appear on the target player's body on the client side, sometimes disappearing on the client side.

**Comment by winstxnhdw** [comment]
@LTYGUY

**Comment by winstxnhdw** [comment]
You are right. If we can get to the bottom of this, we can probably make a new command out of this.

**Comment by winstxnhdw** [comment]
Yes, the issue seemed to appear when we start teleporting enemies to the player.

**Comment by winstxnhdw** [comment]
Hey, I’ve pushed the theoretical fix for this. We’ve decided that it would be best to remove the functionality to teleport enemies to player. It’s unfortunate, I know but even if we do prevent ourselves from falling off, there would be no way to prevent the target player from falling off the map.

Please pull the latest version and let us know if you are still experiencing this issue.
