### ISSUE TITLE
[Question]: can we add a few host features?

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#320]
just curious, because we could have a /spawn enemy command, along with a bunch of host features.

**Comment by winstxnhdw** [comment]
no. if it’s a small feature, we can add it as a debug command.

**Comment by xAstroBoy** [comment]
> no. if it’s a small feature, we can add it as a debug command.

I might have a idea for a way to workaround the host check and still send the host rpcs which would work

**Comment by winstxnhdw** [comment]
Sure, but I doubt it’s possible.

**Comment by xAstroBoy** [comment]
> Sure, but I doubt it’s possible.

How so? I dont see any server check that is from the method, spoofing a server rpc as the host with harmony should be  fairly easy

**Comment by winstxnhdw** [comment]
See #237 

You are likely going to waste your time like me.

**Comment by winstxnhdw** [comment]
Of course. How else would I do it.

**Comment by winstxnhdw** [comment]
You can give it a try though. If you manage to do it, it’ll be a great breakthrough and the first in the world LOL

**Comment by xAstroBoy** [comment]
> You can give it a try though. If you manage to do it, it’ll be a great breakthrough and the first in the world LOL

i did copy the RPC command and remove the host checks, is sending them to the server,  but yeah is a waste of time :C

**Comment by winstxnhdw** [comment]
I am adamant that they should stay as debug commands and never more. I want the exposed features to be consistent without surprises.

**Comment by winstxnhdw** [comment]
At the end of the day, you can always load this mod with game master and have the features you want. The debug commands should also not have any consistent performance penalty.

**Comment by xAstroBoy** [comment]
except for a annoying extra message that gets printed every single time you use a debug command.

**Comment by winstxnhdw** [comment]
It's the same as you printing out that it is a host-only command, so I don't see a problem there.
