### ISSUE TITLE
[Bug]:  loader keeps adding back deleted haxmodules after startup. 

### ISSUE THREAD

**Issue by jjcoo51** [winstxnhdw/lc-hax#321]
### What happened?

tried this at least 10 times now. after the last update the loader keeps bringing back removed haxmodules upon injecting. Didnt see any posts about it happening so wasnt sure if it was just on my end or what. 

### Current Commit Hash

58e23b7

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Might be what I changed in launch.bat. I changed it because @Dexteriority was saying he couldn’t update. I’ll revert it.

**Comment by winstxnhdw** [comment]
I’ve reverted it. Do try again.

**Comment by Dexteriority** [comment]
> Might be what I changed in launch.bat. I changed it because @Dexteriority was saying he couldn’t update. I’ll revert it.

sorry (`•ω•`)//
