### ISSUE TITLE
[Bug]: When I kill the monster, from the perspective of other players, it is still alive and can attack them.

### ISSUE THREAD

**Issue by wreck0** [winstxnhdw/lc-hax#323]
### What happened?

When I kill the monster, from the perspective of other players, it is still alive and can attack them.

### Current Commit Hash

A1B2C3D4

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
How are you killing them? With a shovel?

**Comment by winstxnhdw** [comment]
Closed due to inactivity.
