### ISSUE TITLE
[Feature Request]: Automatic Reconnect

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#326]
### Automatic Reconnect
I don't know if this is possible but it would be cool if you could toggle something called Automatic Reconnect, when enabled if you get disconnected by any means by a server that's in the ship you automatically attempt to reconnect to that server, this would mostly work with anti kick because even if you are kicked after someone joins, you can instantly join back into the server when if it was enabled. And possibly make it where if you do rejoin a server it clears the chat so it doesn't send your join ship message.

I'm not fully sure about this idea though because seems like it would be used for more bad than good, but that's up to you to decide.

**Comment by joep26020** [comment]
> ### Automatic Reconnect
> I don't know if this is possible but it would be cool if you could toggle something called Automatic Reconnect, when enabled if you get disconnected by any means by a server that's in the ship you automatically attempt to reconnect to that server, this would mostly work with anti kick because even if you are kicked after someone joins, you can instantly join back into the server when if it was enabled.
> 
> I'm not fully sure about this idea though because seems like it would be used for more bad than good, but that's up to you to decide.

I think this would be a good feature to add. Often times I get kicked for no apparent reason. I join and then the host kicks me instantly. Then I have to scroll and find the lobby again, and they do the same thing. So I think it would be useful.

**Comment by winstxnhdw** [comment]
Yeap, sounds good. I’ll look into it.

**Comment by winstxnhdw** [comment]
This has been added in latest. It's pretty sick.
