### ISSUE TITLE
[Bug]: Injecting after ship lands breaks EnemyESP

### ISSUE THREAD

**Issue by winstxnhdw** [winstxnhdw/lc-hax#328]
### What happened?

This happens because the method used to populate the Enemy Hashsets are not updated when enemies have already spawned.

cc: @xAstroBoy

### Current Commit Hash

c08b417d8a71d44c9db8cb22e6985e626006d6aa

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by xAstroBoy** [comment]
instead of .Start() use .Update()

**Comment by winstxnhdw** [comment]
Running `Add` on every frame is insane. I think we might have to revert back to using `HaxObjects`.
