### ISSUE TITLE
[Bug]: cant turn hear off

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#330]
### What happened?

not sure why but hear is always on

### Current Commit Hash

44444d

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Okay, nvm. There was a bug. Fixed in latest.

**Comment by joep26020** [comment]
oh my goodness it is PERFECTTTTT. i have had so much fun just making a zombie apocalypse lmao

**Comment by joep26020** [comment]
there is 1 small issue though: if you spawn a lot (50+) they get stuck together and slowly move out like an army of ants 1 at a time. 
![Lethal Company Screenshot 2024 01 29 - 17 34 57 94](https://github.com/winstxnhdw/lc-hax/assets/143763241/0ff62e61-d55a-4f87-8313-d4ae5a213954)

**Comment by winstxnhdw** [comment]
I don't think it's worth the effort fixing this issue.

**Comment by joep26020** [comment]
> I don't think it's worth the effort fixing this issue.

true, no problemo
