### ISSUE TITLE
[Bug]: Possession: Gravity and velocity fixes

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#331]
Just been taking a look at the code and it looks like when you pulled in the possession branch you reverted the gravity logic, I don't know if there were issues with my new logic but the problems with the old one is if you don't jump for a while then walk off a ledge your velocity still increases so you just teleport to the bottom, the new code prevents you from Gaining velocity while on ground and resets it. Also suggest adjusting the gravity a bit so it's a bit more less floaty and where you don't Glide when you're going downstairs.

### Changes
**Old**:
```
        void ApplyGravity() {
            Vector3 motion = Vector3.zero;
            this.VelocityY -= gravity * Time.deltaTime;
            motion.y = this.VelocityY;
            _ = this.CharacterController.Move(motion * Time.deltaTime);
        }
```
**New**:
```
        // Gravity adjustments
        const float jumpForce = 9.2f;
        const float gravity = 18.0f;
        const float maxVelocityMagnitude = 15.0f;


        // New gravity logic
        void ApplyGravity() {
            if (CharacterController.isGrounded) {
                this.VelocityY = 0f;
            }
            else {
                this.VelocityY -= gravity * Time.deltaTime;
            }
            Vector3 motion = Vector3.zero;
            motion.y = this.VelocityY;
            _ = this.CharacterController.Move(motion * Time.deltaTime);
        }
```

**Comment by winstxnhdw** [comment]
I removed it because `isGrounded` actually doesn’t work here.

**Comment by D1GQ** [comment]
> I removed it because `isGrounded` actually doesn’t work here.

Interesting this might be a dumb question but is there a reason why? I've tested myself and seems that it fixes the velocity issues.

**Comment by D1GQ** [comment]
> It might be something else that fixed it but `isGrounded` is leftover Unity code that the developer never intended to implement so it is not trustworthy here. I’ve tested it before but I could be wrong. Does the issue of falling off the ledge still happen with my change? I didn’t find anything unusual in my testings.

I downloaded a fresh version of the branch and it was a issue, then I added that logic in it seems that it wasn't happening again, but it's also strange because I can't use the is grounded Logic on the jumping for some reason so your point makes sense, I don't know what's going on.

**Comment by D1GQ** [comment]
Let me test things further and I'll give you an answer.

**Comment by winstxnhdw** [comment]
Let me get back to you later. I am extremely fatigued.

**Comment by D1GQ** [comment]
Here whenever you can if you look at these videos the first video is from the main build so the normal code the second video is with my gravity logic, so I don't know what's going on.


https://streamable.com/w0seyk

https://streamable.com/nrm1hj

**Comment by joep26020** [comment]
> Here whenever you can if you look at these videos the first video is from the main build so the normal code the second video is with my gravity logic, so I don't know what's going on.
> 
> **Video 1** https://streamable.com/w0seyk
> 
> **Video 2** https://streamable.com/nrm1hj

interesting, i dont have those counters on the top right.

**Comment by D1GQ** [comment]
> interesting, i dont have those counters on the top right.

That's LethalMenu, I use it to spawn monsters to test.

**Comment by winstxnhdw** [comment]
> Here whenever you can if you look at these videos the first video is from the main build so the normal code the second video is with my gravity logic, so I don't know what's going on.
> 
> **Video 1** https://streamable.com/w0seyk
> 
> **Video 2** https://streamable.com/

Very strange. I think we should just cap the velocity then.

**Comment by xAstroBoy** [comment]
@winstxnhdw he's not wrong, isGrounded is a unity feature, you should use it here.

**Comment by winstxnhdw** [comment]
Try it out. It doesn't work sometimes.

**Comment by xAstroBoy** [comment]
> Try it out. It doesn't work sometimes.

Actually it does , i tried it out, your logic makes the enemy slip thru the holes, while his doesn't.

**Comment by winstxnhdw** [comment]
Slip through holes? The logic is for prevent the enemy from jumping in the air.

**Comment by xAstroBoy** [comment]
> Slip through holes? The logic is for prevent the enemy from jumping in the air.

Not just that, but as well not make it gravity suck the enemy into the hole, but just slowly fall into it.

**Comment by winstxnhdw** [comment]
Falling slowly is not realistic or what the mobs do in the game.

**Comment by xAstroBoy** [comment]
> Falling slowly is not realistic or what the mobs do in the game.

but for sure they dont fall in the holes of the maps like a bowling ball... we cannot block this from happening but we can somewhat slow it down which @D1GQ is doing.

**Comment by xAstroBoy** [comment]
> Have you seen an Eyeless Dog on Titan? They fall exactly like that when they chase you down the ladder.

yes but not on the inside part, outside is way different.

**Comment by winstxnhdw** [comment]
Okay. I’ll add it back.

**Comment by winstxnhdw** [comment]
I've added this back.

**Comment by winstxnhdw** [comment]
Probably need to play around with the collision box to prevent the ground clipping bug.
