### ISSUE TITLE
[FEATURE REQUEST]: Spawn Monsters and Items

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#337]
### What happened?

I'm not really surprised if you can't be bothered by implementing this, because I might be asking for a lot of work, I just don't know it, but they seem like some really nice additions. I also understand if they are impossible to code also.

Feature 1: Spawning monsters in the map. 
It's pretty self-explanitory. Basically you add a command where it spawns an entity somewhere based on the command. For example, you could tell it to spawn on a player or just randomly.

Feature 2: Spawning items
It's also pretty self-explanitory. Basically you add a command which allows you to spawn items such as scrap and other things like shotguns.

I think a lot of people really appreciate it if you considered adding these things, but as I mentioned before, don't feel the absolute need to do them if you don't want to.

Also, the dedication to fixing bugs and responding to comments from your side is genuinely impressive. I have never seen a creator so responsive as you are. You have my full respect. Have a good one.

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
This is host-only. We don't expose host-only features. There's a PR in #317 that will introduce spawning enemies but since it is host-only, it'll never be exposed in the README or recommended for use, nor will there be dedicated maintainer support for it. When it is merged, I'll notify this thread. For now, I'll be closing this as not planned.

**Comment by IntegrityPerson** [comment]
Alright. Also on an unrelated note, how do you disable the crosshair?

**Comment by winstxnhdw** [comment]
Comment out the crosshair mod. See the README.

**Comment by joep26020** [comment]
> This is host-only. We don't expose host-only features. There's a PR in #317 that will introduce spawning enemies but since it is host-only, it'll never be exposed in the README or recommended for use, nor will there be dedicated maintainer support for it. When it is merged, I'll notify this thread. For now, I'll be closing this as not planned.

did you merge the more poweful trigger mod from astro boy?

**Comment by xAstroBoy** [comment]
Not yet, i dont know why he's not approving the host command and add in readme, i might split the fork and maintain it myself at this point adding a few host commands and make it run with bepinex itself which makes it more less-inject required one day, for now im focusing on enchancing and fixing this mod.

**Comment by winstxnhdw** [comment]
+1 for splitting into a fork. My semester has just begun and I am beginning to have less and less time to focus on this project. So I think it would be better to have a version of this project with features others might want but I am not willing to maintain.

>  i dont know why he's not approving the host command and add in readme

This project started out as a non-host mod and I want it to stay as a non-host mod. That’s really what sets this project apart from everything else. As a user, the moment you inject this mod, that everything is usable no matter the conditions. I believe that there is beauty in it. I can’t compete with ProjectApparatus or LethalMenu, and I don’t ever plan to. The goal of this project is to write code that contributors find easy to understand and maintain, such that it would last as long as Lethal Company exists. I hope this answers your question.

**Comment by winstxnhdw** [comment]
> did you merge the more poweful trigger mod from astro boy?

I'll review and merge it my submissions on Sunday. If you have the [GitHub CLI](https://cli.github.com/) installed, you can use his PR by doing the following.

```bash
gh pr checkout 317
```

**Comment by xAstroBoy** [comment]
> +1 for splitting into a fork. My semester has just begun and I am beginning to have less and less time to focus on this project. So I think it would be better to have a version of this project with features others might want but I am not willing to maintain. I’d be happy to link to it in the README.
> 
> > i dont know why he's not approving the host command and add in readme
> 
> This project started out as a non-host mod and I want it to stay as a non-host mod. That’s really what sets this project apart from everything else. As a user, the moment you inject this mod, that everything is usable no matter the conditions. I believe that there is beauty in it. I can’t compete with ProjectApparatus or LethalMenu, and I don’t ever plan to. The goal of this project is to write code that contributors find easy to understand and maintain, such that it would last as long as Lethal Company exists. I hope this answers your question.

Yes but as well both mods can have host functionality and non , is still a unique and handy mod.

**Comment by winstxnhdw** [comment]
Nothing unique about this mod anymore. Especially, ever since teleporting objects was patched. Everything in here can be done in Project Apparatus or Lethal Menu.

**Comment by xAstroBoy** [comment]
> Nothing unique about this mod anymore. Especially, ever since teleporting objects was patched. Everything in here can be done in Project Apparatus or Lethal Menu.

the unique part of this mod is that is not intrusive at all.

**Comment by winstxnhdw** [comment]
I've been thinking about how I should implement host-only commands without them being debug commands and also maintaining consistency throughout the project, and I think I've come up with a great idea.

Introducing the `sudo` command. Using `sudo` will unlock `sudo` commands which require host privileges to run.

**Comment by IntegrityPerson** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/a012440a-4db6-4b26-bc03-24543407b591)

**Comment by xAstroBoy** [comment]
> ![image](https://private-user-images.githubusercontent.com/157595981/301833068-a012440a-4db6-4b26-bc03-24543407b591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzQ4NzMsIm5iZiI6MTcwNjg3NDU3MywicGF0aCI6Ii8xNTc1OTU5ODEvMzAxODMzMDY4LWEwMTI0NDBhLTRkYjYtNGIyNi1iYzAzLTI0NTQzNDA3YjU5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMTQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWJjYWYzNDgwOWJjMDQ4NDY3NDY1YjYxM2IxZTI1OTBmZTk0Nzg1ZTg3YjA1MDViNDZhN2FlZDQ0OTkwMTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nEcxCz77-QO2urBKfItGYOitE4vVjBEcEdx4PlTFxGA)

Because is not merged yet, i dont know why is taking so long to merge, and i find the /su useless as well

**Comment by IntegrityPerson** [comment]
We'll just wait patiently, he has other things to do than work on a mod.

**Comment by xAstroBoy** [comment]
> We'll just wait patiently, he has other things to do than work on a mod.

Yeah i know, but the code is ready and im now working on porting a bit of controlcompany features onto the possession mod

**Comment by IntegrityPerson** [comment]
cool

**Comment by winstxnhdw** [comment]
> Yeah i know, but the code is ready and im now working on porting a bit of controlcompany features onto the possession mod

At this point, you should just branch off and create a new PR.

**Comment by winstxnhdw** [comment]
Maybe `su` can be implicit instead. Since there’s a way to check if the player is host, we can probably remove `su`.

**Comment by xAstroBoy** [comment]
> Maybe `su` can be implicit instead. Since there’s a way to check if the player is host, we can probably remove `su`.

Yeah, and we dont need host control to take over a enemy AI , most RPCs used by control Company mod are owner based, which i think we can use a proper control over a existing enemy regardless, controlCompany allows only to control spawned enemies, which can be fun but that's all it does.

**Comment by winstxnhdw** [comment]
@xAstroBoy If your code quality was higher like @armorfid’s, it wouldn’t have taken this long. Learn to split features into smaller PRs.

**Comment by joep26020** [comment]
> > Maybe `su` can be implicit instead. Since there’s a way to check if the player is host, we can probably remove `su`.
> 
> Yeah, and we dont need host control to take over a enemy AI , most RPCs used by control Company mod are owner based, which i think we can use a proper control over a existing enemy regardless, controlCompany allows only to control spawned enemies, which can be fun but that's all it does.

hey how do i use your edited mod version

**Comment by armorfid** [comment]
> xAstroBoy If your code quality was higher like armorfid’s, it wouldn’t have taken this long. Learn to split features into smaller PRs and follow the codebase’s style.

coding has been my job for 10+ years, don't set the bar too high lol, video game modding in general involves a lot of newbie coders

side note, I been hella busy with work, but I have more commits left in me once crunch time's over

**Comment by winstxnhdw** [comment]
Yeah, I have no problem closing an eye for newbie coders but I just can’t merge that kind of code into the codebase 😭😭
