### ISSUE TITLE
[Bug]: teleporter prompt not working and autorejoin 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#340]
### What happened?

the prompt for teleport doesn't work for the triggermod, nor the inverse. also, could you add back when you press shift and f4 it puts you back in so you can be the last player to join?

### Current Commit Hash

5555555su

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Fixed in latest.
