### ISSUE TITLE
[FEATURE REQUEST]: F3 Disconnect Then Reconnect / Reconnect

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#342]
### F3 Disconnect Then Reconnect / Reconnect
Added a simple option instead of just disconnecting with Shift F4, You can disconnect then reconnect with Shift F3, also if you somehow get disconnected from the game and it doesn't attempt to reconnect you can just press Shift F3 to reconnect to the last game you were in.

### Code
**DisconnectMod.cs:**
```
using Hax;
using UnityEngine;
using Steamworks;
using System.Collections; // Added

public sealed class DisconnectMod : MonoBehaviour {
    bool IsShiftHeld { get; set; } = false;
    bool HasAnnouncedGameJoin { get; set; } = false;

    void OnEnable() {
        InputListener.onShiftButtonHold += this.HoldShift;
        InputListener.onF4Press += this.TryToDisconnect;
        InputListener.onF3Press += this.Rejoin; // Added
    }

    void OnDisable() {
        InputListener.onShiftButtonHold -= this.HoldShift;
        InputListener.onF4Press -= this.TryToDisconnect;
        InputListener.onF3Press -= this.Rejoin; // Added
    }

    void HoldShift(bool isHeld) => this.IsShiftHeld = isHeld;

    void TryToDisconnect() {
        if (!this.IsShiftHeld) return;

        GameNetworkManager.Instance.Disconnect();
        Setting.DisconnectedVoluntarily = true;
    }

    // Added
    void Rejoin() {
        if (!this.IsShiftHeld) return;
        GameNetworkManager.Instance.Disconnect();
        Setting.DisconnectedVoluntarily = true;
        _ = this.StartCoroutine(this.JoinLastGame());
    }

    // Added
    IEnumerator JoinLastGame() {
        yield return new WaitForSeconds(0.2f);
        this.HasAnnouncedGameJoin = false;
        if (Setting.ConnectedLobbyId is SteamId lobbyId) {
            GameNetworkManager.Instance.StartClient(lobbyId);
        }
    }
}
```

**InputListener.cs:**
```
using System;
using UnityEngine;
using UnityEngine.InputSystem;

public class InputListener : MonoBehaviour {
    public static event Action? onF3Press; // Added

    (Func<bool>, Action)[] InputActions { get; } = [
        (() => Keyboard.current[Key.F3].wasPressedThisFrame, () => InputListener.onF3Press?.Invoke()), // Added
    ];
}
```

**Comment by winstxnhdw** [comment]
What’s up with using coroutines here?

**Comment by D1GQ** [comment]
> IEnumerator JoinLastGame() {
>         yield return new WaitForSeconds(0.2f);

Because it wasn't trying to reconnect without adding a small delay, and it's like the easiest way to add a delay without adding too much code that I know of, if you have a better way you can change it lol.

**Comment by D1GQ** [comment]
This seems to also make it where if they host closes the game if you keep trying you can eventually rejoin if they made a new game, I don't know if this works all the time or not.

**Comment by D1GQ** [comment]
@winstxnhdw Is there a way to forcibly stop trying to connect to a game and go back to the main menu to prevent a "an error occurred" message?

**Comment by winstxnhdw** [comment]
Just don't press the ok button.

**Comment by Totoqoe** [comment]
> This seems to also make it where if they host closes the game if you keep trying you can eventually rejoin if they made a new game, I don't know if this works all the time or not.

Can confirm, your code even allows you to join the host if they rehost a private lobby.

**Comment by joep26020** [comment]
> > This seems to also make it where if they host closes the game if you keep trying you can eventually rejoin if they made a new game, I don't know if this works all the time or not.
> 
> Can confirm, your code even allows you to join the host if they rehost a private lobby.

how do you get it to keep retrying?

**Comment by D1GQ** [comment]
> how do you get it to keep retrying?
Take a look at https://github.com/winstxnhdw/lc-hax/pull/343

**Comment by winstxnhdw** [comment]
Added in #346
