### ISSUE TITLE
[Bug]: THE M3 COMMAND

### ISSUE THREAD

**Issue by tommyboi12321** [winstxnhdw/lc-hax#345]
### What happened?

how can i do the M3 command it wont let me use it can you mabye change the M3 controls to the F7 or something

### Current Commit Hash

123asd

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### If you selected "Others" above, please specify the injector you are using.

gg

### Log output

gg

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
`M3` is middle click.
