### ISSUE TITLE
[Bug]: Stamina and Weight mod not working

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#349]
### What happened?

I just restarted and reinstalled the mod. Inf stamina and no weight mods are not working.

Also do I need to reinstall the mod every time you update it? Or do I just need to launch it and it will update for me?

### Current Commit Hash

a1b2c3d4

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by IntegrityPerson** [comment]
Light mod is also not working

**Comment by IntegrityPerson** [comment]
Fixed

**Comment by winstxnhdw** [comment]
If you use `launch.bat` and you see no errors, it’ll update for you.

**Comment by IntegrityPerson** [comment]
Not working again.

**Comment by winstxnhdw** [comment]
Send your commit hash, logs and everything.

**Comment by IntegrityPerson** [comment]
How to do that?

**Comment by winstxnhdw** [comment]
`git rev-parse HEAD`

**Comment by IntegrityPerson** [comment]
Where do I enter it because
![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/58479cf9-fffb-4a8a-bbc0-20c485bb48f8)

**Comment by winstxnhdw** [comment]
Go to your `lc-hax` folder and do this.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/09a91470-e60c-4cdf-9525-8372fbadc025)

**Comment by IntegrityPerson** [comment]
Alrighty where are the logs?
![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/d53c33fd-5840-436c-94ac-013cecab71b4)

**Comment by winstxnhdw** [comment]
No logs, means there's no error. So just send the commit hash.

**Comment by IntegrityPerson** [comment]
7a0c2ef1e0ee0d82fc422228df4ceff04ee0e9a1

**Comment by winstxnhdw** [comment]
I can't replicate your problem. Are you on vanilla LC?

**Comment by IntegrityPerson** [comment]
Yes

**Comment by winstxnhdw** [comment]
Type `/su` in your chat and tell me what you see.

**Comment by IntegrityPerson** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/8f222b95-b200-4b61-926a-d3ea5721aff6)

**Comment by winstxnhdw** [comment]
Okay, I have no clue. You might have to reinstall your game or something. A modloader probably messed it up.

**Comment by IntegrityPerson** [comment]
;(
I got a gift that give 165 cash register lol. I have to get rid of that now ;( but alright I'll reload everything

**Comment by IntegrityPerson** [comment]
Whenever I delete all of my files and restart the game, when I reload everything is still there... Not supposed to happen right?

**Comment by IntegrityPerson** [comment]
Can someone give me a guide on how to reinstall my files?

**Comment by winstxnhdw** [comment]
Your save files are stored elsewhere. Uninstalling the game won’t remove them.

**Comment by IntegrityPerson** [comment]
I did before and tried again. Works fine now. Thanks for the advice. Have a good one.
