### ISSUE TITLE
[Feature Request]: allow short-form on commands that require player names

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#35]
### What happened?

also could you add a revive people/self command and a spawn worm on someone command that would be hilarious. also a player esp with names and box would be nice. and please fix it where you click ppl u dont go thru floor. also what does stunclick do? because when I use it, it lags my game. and also could you maybe make the ping work in phantom mode that way its easier to spot enemies and turrets for teammates. lastly, it gives me 4 fps when i sometimes m3 click players

### Current Commit Hash

...

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by yujispin990** [comment]
someone already asked for this.

**Comment by winstxnhdw** [comment]
You can type their player ID instead of their name. Do `/players` to see their player ID, or just look at them and it'll appear on the top left of your HUD.

**Comment by winstxnhdw** [comment]
Revive is not possible without host privileges.

Player ESP is planned.

Stunclick simulates throwing a stun grenade every time you left-click.

Scanning while in Phantom is already possible. It's just not possible if you are dead. We tried enabling it if you are dead but it was really really hard to implement so we gave up.

**Comment by joep26020** [comment]
> Revive is not possible without host privileges.
> 
> Player ESP is planned.
> 
> Stunclick simulates throwing a stun grenade every time you left-click.
> 
> Scanning while in Phantom is already possible. It's just not possible if you are dead. We tried enabling it if you are dead but it was really really hard to implement so we gave up.
> 
> There is not much I can do about the performance issue when you `M3` a player. It is already written pretty efficiently. There is possibility for slightly better performance if I hand-tune it further, but it's not going to solve your issue. Lethal Company itself, unmodded, is doing way more inefficient instructions than this mod ever can.

appreciate the response greatly!
