### ISSUE TITLE
[BUG] Build command not working

### ISSUE THREAD

**Issue by ivjvon** [winstxnhdw/lc-hax#350]
The build command used to work before now its just blank

**Comment by winstxnhdw** [comment]
That’s funny because the `build` command is the only one I tested. Send me the `lc-hax.log` file?

**Comment by winstxnhdw** [comment]
Works ok for me.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/a037c7bb-8772-4b8e-a50b-96eed0517f84)

**Comment by twiggie17** [comment]
> That’s funny because the `build` command is the only one I bothered to test, so it should be working. Send me the `lc-hax.log` file?

Hi I tried to do the build command also, host and friends lobby but no luck here is a image of it. every other command works but this one 
![image](https://github.com/winstxnhdw/lc-hax/assets/162192320/c81ba459-eb01-4402-a721-6626afe36b38)

**Comment by winstxnhdw** [comment]
Does `/random` spawn an inverse?

**Comment by twiggie17** [comment]
yes

**Comment by twiggie17** [comment]
sorry meant it will teleport them not spawn one

**Comment by winstxnhdw** [comment]
If you don’t have an inverse, it will spawn one first.

**Comment by twiggie17** [comment]
> Are you modded?

yes I got mods on through thunderstore atm

**Comment by winstxnhdw** [comment]
Might be why.

**Comment by twiggie17** [comment]
we have an inverse just bought one and it does do the inverse command like normal just not building, i was trying to build the teleporter but nothing showed
