### ISSUE TITLE
[Feature Request] Lightning strike other players

### ISSUE THREAD

**Issue by TheLGAOriginal** [winstxnhdw/lc-hax#354]
Is there any chance of adding a command to make lightning strike other players? Since random lightning has a fairly good chance of hitting players, this would probably pass as simple bad luck, giving us another option to troll players without creating suspicion.

**Comment by winstxnhdw** [comment]
We are starting to allow server-sided commands but I will only be accepting contributions of these commands and won't work on them myself.
