### ISSUE TITLE
[BUG]: possession mod feature may fail intermittently.

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#357]
In the new version, there is a possibility of being unable to repossess an enemy after using the "possess enemy" feature. 
When this bug occurs, it is still possible to press the X and N keys, and chat messages will indicate opening and closing, but repossessing the enemy is not possible.

It seems that this bug may occur if the possessed enemy dies.
Even rejoining the game does not resolve the issue; the only solution is to restart the game.

**Comment by winstxnhdw** [comment]
normally, i’d be happy to hear this and give credit to @xAstroBoy but the pain of merging that PR was too traumatising.

**Comment by xAstroBoy** [comment]
> normally, i’d be happy to hear this and give credit to @xAstroBoy but the pain of merging that PR was too traumatising.

Hey! I took time to reverse and adjust all ControlCompany mechanisms to this mod yet you did a complete overhaul when it was perfectly working!

**Comment by winstxnhdw** [comment]
working is the bare minimum.

**Comment by winstxnhdw** [comment]
Fixed in latest.
