### ISSUE TITLE
[Feature Request]: Add a way to bypass no team killing and the lock mod which locks players from moving objects (tp wont work)

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#36]
### What happened?

...

### Current Commit Hash

ddd

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
First part MIGHT be possible and was actually one of the first things I tried doing for this project but I didn't end up finding a way. If someone could help with this, it would be much appreciated.

Second, this is not possible. These actions are validated on their own client and we have no control over that.

**Comment by joep26020** [comment]
> First part MIGHT be possible and was actually one of the first things I tried doing for this project but I didn't end up finding a way. If someone could help with this, it would be much appreciated.
> 
> Second, this is not possible. These actions are validated on their own client and we have no control over that.

thanks!
