### ISSUE TITLE
[Bug]:  Possession Noclip no longer works

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#364]
Enemies under possession can no longer jump, or fly under noclip.

and ESP not showing all the items like sometimes initialize(0 does not get all of the lists

**Comment by xAstroBoy** [comment]
and ESP not showing all the items like sometimes initialize(0 does not get all of the lists

**Comment by winstxnhdw** [comment]
Fixed.

**Comment by xAstroBoy** [comment]
@winstxnhdw what about the ESP not getting all the items on ship land/ game start?

**Comment by winstxnhdw** [comment]
I don't see that problem.

**Comment by winstxnhdw** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/a442f6ab-88eb-4937-9501-b3f8ba38678c)

**Comment by xAstroBoy** [comment]
> ![image](https://private-user-images.githubusercontent.com/56998716/303756865-a442f6ab-88eb-4937-9501-b3f8ba38678c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDc0OTksIm5iZiI6MTcwNzUwNzE5OSwicGF0aCI6Ii81Njk5ODcxNi8zMDM3NTY4NjUtYTQ0MmY2YWItODhlYi00OTM3LTk1MDEtYjNmOGJhMzg2NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE5MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYThlZjU0ZjViNTQ3MjJjYzc3ZjkxZTliYzk4MmVmOThhZmVhZGEyNmQxMzNjMzE5ZDNlMmIwMzBkYWEwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oBZeFPEzs2vpEM7CULAIVJesBFE_85j9RCFmeClivPA)

items are always showing up, but not the doors and the rest, there's no entrance doors shown in that screenshot, not even the turrets or mines.

**Comment by winstxnhdw** [comment]
You're right

**Comment by xAstroBoy** [comment]
> You're right

Initialize() sometimes seems to be skipping or not finding these items, if i invoke it in UnityExplorer, everything shows up.

**Comment by winstxnhdw** [comment]
Maybe exiting ship phase is too early to find the renderers.

**Comment by winstxnhdw** [comment]
Fixed.

**Comment by winstxnhdw** [comment]
Nvm, it's not fixed.

**Comment by xAstroBoy** [comment]
> Nvm, it's not fixed.

yeah im investigating it as well a good way to fix it
would be better if we made a coroutine search ?

**Comment by winstxnhdw** [comment]
I'd rather revert to `OnShipLand`

**Comment by xAstroBoy** [comment]
> I'd rather revert to `OnShipLand`

that's what is that harmony event does  ..

**Comment by winstxnhdw** [comment]
Guess not since `OnShipLand` worked before.

**Comment by xAstroBoy** [comment]
> Guess not since `OnShipLand` worked before.

yeah but something broke during your changes? maybe something is giving a error?

**Comment by winstxnhdw** [comment]
Doesn't seem like it. The only reason why I changed from `OnShipLand` to `OnShipDescent` and now this is because I wanted less of a delay, but if it doesn't work, I'll just revert.

**Comment by xAstroBoy** [comment]
> Doesn't seem like it. The only reason why I changed from `OnShipLand` to `OnShipDescent` and now this is because I wanted less of a delay, but if it doesn't work, I'll just revert.

idk what to do, because you could as well re-run it if something essential such as entrances have nothing inside them.

**Comment by winstxnhdw** [comment]
Nvm, I got it. Seems like the issue was the event chaining.
