### ISSUE TITLE
[FEATURE REQUEST]: Debug Future For Possession

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#365]
### Debug Future For Possession
Add a future where before possessing an enemy it collects its position then later on if you click F1 it will teleport you to that position, I added this future to my own version for a temp fix of teleporting in the void and teleporting from the last possession position and it works pretty well. I know this isn't a fix to the teleportation issues but it's a possible quick Band-Aid while we find a way to fix those problems!

**Comment by winstxnhdw** [comment]
@D1GQ, do you think you could just reduce the scale of the character controller?

**Comment by D1GQ** [comment]
> @D1GQ, do you think you could just reduce the scale of the character controller?

I've tried that before but it seems like it didn't do much.

**Comment by winstxnhdw** [comment]
I am pretty sure the problem is the collider of the character controller though.

**Comment by D1GQ** [comment]
idk

**Comment by winstxnhdw** [comment]
Seems to be fixed after I set the scale to `0.0f`.

**Comment by joep26020** [comment]
> Seems to be fixed after I set the scale to `0.0f`.

hey winston how do we respawn now and is thata host only fetaure?
