### ISSUE TITLE
on some servers I can't type slash commands in chat so can you make a custom input

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#366]

**Comment by winstxnhdw** [comment]
I've added this. You can change the character on this line to whatever you want.

https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Patches/ChatPatch.cs#L23

**Comment by winstxnhdw** [comment]
You can now change the command prefix in runtime by doing `!prefix <prefix>`

**Comment by joep26020** [comment]
> You can now change the command prefix in runtime by doing `!prefix <prefix>`

Ok, this didnt fix it at the moment. I press enter and it highlights all the text even when you change the prefix. it somehow knows when i type a command and doesn't let me do it.

**Comment by winstxnhdw** [comment]
What do you mean?

**Comment by joep26020** [comment]
> What do you mean?

its hard to explain ill show a video

**Comment by joep26020** [comment]
https://github.com/winstxnhdw/lc-hax/assets/143763241/ae4bc06b-0e3f-4e9d-9032-591bdd3f94db

**Comment by winstxnhdw** [comment]
Aren't you supposed to use `!prefix @` then `@players`?

**Comment by joep26020** [comment]
> Aren't you supposed to use `!prefix @` then `@players`?

im confused? this does it with any commands. even like /kill. i ave also changed the prefix to ; and that still doesnt work. i think its the kaoscompany mod. but idk how they detect im inputting a command

**Comment by winstxnhdw** [comment]
Can you type at all?

**Comment by joep26020** [comment]
yes, i can do anything except if it inputs a command
for example i cant even type the prefix command, but  i can type ;players. but when i change the prefix to ; it doesnt work

**Comment by winstxnhdw** [comment]
What happens if you just type `;`? Can you send a screenshot?

**Comment by joep26020** [comment]
if i type / with the prefix set as '/' then it doesnt work. but when i type ; it does type. and also when i type ! it doesnt work either to change the prefix

**Comment by winstxnhdw** [comment]
https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Static/State.cs#L6

What happens if you change this to `;`?

**Comment by winstxnhdw** [comment]
It shouldn't ever be possible to block the command.

**Comment by joep26020** [comment]
ok, doing that right now. and i checked in vanilla and it works but with that mod it somehow knows im doing a commands

**Comment by winstxnhdw** [comment]
Yeah, I don't think a mod can do that. The most it can do is detect command prefixes and block them. But since you said you are able to type `;` then you should also be able to do `;players`.

**Comment by joep26020** [comment]
> It shouldn't ever be possible to block the command. It means you are doing something wrong.

yep, same result. it knows i am inputting a command, even if i simply type the ; prefix.

**Comment by winstxnhdw** [comment]
Okay, send me your `lc-hax.log` file. It's possible an exception is happening.

**Comment by joep26020** [comment]
> Okay, send me your `lc-hax.log` file. It's possible an exception is happening.

where is that

**Comment by winstxnhdw** [comment]
It's in your Lethal Company folder.

**Comment by joep26020** [comment]
> It's in your Lethal Company folder.

and where is that lol

**Comment by winstxnhdw** [comment]
You don't know where your Steam games are stored?

**Comment by joep26020** [comment]
[lc-hax.log](https://github.com/winstxnhdw/lc-hax/files/14233274/lc-hax.log)

**Comment by winstxnhdw** [comment]
```cs
[11-02-24 11:10:11] System.TypeInitializationException: The type initializer for 'Hax.Chat' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'SpawnCommand' threw an exception. ---> System.ArgumentException: An item with the same key has already been added. Key: RollingGiant
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in <787acc3c9a4c471ba7d971300105af24>:IL_015A 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000 
  at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0009e] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_009E 
  at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) [0x00000] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_0000 
  at SpawnCommand..cctor () [0x00016] in <094e5ad623344065861bc41aef0d6e0d>:IL_0016 
```

Seems like the `spawn` command is causing a problem.

**Comment by joep26020** [comment]
> ```cs
> [11-02-24 11:10:11] System.TypeInitializationException: The type initializer for 'Hax.Chat' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'SpawnCommand' threw an exception. ---> System.ArgumentException: An item with the same key has already been added. Key: RollingGiant
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in <787acc3c9a4c471ba7d971300105af24>:IL_015A 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000 
>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0009e] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_009E 
>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) [0x00000] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_0000 
>   at SpawnCommand..cctor () [0x00016] in <094e5ad623344065861bc41aef0d6e0d>:IL_0016 
> ```
> 
> Seems like the `spawn` command is causing a problem.

interesting. so do you want me to remove it on my files?

**Comment by winstxnhdw** [comment]
I read it closer. It seems that your modpack has added this enemy called `RollingGiant`, which is causing the issue.

**Comment by joep26020** [comment]
> I read it closer. It seems that your modpack has added this enemy called `RollingGiant`, which is causing the issue.

oh ok yeah thats a new entity we added

**Comment by winstxnhdw** [comment]
I think I can add a fix for this. Give me a while.

**Comment by joep26020** [comment]
> I read it closer. It seems that your modpack has added this enemy called `RollingGiant`, which is causing the issue.

but we like it so should i just remove the spawn command to get it working?

**Comment by joep26020** [comment]
> I think I can add a fix for this. Give me a while.

this would be a good idea though to be honest as an anticheat for lchax. we could keep it down low so if any of the trusted few want to play modded and dont want annoying hackers we can just do this

**Comment by winstxnhdw** [comment]
Done.

**Comment by winstxnhdw** [comment]
> this would be a good idea though to be honest as an anticheat for lchax. we could keep it down low so if any of the trusted few want to play modded and dont want annoying hackers we can just do this

Not sure what you mean.

**Comment by joep26020** [comment]
> Done.

thank you

**Comment by joep26020** [comment]
> > this would be a good idea though to be honest as an anticheat for lchax. we could keep it down low so if any of the trusted few want to play modded and dont want annoying hackers we can just do this
> 
> Not sure what you mean.

eh it doesnt matter

**Comment by joep26020** [comment]
> > this would be a good idea though to be honest as an anticheat for lchax. we could keep it down low so if any of the trusted few want to play modded and dont want annoying hackers we can just do this
> 
> Not sure what you mean.

its working now
