### ISSUE TITLE
[Bug]: Disabling "PosessionMod" also disables the ability to scan.

### ISSUE THREAD

**Issue by IntegrityPerson** [winstxnhdw/lc-hax#368]
### What happened?

![image](https://github.com/winstxnhdw/lc-hax/assets/157595981/b55466ad-2e2e-4a2d-b5c7-22f7da163423)
If I switch this to //Loader.AddHaxModules<PossessionMod>(); - it will disable the ability to scan.

### Current Commit Hash

9d015885c8d9d0cd692318a1f7bc95789b8d9fb5

### Injector

- [X] SharpMonoInjectorCore
- [X] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by IntegrityPerson** [comment]
Also is there a version of this mod where I can have **ONLY** the commands in chat?

**Comment by winstxnhdw** [comment]
I think this has something to do with @xAstroBoy’s disable player scan for possession mod.

**Comment by winstxnhdw** [comment]
> Also is there a version of this mod where I can have ONLY the commands in chat?

Just comment out all the mods and delete all the patches that are not dependencies + ChatPatch.cs.

**Comment by xAstroBoy** [comment]
> I think this has something to do with @xAstroBoy’s disable player scan for possession mod.

yeah because even ControlCompany does disable scan because there's no need for it if you control a enemy

**Comment by IntegrityPerson** [comment]
@winstxnhdw @xAstroBoy  What is the mod that disables the commands being viewed by others in chat because people can see commands such as /money after I disabled most of them.

**Comment by winstxnhdw** [comment]
There is no mod that does that. It's built-in and you can't disable it unless you disable commands.

**Comment by IntegrityPerson** [comment]
No, no, no. Basically I disabled a bunch of the mods by putting // in front of them. Now, when I type commands in chat, others are able to read them. Before, people couldn't see them. Which one do I need to reactivate?

**Comment by winstxnhdw** [comment]
I am saying that should never happen.

**Comment by IntegrityPerson** [comment]
Interesting...

**Comment by IntegrityPerson** [comment]
Then what does the "ChatMod" do?

**Comment by winstxnhdw** [comment]
Just allows you to reuse previous commands. You can remove it and all will still work fine.

**Comment by IntegrityPerson** [comment]
Hmm... I will try typing again

**Comment by winstxnhdw** [comment]
Recently, I even moved ChatPatch to `Dependencies` so you can delete anything patch that is not under `Dependencies` and everything will still work.

**Comment by IntegrityPerson** [comment]
Also, people aren't supposed to see your commands right?

**Comment by winstxnhdw** [comment]
Nope. If the name starts with "USER", it will never be seen.

**Comment by IntegrityPerson** [comment]
Ok maybe it was just that session then... That's strange

**Comment by winstxnhdw** [comment]
If they have a mod that listens to RPC commands, they can see that someone has called an RPC command, but they won't know who it is from AFAIK.

**Comment by IntegrityPerson** [comment]
My name starts with my ingame name... not USER

**Comment by winstxnhdw** [comment]
Then your command is not working.

**Comment by IntegrityPerson** [comment]
Damn

**Comment by IntegrityPerson** [comment]
Is it possible that my mods are making it go wrong?

**Comment by winstxnhdw** [comment]
Very possible.

**Comment by IntegrityPerson** [comment]
I will disable them and report back when I find the one.

**Comment by IntegrityPerson** [comment]
It is the "Boombox Controller" mod. I think because it also uses commands to play the custom tracks. All good now.

Thanks!!

**Comment by winstxnhdw** [comment]
I am forcefully overriding the command patch, maybe you can try the Boombox mod again.

**Comment by winstxnhdw** [comment]
Fixed in latest.
