### ISSUE TITLE
[Bug]: no respawn feature?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#374]
### What happened?

hey winston how do we respawn now and is that a host only feature? i noticed it disappeared from the readme

### Current Commit Hash

lola

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
It’s now combined with `heal`.

**Comment by joep26020** [comment]
> It’s now combined with `heal`.

how does that work? like do i use /heal 100 or do /heal when dead

**Comment by winstxnhdw** [comment]
Just do `/heal` when you are dead. Follow the instructions and you’ll be fine.

**Comment by joep26020** [comment]
> Just do `/heal` when you are dead. Follow the instructions and you’ll be fine.

uhm its not working anymore for some reason

**Comment by winstxnhdw** [comment]
My bad, I was playing around with it. Try again.

**Comment by joep26020** [comment]
also destroy all isnt working either

**Comment by winstxnhdw** [comment]
It’s working for me.

**Comment by joep26020** [comment]
> It’s working for me.

hmm im not sure then...

**Comment by joep26020** [comment]
nvm server issues

**Comment by joep26020** [comment]
kinda buggy tho

**Comment by winstxnhdw** [comment]
If you move your slots while destroying, it probably breaks some things.

**Comment by joep26020** [comment]
hmm ok.

**Comment by joep26020** [comment]
yeah tha seems to be it
