### ISSUE TITLE
[Bug]: /buy command

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#375]
### What happened?

when i use /buy jetpack 12 it crashes the game

### Current Commit Hash

3414ffe

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
does `suit pajama` crash the game too?

**Comment by joep26020** [comment]
> does `suit pajama` crash the game too?

Yes

**Comment by winstxnhdw** [comment]
Fixed.
