### ISSUE TITLE
[Bug]: Enemies are literally not being affected by gravity

### ISSUE THREAD

**Issue by xAstroBoy** [winstxnhdw/lc-hax#376]
### What happened?

They no longer can jump or be affected by the circumstant envroinment 

### Current Commit Hash

aaaa

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I don’t get this issue though.

**Comment by joep26020** [comment]
> ### What happened?
> They no longer can jump or be affected by the circumstant envroinment
> 
> ### Current Commit Hash
> aaaa
> 
> ### Injector
> * [ ]  SharpMonoInjectorCore
> * [ ]  Others
> 
> ### If you selected "Others" above, please specify the injector you are using.
> _No response_
> 
> ### Log output
> _No response_
> 
> ### Acknowledgement
> * [x]  I have confirmed that my anti-virus is not blocking any of the relevant programs
> * [x]  I have done my due diligence to check for similar issues

yeah i got that too, cant jump

**Comment by xAstroBoy** [comment]
a potential fix would be setting the enemy before possession as kinematic object, and then disable the kinematic once possessed.

**Comment by winstxnhdw** [comment]
Okay, fixed. I just messed up the conditional because `CharacterController` became nullable.

**Comment by winstxnhdw** [comment]
> a potential fix would be setting the enemy before possession as kinematic object, and then disable the kinematic once possessed.

LOL

**Comment by xAstroBoy** [comment]
> > a potential fix would be setting the enemy before possession as kinematic object, and then disable the kinematic once possessed.
> 
> LOL
that would temporarily disable the physic mechanism, just the time to possess it, then reactivate it, why LOL?

**Comment by winstxnhdw** [comment]
No, I just thought it was really like you to suggest something like this when the real solution was flipping `is false` to `is true`.

**Comment by xAstroBoy** [comment]
> No, I just thought it was really like you to suggest something like this when the real solution was flipping `is false` to `is true`.

that was the suggestion to avoid the bug that the enemy goes outside the map when possessed

**Comment by winstxnhdw** [comment]
Ah, I see. In that case, I still haven't got that issue yet.

**Comment by winstxnhdw** [comment]
Okay, I just got it with bees.
