### ISSUE TITLE
[Bug]: possession flings the enemies

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#377]
### What happened?

d

### Current Commit Hash

5555wc

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
the heck is with these bugs?

**Comment by winstxnhdw** [comment]
Seems fine to me.

https://github.com/winstxnhdw/lc-hax/assets/56998716/e7f5f6a4-6ddc-42c1-829c-3abd7370397b

**Comment by joep26020** [comment]
> the heck is with these bugs?

prolly a me issue for esp, but the enemies fling a lot for possession, and sometimes they are glitchy and always want to go back to original position, so on other people's screens it doesnt move and on ur screen its glitching

**Comment by winstxnhdw** [comment]
I thought the fling issue was due to the collider but the BepInEx colliders are saying otherwise.

![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/b9365160-0fde-40a0-b0ea-bf1eadaf317c)

**Comment by joep26020** [comment]
> I thought the fling issue was due to the collider but the BepInEx colliders are saying otherwise.
> 
> ![image](https://private-user-images.githubusercontent.com/56998716/303956457-b9365160-0fde-40a0-b0ea-bf1eadaf317c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTMzODMsIm5iZiI6MTcwNzcxMzA4MywicGF0aCI6Ii81Njk5ODcxNi8zMDM5NTY0NTctYjkzNjUxNjAtMGZkZS00MGEwLWIwZWEtYmYxZWFkYWYzMTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA0NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOTJiYmJlMWZmMDAyNmNiMTVjNTkyMTAyOTQ3ZWZjYmEzNDM4NzZjNjE0NmZlNjcyYzFkYzBkMTQ5MjY2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gPaV1qs5trDTh2AyaB-OU6HeZtsV45VXzVyZ5DdNDlo)

so its a game issue then? is there any way i could help, like giving you my log files?

**Comment by winstxnhdw** [comment]
There’s not much you can do. But if you’ve used ControlCompany before, has this ever happened there too?

**Comment by joep26020** [comment]
> There’s not much you can do. But if you’ve used ControlCompany before, has this ever happened there too?

no never used that mod

**Comment by xAstroBoy** [comment]
> There’s not much you can do. But if you’ve used ControlCompany before, has this ever happened there too?

Control company does not allow to control existing enemies, just controls the one that it spawns

**Comment by winstxnhdw** [comment]
I'll close this for now since we are going to merge @xAstroBoy PR which should fix this.
