### ISSUE TITLE
[Feature Request]: make it so you can activate earth leviathan please

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#379]
### What happened?

title

### Current Commit Hash

llllko

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
It’s either left or right-click. But you can already do that.

**Comment by Totoqoe** [comment]
It doesn't work when you're not the host. Something similar happens with lethal menu where using the Kill function of the worm only makes it growl when you're not the host.
