### ISSUE TITLE
[Bug]: respawn sometimes doesnt work at all

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#380]
### What happened?

adasdsarasg

### Current Commit Hash

t66

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
@joep26020 can you try again. I think I might have fixed it.

**Comment by winstxnhdw** [comment]
Closed due to inactivity.

**Comment by Totoqoe** [comment]
Sorry for bumping, but I have encountered the same issue that I believe is what OP experienced.  The screen only plays the heal effect.  This clip was taken on Feb 19.
https://cdn.discordapp.com/attachments/772945937009868851/1209744156583395398/Desktop_2024.02.19_-_23.48.49.02.Dvr.mp4?ex=65e8090a&is=65d5940a&hm=d152f99aa3eeeec2aadc521f77cf1ded80ef04b76f8167cfeb81f90522d75748&

**Comment by winstxnhdw** [comment]
I see the problem. Seems like instakill don't set your player health to 0 which is what we are using to check if the player has died.

**Comment by winstxnhdw** [comment]
Fixed in latest.
