### ISSUE TITLE
[Bug]: Forest Giant Possession

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#381]
### What happened?

It seems that possessing Forest Giants is bugged out right now, you can move around but the Forest Giant doesn't follow.

### Current Commit Hash

none

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Pretty sure I just fixed that in latest.

**Comment by winstxnhdw** [comment]
Closing this because I just tested and it was fine.
