### ISSUE TITLE
[Bug]: Nutcracker + Snareflea Possession / Movement

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#386]
### Nutcracker:
Is there a way to make it where the Nutcracker doesn't try to go in Sentry mode at all when possessed, the way is right now the AI sometimes still tries to go in Sentry mode it makes it look very buggy.
### Snareflea:
Snarefleas are currently bugged out right now for possession, you can go off this ceiling just fine but when you try to go back on the ceiling it completely breaks the Snareflea.

### Off topic:
also this is completely off topic but do you think we can Implement a system to adjust the enemies movement speed depending on which enemy is possessed like the abilities?

### Current Commit Hash

none

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think we can ping @xAstroBoy and ask him what he thinks about this.

**Comment by xAstroBoy** [comment]
@winstxnhdw using agent.speed would do the trick, as well you need to fix the collision system, why you dont use the enemy collider itself?

**Comment by winstxnhdw** [comment]
because anything to do with agents suck. you can't even reliably disable it: https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html

**Comment by xAstroBoy** [comment]
> because anything to do with agents suck. you can't even reliably disable it: https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html

Actually you can, controlcompany sets isStopped , that completely disables the NavMeshAgent but still leave it’s functionalities available

**Comment by xAstroBoy** [comment]
‘’’

		protected virtual void EnableAIControl(bool enabled)
		{
			this.CheckInitialized();
			this.isAIControlled = enabled;
			ControlCompanyPlugin.Instance.logger.LogMessage(string.Format("Enable AI control: {0}", enabled));
			bool flag = this.IsAIControlled;
			if (flag)
			{
				this.enemyAIAgent.angularSpeed = this.originalAgentAngularSpeed;
				this.enemyAIAgent.speed = this.originalAgentSpeed;
				this.enemyAIAgent.isStopped = false;
			}
			else
			{
				this.enemyAI.ChangeOwnershipOfEnemy(ControlCenter.Instance.GetHostPlayer().actualClientId);
				this.enemyAIAgent.angularSpeed = 0f;
				this.enemyAIAgent.speed = 0f;
				this.enemyAIAgent.isStopped = true;
				base.transform.SetParent(null);
			}
			this.canMove = !
			
‘’’

**Comment by winstxnhdw** [comment]
Yeah, I have tried that. It's not working for me for some reason.

**Comment by xAstroBoy** [comment]
> Yeah, I have tried that. It's not working for me for some reason.

Works well for me, try again?

**Comment by xAstroBoy** [comment]
> `CharacterController` will always have its own collider though?

Before parenting it, strip it from that charactercontroller?

**Comment by winstxnhdw** [comment]
Sure, I'll give it a try.

**Comment by xAstroBoy** [comment]
I did try without isStopped and i was able to sync the charactercontroller speed by exposing the speed variable and putting a line in update to use that variable in charactercontroller.Speed = agent.speed, also i am working on a spring controller as well

**Comment by xAstroBoy** [comment]
#392 @winstxnhdw @D1GQ i took my time and actually implemented a bunch of features for PossessionMod, have a look.

**Comment by D1GQ** [comment]
I'll definitely check it out when I can.

**Comment by xAstroBoy** [comment]
> I'll definitely check it out when I can.

just figured did not need the collider calculation, not disabling the enemy colliders might be enough, and just a big enough collider for the controller to not phase thru the various map structure would work.

**Comment by winstxnhdw** [comment]
Let me know how it goes. I won’t have time to try it out for a while.

**Comment by D1GQ** [comment]
> Let me know how it goes. I won’t have time to try it out for a while.

Seems pretty nice so far, do you think you can also make it where the Nutcracker has to reload after shooting two times?

**Comment by D1GQ** [comment]
But there seems to be a bug where you're not able to move when entering and leaving the factory, also would be nice if you have to use the trigger mod too leave an enter instead of it randomly just dragging you.

**Comment by xAstroBoy** [comment]
> But there seems to be a bug where you're not able to move when entering and leaving the factory, also would be nice if you have to use the trigger mod too leave an enter instead of it randomly just dragging you.

I fixed it a hour ago, try with the latest changes

**Comment by D1GQ** [comment]
> I fixed it a hour ago, try with the latest changes

I just downloaded it not even 30 minutes ago it was happening to me with the puffer

**Comment by xAstroBoy** [comment]
> > I fixed it a hour ago, try with the latest changes
> 
> I just downloaded it not even 30 minutes ago it was happening to me with the puffer

weird, i was 3h trying to fix it , i thought i did, try redownloading or ill try to fix it tomorrow

**Comment by D1GQ** [comment]
Controlling enemies seems to work fine until you run into another player, it seems that when the AI tries to take over, you pause randomly when you try to move.

**Comment by xAstroBoy** [comment]
> Controlling enemies seems to work fine until you run into another player, it seems that when the AI tries to take over, you pause randomly when you try to move.

That’s spring behaviour, im working on overriding the locks

**Comment by winstxnhdw** [comment]
Completed in latest.
