### ISSUE TITLE
Feature Request: InfiniteAmmo

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#39]
It seems that it can be implemented on the client side and there is already a MOD available, but I still hope that it can be added as a feature to LC-HAX.

**Comment by winstxnhdw** [comment]
Interesting. Can you send a reference link?

**Comment by winstxnhdw** [comment]
Looks easy. I'll add it by today.

**Comment by winstxnhdw** [comment]
I have added this.
