### ISSUE TITLE
[Bug]: Antikick/Connect

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#397]
### What happened?

There seems to be an issue right now where if you Auto reconnect because of AntiKick or connect to a Lobby through Steam ID, the game doesn't register you as a player joining, so for example if the lobby is full with you and three others, the lobby doesn't think it's full so another player can join then the lobby completely crashes because of a fifth player that tries to load it, which as you know the game is hard coded for four players. I don't know if there's a way to work around this.

### Current Commit Hash

none

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I think unless we find another breakthrough for anti-kick, let’s just mark all these issues as not solvable right now.

**Comment by Dr-Insanity** [comment]
> I think unless we find another breakthrough for anti-kick, let’s just mark all these issues as not solvable for now.

Hello. I was looking for an anti kick. Perhaps you can block the kick packet from the game. Use wireshark to study the network traffic, and make your application set a firewall rule to specifically block this.

That all, is, if that is how Lethal Company kicks clients.

**Comment by winstxnhdw** [comment]
Hey, that wouldn’t work because kicking is not client side. Your device doesn’t have to ‘approve’ to be kicked. The host can kick you whether or not your client agrees.

**Comment by Dr-Insanity** [comment]
I see. I was aware of this, but wasn't sure this would fully apply to P2P. Best of luck finding a breakthrough. I have too little knowledge of the game & the stack you program with. Also, this is a great project.
