### ISSUE TITLE
[Bug]: Crosshair Mod

### ISSUE THREAD

**Issue by D1GQ** [winstxnhdw/lc-hax#398]
### What happened?

I don't know if this is exclusively for me but I've noticed once the Crosshair gets rendered in game and you exit to the menu you still have it, the current method used does have a condition to render but if the condition isn't met it just returns it doesn't unrender the Crosshair, here's a simple fix I did.

### Crosshair Mod:
**Code:**
```
void OnGUI() {
    if (this.InGame)
    this.RenderCrosshair();
    else
        this.UnRenderCrosshair();

}

    void UnRenderCrosshair() {
}
```

### Current Commit Hash

none

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
There’s no need to unrender the crosshair because not rendering it is the same as unrendering it.

**Comment by D1GQ** [comment]
> There’s no need to unrender the crosshair because not rendering it is the same as unrendering it.

I guess the issue is exclusive to me then, because with the original code the Crosshair would just stay.

**Comment by winstxnhdw** [comment]
Yeah, it’s more likely that your `InGame` flag is not becoming false.

**Comment by D1GQ** [comment]
It's probably because of some type of modification I did, I do a lot of modifications of the code to suit me, it's just this wasn't happening until I updated I had to transfer all of my modifications, so I thought it was just a bug. Sorry.
