### ISSUE TITLE
[Bug]: Revive monster function not working? Or maybe it's delay is too late. Also, wondering if you can implement a way to detect other people using this mod so I can not join lobbies where other hackers are. Also opening and closing doors is only client sided when in phantom mode. 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#40]
### What happened?

...

### Current Commit Hash

aaa

### Injector

- [x] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I'd appreciate if you keep your titles more concise and elaborate more in the description.

> Revive monster function not working?

What do you mean by not working.

> if you can implement a way to detect other people using this mod so I can not join lobbies where other hackers are

This requires literally installing a backdoor in the program, which we will **never** implement for the safety of the users.

> Also opening and closing doors is only client sided when in phantom mode

I'll see what I can do.

**Comment by winstxnhdw** [comment]
> opening and closing doors is only client sided when in phantom mode

I don't think we will be moving forward to fix this. Can't seem to find the root cause of it and anything to do with InteractTriggers in this game is too complex until we get a better understanding. If anyone would like to give this attempt, it'd be greatly appreciated.

**Comment by joep26020** [comment]
> I'd appreciate if you keep your titles more concise and elaborate more in the description.
> 
> > Revive monster function not working?
> 
> What do you mean by not working.
> 
> > if you can implement a way to detect other people using this mod so I can not join lobbies where other hackers are
> 
> This requires literally installing a backdoor in the program, which we will **never** implement for the safety of the users.
> 
> > Also opening and closing doors is only client sided when in phantom mode
> 
> I'll see what I can do.

I don't know how to further elaborate. I'm saying the funny revive function for monsters does not revive them. I look at them and click r + m3, no result.

**Comment by joep26020** [comment]
> > opening and closing doors is only client sided when in phantom mode
> 
> I don't think we will be moving forward to fix this. Can't seem to find the root cause of it and anything to do with InteractTriggers in this game is too complex until we get a better understanding. If anyone would like to give this attempt, it'd be greatly appreciated.

K, thank you!

**Comment by winstxnhdw** [comment]
Well, the issue here is that you are doing it wrong. You are supposed to look at a player and do the bind. Not look at the enemy.

**Comment by joep26020** [comment]
> Well, the issue here is that you are doing it wrong. You are supposed to look at a player and do the bind. Not look at the enemy. Funny revive will revive all lureable enemies.

So what will happen when I look at the player? Will the monsters spawn on them again?
