### ISSUE TITLE
[Feature Request]: Allow voice chat at camera's position while in `Phantom`

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#41]
### What happened?

adadwaasdadw.

### Current Commit Hash

adwa

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
> maybe even toggle location on current location in phantom mode to troll people?

I have no clue what you mean by this. I'd also appreciate if you keep your titles more concise and elaborate more in the description.

**Comment by joep26020** [comment]
> > maybe even toggle location on current location in phantom mode to troll people?
> 
> I have no clue what you mean by this. I'd also appreciate if you keep your titles more concise and elaborate more in the description.

I'm talking about people hearing your voice wherever you are in phantom mode. Like pretend you turned you character invisible and could fly. Kind of like that.

**Comment by winstxnhdw** [comment]
I can look into this.

**Comment by winstxnhdw** [comment]
Do you have a reference implementation?

**Comment by winstxnhdw** [comment]
I think I've tried the first one before but it never worked. I'll look into it again.

**Comment by winstxnhdw** [comment]
I've tried both versions but no luck :/

**Comment by joep26020** [comment]
> I've tried both versions but no luck :/

Did you add it to the mod?

**Comment by winstxnhdw** [comment]
I really want to get this feature in but I don't have anyone to test it with.

**Comment by joep26020** [comment]
> I really want to get this feature in but I don't have anyone to test it with.

ill test with u

**Comment by joep26020** [comment]
> I really want to get this feature in but I don't have anyone to test it with.

i could be ur test dummy lol

**Comment by AverageVirusTotalEnjoyer** [comment]
was this tested @winstxnhdw

**Comment by winstxnhdw** [comment]
Not yet, don't think I can test this until I've fully recovered and can focus 100% on this.

**Comment by AverageVirusTotalEnjoyer** [comment]
Ok

**Comment by joep26020** [comment]
> Not yet, don't think I can test this until I've fully recovered and can focus 100% on this.

couldn't you just add a fly and noclip mod and be invisible with this?

**Comment by joep26020** [comment]
> > Not yet, don't think I can test this until I've fully recovered and can focus 100% on this.
> 
> couldn't you just add a fly and noclip mod and be invisible with this?

or infinite jump maybe

**Comment by Totoqoe** [comment]
I wonder if this could be possible, I know of one instance where the voice detaches itself from the player body and that's when a player gets stuck in the void, once they load in as nameless, the ESP shows their body as if they're several meters away, yet their voice still seems to come closely from the left wall of the ship. Not sure if this can be replicated outside of that one niche scenario.

**Comment by winstxnhdw** [comment]
It's definitely possible. But it's probably super painful and annoying to do. Even `hear` sucks.

**Comment by winstxnhdw** [comment]
Nevermind. It's host-only.
