### ISSUE TITLE
Some bugs in the latest version

### ISSUE THREAD

**Issue by tslpy1** [winstxnhdw/lc-hax#42]
1. Instant Interact mod cannot access the secondary entrance and cannot close the door.
2.collision errors still occur when using trigger mode on players, and the same goes for /mob, which also results in collision errors.

I think there might be a bug occurring when certain types of enemies are being teleported. 
Based on my testing, it seems that only the "Centipede" and "Masked" enemies work properly when being teleported. 
Other enemies seem to be unable to be teleported. The "SpringMan" model can be teleported, but it seems that other players cannot see it, although sometimes I get killed when getting close to the model myself. 
Additionally, the enemies that cannot be teleported also disappear from the client-side, similar to the effect of "kill localenemy". 
I cannot see them, but other players can still see the enemies.

It might be worth trying to add a functionality to the enemy teleportation feature that checks the enemy type. 
This way, only certain types of enemies can be teleported, which may help in troubleshooting and identifying if the error is caused by specific enemy types.

regardless, thank you for your diligent development work.

**Comment by winstxnhdw** [comment]
Try pulling latest.
