### ISSUE TITLE
[Bug]: The hurt red vision stays after you die permanetly.

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#44]
### What happened?

Pretty much, if you were to be killed before in a round, you will keep the red hurt ui forever no matter if you use /heal. You would need to restart the game to remove the effect.

### Current Commit Hash

883279ccc73e8feb58807f105784b3b798372808

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Thanks for the report. This has been fixed in latest.
