### ISSUE TITLE
[Bug]: how to use the translate? 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#469]
### What happened?

do i do /translate english spanish hello to get hola or do i do /translate spanish english hello to get hola?

### Current Commit Hash

78

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
from, to

**Comment by joep26020** [comment]
> from, to

wait winston can u make it so u can see ur translate commands

**Comment by winstxnhdw** [comment]
wdym?

**Comment by joep26020** [comment]
> > from, to
> 
> wait winston can u make it so u can see ur translate commands

i cant see it when i do the translate command like the output

**Comment by winstxnhdw** [comment]
by default, there should be output. could be broken.

**Comment by joep26020** [comment]
> by default, there should be output. could be broken.

it does too when i do like /fall command twice. it only shows first input and no other commands after that

**Comment by winstxnhdw** [comment]
weird. are you using translate on detached mode?

**Comment by joep26020** [comment]
> weird. are you using translate on detached mode?

it does it on both modes

**Comment by winstxnhdw** [comment]
is this closed because it’s fixed or what?
