### ISSUE TITLE
[Bug]: can you make it so you can spin certain items

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#470]
### What happened?

d

### Current Commit Hash

6yy6yt8

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Probably won’t add this.
