### ISSUE TITLE
can you remove respawn

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#478]
### What happened?

[Bug]: can you turn off the respawn feature its very useless i can do everything with it in phantom mode and sometimes when i want to only remove the red effect i cant because ill respawn and it doesnt even respawn u it just puts ur character in 

### Current Commit Hash

778787

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
i mean you can just kill yourself with `/kill`

**Comment by joep26020** [comment]
> i mean you can just kill yourself with `/kill`

ok

**Comment by joep26020** [comment]
/bomb 7

> > i mean you can just kill yourself with `/kill`
> 
> ok

that doesnt work tho

**Comment by joep26020** [comment]
> What?

sorry for the bomb thing that was a mistake but im saying do /kill on yourself doesnt kill you again
