### ISSUE TITLE
[Bug]: how do i turn off the grainy effect

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#479]
### What happened?

fafaf

### Current Commit Hash

u8775

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
what

**Comment by joep26020** [comment]
> what? u mean film grain?

yes like when using the brightness feature with f4 and f5

**Comment by winstxnhdw** [comment]
Unless it affects performance. It’s probably not going to be job of this project.
