### ISSUE TITLE
[Bug]: God Mode and Start ship.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#49]
### What happened?

God mode doesn't allow you to use/pick up items. And start ship causes the host to not be able to click anything or even press the menu button.

### Current Commit Hash

a2b45

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I am unable to replicate your issue. 

I can pick and use items in God mode and I can also interact after using `/start`.

**Comment by joep26020** [comment]
> I am unable to replicate your issue.
> 
> I can pick and use items in God mode and I can also interact after using `/start`.

Oh I figured it out, it's when I click a player with m3 to hate them. It doesn't let me use items or anything. And whenever I use start on another host, not me, they can't do anything.

**Comment by winstxnhdw** [comment]
I still can't replicate your issue. I can still interact with items after using `M3`. The host that I use `/start` on can still interact and play as normal.

**Comment by joep26020** [comment]
> I still can't replicate your issue. I can still interact with items after using `M3`. The host that I use `/start` on can still interact and play as normal.

Maybe the host I was playing with had a mod that interfered with the start command. Seems like a me issue. But when I fall through the floor I can't pick up or use items after using m3.

**Comment by winstxnhdw** [comment]
Yeah, that's a really old bug that has been fixed for a while now.

**Comment by joep26020** [comment]
> Yeah, that's a really old bug that has been fixed for a while now.

Ok sorry...

**Comment by winstxnhdw** [comment]
Not your fault. I should've realised when I saw your current commit hash.
