### ISSUE TITLE
[Bug]: Error When running requirements.bat

### ISSUE THREAD

**Issue by maupwastaken** [winstxnhdw/lc-hax#490]
### What happened?

When running requirements.bat I get this error:
`Building SharpMonoInjectorCore! Please be patient as this may take a few minutes!
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
System.CommandLine. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
System.Management. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
Microsoft.NET.ILLink.Tasks. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
Microsoft.NETCore.App.Runtime.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Pac
kages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
Microsoft.WindowsDesktop.App.Runtime.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offl
ine Packages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
Microsoft.AspNetCore.App.Runtime.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline
Packages
C:\Users\jan-s\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj : error NU1101: Unable to find package
Microsoft.NETCore.App.Crossgen2.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline P
ackages
  Failed to restore C:\Users\MYUSER\lc-hax\submodules\SharpMonoInjectorCore\SharpMonoInjector.csproj (in 109 ms).
Press any key to continue . . .`

I believe I followed the Instruction video, and I don't know how to fix this issue.

### Current Commit Hash

5ada0586ba99097e081a267ae43a94175cc46c42

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
See #123.
