### ISSUE TITLE
[Bug]: Player "revives" when using chat after death

### ISSUE THREAD

**Issue by yjkyjjk** [winstxnhdw/lc-hax#497]
### What happened?

sometimes when you use chat you "revive" and then it reports you as missing. You also can't move your camera or spectate anymore. And also, you helped me get a new pc. tysm

### Current Commit Hash

fd55731216c382bbc18e7a44888d509757d2863c

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
What? How’s that even possible?

**Comment by yjkyjjk** [comment]
i dont know. But sometimes when i try to type /mask i get "revived" and then i get stuck in a spot. i can still scan but the players cant see me

**Comment by winstxnhdw** [comment]
Cool. An unintended feature.

**Comment by yjkyjjk** [comment]
And also the spectate and broken visor hud is still on my screen after my friend start the ship

**Comment by winstxnhdw** [comment]
Are you on v49

**Comment by Totoqoe** [comment]
I've had this happen a few times too, it's so odd and random but it might be a mod conflict.
