### ISSUE TITLE
Doesn't exist.

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#5]
![image](https://github.com/winstxnhdw/lc-hax/assets/79861302/b9f4d984-004c-4884-8ce1-0b8df5acaf9f)

**Comment by TheLGAOriginal** [comment]
What was the solution here? im having the same problem

**Comment by winstxnhdw** [comment]
You probably didn’t install .NET 8.0 SDK as stated in the README.

**Comment by MythicalTrashcan** [comment]
This is old. You gotta git clone with --recursive. I forgot to so SharpMonoInjectorCore just didn't exist.

**Comment by TheLGAOriginal** [comment]
Even using the --recursive i still keep getting the Sharpmonoinjector error, already have the .net 8.0 sdk installed

**Comment by winstxnhdw** [comment]
Send a screenshot of your terminal.
