### ISSUE TITLE
[Bug]: Lure enemy breaks Old Bird/Radmech

### ISSUE THREAD

**Issue by cmmaio** [winstxnhdw/lc-hax#502]
### What happened?

Lure enemy to player via triggermod or /hate doesn't work on oldbirds (radmech) and instead of luring it freezes them and makes them walk in place breaking them. 

### Current Commit Hash

dd6aab5f8e2c889352690897b535332f706b0641

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
well, yeah. what’d you expect when you build for v49 but use it for v50?

**Comment by winstxnhdw** [comment]
It’s still in beta. Chill bro.

**Comment by xAstroBoy** [comment]
> It’s still in beta. Chill bro.

not anymore
