### ISSUE TITLE
[Bug]: Installation error.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#51]
### What happened?

Got this error when trying to reclone to get new features:

fatal: could not create work tree dir 'lc-hax': Permission denied

### Current Commit Hash

asdw2232

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
That's because the folder still exists. You have to delete the existing one first.

**Comment by joep26020** [comment]
> That's because the folder still exists. You have to delete the existing one first.

I deleted it. The problem was git bash. I did it on there and it didn't work but on cmd it worked.

**Comment by winstxnhdw** [comment]
No, the problem is that git bash starts on the %USERPROFILE% path which you mistaken as the correct path but I am glad you got it solved.
