### ISSUE TITLE
[Bug]: Can't type in chat anymore.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#52]
### What happened?

So I recently installed the mod and now I ran it, and I can't type in chat at all even after restarting my pc.

### Current Commit Hash

6436532523

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Try pressing `esc` first?

**Comment by joep26020** [comment]
No, still doesn't work

**Comment by joep26020** [comment]
I'm reinstalling all my mods. Maybe it's them because I reinstalled the game.

**Comment by joep26020** [comment]
Ok fixed it, was a mod issue.
