### ISSUE TITLE
[Bug]: Possess monsters disappearing.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#53]
### What happened?

When I die in possess mode, all the other monsters disappear. 

### Current Commit Hash

5353534

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by joep26020** [comment]
> What do you mean by die when you are possessed? Do you mean that when your real body gets killed while you are possessed, all the monsters disappear?
> 
> That’s extremely bizzare.

Sorry I didn't clarify. It's when I am controlling the monster and IT dies. Again, sorry for the confusion. And when the bracken disappears, that happens too.

**Comment by MythicalTrashcan** [comment]
Yeah, Bracken is the only one for me that will just randomly become invisible. You can still find it by scanning. It usually becomes visible after about 20 seconds.

**Comment by winstxnhdw** [comment]
That’s just the AI taking back control and teleporting away. It happens. Nothing much we can do about it.

**Comment by joep26020** [comment]
> That’s just the AI taking back control and teleporting away. It happens. Nothing much we can do about it.

It happens when I am controlling thumper and it dies. Every monster disappears.  :/
