### ISSUE TITLE
[Bug]: /buy command not working on cruiser

### ISSUE THREAD

**Issue by Exventer** [winstxnhdw/lc-hax#532]
### What happened?

when you try to buy cruiser vehicle with /buy command it buys random weapons instead of vehicle

### Current Commit Hash

idkwhatthisis

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I took a look. Seems like vehicles are in a separate group from purchasable items, similar to clothing unlockables. Further investigation tells me that it may also be host only :/

**Comment by Exventer** [comment]
i hope its not host only

**Comment by Totoqoe** [comment]
I could've sworn I tried this command with a friend group and it worked while I wasn't host, albeit it was on Astros branch instead of the main one.

**Comment by winstxnhdw** [comment]
Cool, I completely forgot how the buy mechanics work. I'll add this.

**Comment by winstxnhdw** [comment]
Okay, I've added it in latest. Feel free to try it out.

**Comment by winstxnhdw** [comment]
I'll close this for now.
