### ISSUE TITLE
[Bug]: possession not working

### ISSUE THREAD

**Issue by Lipti-pl** [winstxnhdw/lc-hax#533]
### What happened?

as much as i try to use possession module on the latest patch i cant seem to get it to work
im afraid its a bug although i couldnt get it to work to begin with and there are no tutorials other than the keybinds listed and i tried those so i have to assume that its broken 
are there any fixes planned for it?

### Current Commit Hash

e

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
It's not broken. Please read the guides carefully. If not, read the countless other discussions or issues.
