### ISSUE TITLE
[Bug]: when you use /hate {player name} nutcrackers fire at random trying to shoot the player targetted and sometimes teleports to the player spiders also leave their webs right under the player while being nowhere near

### ISSUE THREAD

**Issue by Lipti-pl** [winstxnhdw/lc-hax#534]
### What happened?

ive been testing this command quite a lot and every now and then i need to re type it because mobs lose agro 
every time i do and theres a nutcracker/bunker spider somewhere on the map they cause some bullshit to happen

i think  a nice addition to the command list is to make a command that makes enemies constantly agro onto a player also plz fix the spider man webs 

### Current Commit Hash

e

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
You don't have to re-type. Just uparrow and it will cycle to your previous commands. I won't be making any changes to `hate`.
