### ISSUE TITLE
[Bug]: All Commands Output "Default Title : Default Body" and Provide No Effect

### ISSUE THREAD

**Issue by Bazingawastaken** [winstxnhdw/lc-hax#538]
### What happened?

Excluding the Godmode command. Every attempt to execute a command results in a small text box consisting only of the words "Default Title : Default Body" and does not do anything. This is occurring while only MoreCompany is active. Even while I am hosting a lobby, only Godmode can be used, and only before someone joins the lobby. This has happened every launch over the course of weeks, as well as after reinstalling. While on a vanilla game, they work just fine, so I also may be unaware of lost compatibility with MoreCompany. Confused as to if it is a user error or game error, and if there is a simple fix I am unaware of. Non command abilities (reach, instant interact, possession, etc.) work just fine
![image_2024-08-20_013503964](https://github.com/user-attachments/assets/f62cf728-63f1-47e8-b001-15f2ae5f21ac)

Also, I have no experience with Git or other functions, and I used the opinionated guide to run the program. I apologize as I do not understand how to find the current commit hash, as all attempts result in a fatal error.

### Current Commit Hash

Unknown?

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Seems like the game has updated. I’ll push a patch tonight.

**Comment by winstxnhdw** [comment]
I've updated `lc-hax` to support v61. Let me know if you are still getting this issue.

**Comment by Bazingawastaken** [comment]
It is working now, thank you!

 Also, they released v62 shortly after you fixed it for v61, so that could also be a problem later on.

**Comment by winstxnhdw** [comment]
Yeah, I patched for that as well.
