### ISSUE TITLE
[Bug]: /hate breaks radmechs (old birds)

### ISSUE THREAD

**Issue by Lipti-pl** [winstxnhdw/lc-hax#539]
### What happened?

whenever you type in /hate on anyone radmechs start standing still in one place unable to do anything 

### Current Commit Hash

eee

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
False alarm?

**Comment by xAstroBoy** [comment]
Not false alarm, in my fork i locked the radmech behind host for this reason.

**Comment by winstxnhdw** [comment]
Strange. I’ll patch it.
