### ISSUE TITLE
[Bug]: can not move when im controlling a entity

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#59]
### What happened?

i wnet to possess one and i just stand still even doe im mashing the W key

### Current Commit Hash

command doesnt work in terminal

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by AverageVirusTotalEnjoyer** [comment]
https://github.com/winstxnhdw/lc-hax/assets/118130921/ec7e7b6a-d8d1-46e8-a46f-c5271f6d9211

**Comment by winstxnhdw** [comment]
You have to be in `Phantom` first.

**Comment by AverageVirusTotalEnjoyer** [comment]
i was in phantom, ill show a longer clip

**Comment by AverageVirusTotalEnjoyer** [comment]
bug fixed itself by restarting the game
