### ISSUE TITLE
[Bug]: Change POV of possession.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#61]
### What happened?

Please take a look at the spectate enemies mod. If you could replicate those point of views, especially on the dog and giant, that would be awesome!

### Current Commit Hash

adwsdw as

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Duplicate of #46
