### ISSUE TITLE
[Bug]: When Getting hurt in godmode red death hue doesn't disappear.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#63]
### What happened?

dsdwasda

### Current Commit Hash

adqwasd

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Log output

d

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
I don't think you can get hurt in God mode.. Also, just do `/heal`.

**Comment by joep26020** [comment]
> I don't think you can get hurt in God mode.. Also, just do `/heal`.

Still doesn't fix it.

**Comment by winstxnhdw** [comment]
Please be on the latest commit.
