### ISSUE TITLE
New buglist

### ISSUE THREAD

**Issue by Quesoteric** [winstxnhdw/lc-hax#66]
Just pretend that I did the file-out bug thingy. Bugs will be marked with their test date and commit hash. Format 1234567 DD/MM/YYYY XX:XX
Will convert to your timezone. Also will ALWAYS use your fork of sharpmonoinjector.

Note 29/12/2023: I used to test this mod with BiggerLobby so that I had a surplus of people to test on without the host accurately assuming it was me. Except, most hosts have several mods that likely break features. So, I'm just going to test with the vanilla game on my friend. Bug reports might be slower now, but now are more likely to be valid.

Note 4/1/2023: Oops... just realized I forgot to convert the date too like 90% of the time when converting to your timezone as well lol, some dates might be wrong but the time is accurate

(?) = needs more testing

~~Stamina-mod and possibly others do not work properly if lc-hax is injected during the "Pick Online or LAN" sequence. `24880d4` `25/12/2023 02:09`~~ (Fixed)

~~Dropping items will temporarily speed the player up. If this is just one of the optimization features such as where stamina regens per second, I'll remove this. `24880d4` `25/12/2023 02:13` This can best be observed with a cash register~~ (Not worth fixing)

~~Nutcrackers killed with the command drop an ungrabbable shotgun that teleports to their spawn vent when they don't have their eye out (scanning or attacking)  `24880d4` `25/12/2023 02:16`~~ (Fixed, but still teleports it. I guess you could just use infinite grab though.)

~~Godmode will still disable friendly fire. `24880d4` `25/12/2023 02:16`~~ (Fixed, use demigod.)

~~You can pick up the terminal while typing on the terminal. `24880d4` `25/12/2023 02:22`~~ (Fixed)

~~Unpopped jesters will be able to maul people if you use the hate command. Looks funny though. `24880d4` `25/12/2023 02:45`~~ (Unfixable)

~~Controlled enemies have trouble going up uneven surfaces `24880d4` `25/12/2023 03:00`
(Not really a bug, per-se. Just feels kinda weird to control.)~~ (Limitation)

~~Controlled enemies sometimes becoming invisible. Best observed with eyeless dogs `24880d4` `25/12/2023 03:18` (Can't test this atm. Possession seems to randomly break. I'll look into this.)~~ (I am extremely re-re. Simply just an optimization feature where monsters go invisible when the ship doors are closed... and that's why I thought it was an issue with eyeless dogs. FML)

~~Sometimes controlled enemies don't move for other clients `0a08ac3` `25/12/2023 04:17`~~ (Limitation)

~~Dead centipedes will still wrap around the player via /hate or /mob, however it does no damage, muffles their voice, and makes them drop their items. The 'centipede' model itself will not be visible. `379607c` `27/12/2023 04:22`~~ (It's funny)

~~NameInWeightMod seems to not be working after a recent update. `f0f2452` `29/12/2023 11:53` (Nope, wasn't invalid.)~~ (Fixed)

~~No insanity seems to not prevent the ghost girl spawning .`f0f2452` `29/12/2023 12:11` This time it's (probably) not invalid. Some other things might be broken too.~~ (Misinformed)

~~Can't use ladders with infinite range if there are obstacles (such as map geometry) `f0f2452` `29/12/2023 12:51`~~ (No plan to fix)

~~Phantom mode offsets the first-person helmet model. Really obscure and minor bug so I don't really mind if this is a bottom-of-the-barrel bug that has low priority. `af53e48` `1/1/2024 07:02`~~ (Mod deletes it anyway.... rofl)

~~Don't know if this is invalid or not, but ~~the hate and mob commands~~ the commands in `Debug` and the `Hate` folders are not working for me after a recent update. High probability of being invalid. `af53e48` `1/1/2024 07:44`~~ (Fixed)

~~Following yourself (yes it sounds dumb, I know but it's possible) will cause your character to rubber band/flicker around `71f10ee` `2/1/2024 14:50`~~ (Fixed)

~~`E+M3` will not toggle the lights, it will play the animation though `71f10ee` `2/1/2024 16:20`~~ (Fixed)

~~Masked enemies when spawned outside via `/mask` will ignore everybody, and instead just walk straight towards the entrance, where they will then exit and then finally aggro people. That is if there are valid targets. `d0b5852` `6/1/2024 12:58`~~ (Strange and mysterious "bug." Attempts to recreate lead to immediate death of user)

~~Can't pull the horn with this mod without `/horn` `a44ba5d` `1/8/2024/ 13:29`~~ (INVALID)

~~Infinite gifts don't spawn after the recent update to the game. `10c999d` `1/10/2024 08:50`~~

~~`/enter` `/exit` `/home` all have one shared bug. It's hard to explain without a demonstration so let me explain. But to put it simply, it doesn't update your "inside" or "outside" state.~~ (Fixed)

~~Gifts will be un-droppable after multiple usage either ranging from ~2-3~ absolutely erratic amount of uses before breaking, only way to remove is via the cupboard. `d5ab9d6` `4/1/2024 10:11` (Sometimes this doesn't break for me. Needs more research)~~

After the recent update to `M3 + E` using it basically anywhere at the Company building will result in death. This is because pressing `E` on the water normally will kill you. `d5ab9d6` `4/1/2024 10:37`

~~Sometimes you just flat out die when pressing `SHIFT + =` in phantom mode. Usually occurs over long distances. `d0b5852` `6/1/2024 13:08`~~ (Fixed?)

~~When nutcrackers are prompted, their eye comes out but they don't attack, really funny to scare people though. `6607092` `1/7/2024 08:06`~~

~~The nutcracker's gun will damage you if you're close to it in phantom mode `6607092` `1/7/2024 8:07`~~ (Confliction

Sometimes when you possess an enemy they go flying `cfd8ae9` `1/7/2024 15:44`

~~Clear command prevents all and any messages from being shown, even after the command is executed. Also have to double-tap enter to send something. `a44ba5d` '1/8/2024 05:03`~~ (Fixed)

~~[Issues with the nutcracker and phantom mode](https://github.com/winstxnhdw/lc-hax/issues/66#issuecomment-1879980201) `10c999d` `1/10/2024 08:55`~~

~~[Inverse teleporter doesn't preserve items](https://github.com/winstxnhdw/lc-hax/issues/66#issuecomment-1883266937) `10c999d` `1/10/2024 08:56`~~ (Fixed)

~~Turrets target your camera, too. However this is not like the Nutcracker where it can damage you when you're close to it in phantom mode. Masked will also look at your phantom camera. `332800f` `13:25 11/1/2024`~~

~~Placing something outside with `/build` `/ct` `/pumpkin` in what is a normally invalid position, and you can't place it back. It's stuck forever. `332800f` `13:42 11/1/2024`~~ (Unfixable)

~~Weird bug with godmode and fall damage. Falling from a lethal height in godmode, and then turning off godmode, you will take some fall damage no matter how small the gap is. To put it simply godmode caches falldamage in a way. `332800f` `13:48 11/1/2024`~~ (Fixed?)

~~Probably not related to the issue above, but phantom'ing midair and the game will think you're still falling and building up fall damage. `332800f` `13:48 11/1/2024`~~ (Fixed?)

~~Infinite deposit in practice does not work. `332800f` `14:29 11/1/2024`~~ (Fixed.)

~~Sell command doesn't sell masks. `e3c7f32` `12:58 1/20/2024`~~ (Intentional as it breaks the sell command)

7/2/24: Haven't updated this in some time, and with the new surplus of updates I'll check them out and report back sometime soon

**Comment by winstxnhdw** [comment]
Your findings are always much appreciated.

> Dropping items will temporarily speed the player up.

 Do you actually mean slow down? I don't think I have done anything to speed up a player if they dropped an object.

> You can pick up the terminal while typing on the terminal.

Fixed in latest.

> Unpopped jesters will be able to maul people if you use the hate command. Looks funny though.

May never be fixable, thus intended.

> Controlled enemies have trouble going up uneven surfaces

Limitation of controlling NavMesh directly. You can hold `Space` to increase height.

> Controlled enemies sometimes becoming invisible. Best observed with eyeless dogs

Is this during control or no?

> Sometimes controlled enemies don't move for other clients

Only valid positions are broadcasted to the server. If you are in an invalid position locally, your current position will not be broadcasted.

**Comment by winstxnhdw** [comment]
> Controlled enemies have trouble going up uneven surfaces
> Controlled enemies sometimes becoming invisible. Best observed with eyeless dogs
> Sometimes controlled enemies don't move for other clients

These might all be fixed now with the new controller.

**Comment by winstxnhdw** [comment]
> Godmode will still disable friendly fire.

Indirect fix with the new `/demigod` command.

**Comment by winstxnhdw** [comment]
> Nutcrackers killed by the /kill command (not local) will have their DBS teleport to the vent where they spawned, and you can't pick it up.

Fixed.

**Comment by winstxnhdw** [comment]
No, the mod does something even more naive. It simply sets the Player's current weight to 1.0 lbs, which is the default weight of a player. See [here](https://github.com/winstxnhdw/lc-hax/blob/main/lc-hax/Scripts/Modules/WeightMod.cs#L15).

**Comment by winstxnhdw** [comment]
Interesting. This seems to be a bug with the game then. Of course, this could probably be solved by aggressively setting the player's weight every frame, but I guess it's not really worth the cost.

**Comment by MythicalTrashcan** [comment]
> Do you actually mean slow down? I don't think I have done anything to speed up a player if they dropped an object.

When you hold a very heavy object such as a cache register, it will speed you up to make you the same speed as if you weren't holding it. Once you drop it, there is a breif moment where you will move quickily until it is set back to normal.

**Comment by winstxnhdw** [comment]
> Do you mind if a create another section in this issue for the upcoming v47 update?

Go ahead.

**Comment by winstxnhdw** [comment]
> Nutcrackers killed by the /kill command (not local) will have their DBS teleport to the vent where they spawned, and you can't pick it up.

Nevermind. Still broken.

**Comment by winstxnhdw** [comment]
> Dead centipedes will still wrap around the player via /hate or /mob, however it does no damage, muffles their voice, and makes them drop their items. The 'centipede' model itself will not be visible. 

I am leaving this in because it's funny.

**Comment by winstxnhdw** [comment]
> No insanity seems to not work either

I can't replicate this.

> NameInWeightMod seems to not be working after a recent update.

This has been fixed,

**Comment by winstxnhdw** [comment]
> Also quick question, was the method to detonate mines with triggermod ever changed? Because I remember that I used to be able to activate landmines through walls, but now I can't activate the mines without clear line of sight. and even then it's a bit finnicky to explode.
> 
> Note: I can still interact with everything else, like locked doors through walls with triggermod.

I tried making an optimisation for it but it seems to be causing problems in large lobbies. I guess I'll revert it.

**Comment by winstxnhdw** [comment]
Wait, I just took a look and I didn't change the part that has to do with triggering landmines. It should still be the same as always.

**Comment by winstxnhdw** [comment]
> Stamina-mod and possibly others do not work properly if lc-hax is injected during the "Pick Online or LAN" sequence.

Do you happen to know what are the other mods affected by this? I have just pushed a fix for `Stamina` mod.

**Comment by winstxnhdw** [comment]
> Actually now with testing, found out that the weightmod also breaks if injected in the online/lan sequence.

Alright, I've fixed all of this.

> Also seeing the ghost girl too, but I don't know if this is just because of the previous statement I had about the insanity mod.

If you mean the heavy breathing, I believe that is part of the Ghost Girl reaction, nothing to do with sanity.

**Comment by winstxnhdw** [comment]
> Don't know if this is invalid or not, but the hate and mob commands the commands in Debug and the Hate folders are not working for me after a recent update.

Yeah, I forgot to add the command attributes for them. I've pushed a fix.

**Comment by winstxnhdw** [comment]
> No insanity seems to not prevent the ghost girl spawning

Ghost Girl cannot be stopped from spawning. She doesn't only choose her targets based on sanity level but also the amount of turns you've made, your current HP, and the value of the scrap you are carrying.

If you wish to not be targeted by Ghost Girl, you can do `/block enemy`.

**Comment by winstxnhdw** [comment]
> Phantom mode offsets the first-person helmet model. Really obscure and minor bug so I don't really mind if this is a bottom-of-the-barrel bug that has low priority

That's the helmet's visor. We delete it once the match starts.

**Comment by winstxnhdw** [comment]
> Following yourself

Fixed.

> Nutcrackers killed with the command drop an ungrabbable shotgun that teleports to their spawn vent when they don't have their eye out (scanning or attacking)

Finally, fixed this time.

**Comment by winstxnhdw** [comment]
> After the recent update to M3 + E using it basically anywhere at the Company building will result in death. This is because pressing E on the water normally will kill you.

That's hilarious.

**Comment by winstxnhdw** [comment]
I see, if that's the case, then isn't this the issue with being untargetable itself? Is it the same when you do `/block enemy`?

**Comment by winstxnhdw** [comment]
> The nutcracker's gun will damage you if you're close to it in phantom mode(?)

This shouldn't even be possible.. 

> When nutcrackers are prompted, their eye comes out but they don't attack, really funny to scare people though.

Like they don't attack anymore?

> Sometimes you just flat out die when pressing SHIFT + = in phantom mode. Usually occurs over long distances.

I haven't been able to replicate this. How long does it have to be? I am usually doing that from ship to fire exit.

> Masked enemies when spawned outside via /mask will ignore everybody, and instead just walk straight towards the entrance, where they will then exit and then finally aggro people. That is if there are valid targets.

That's weird. I am able to get it to instantly target someone outside immediately.

> After the recent update to M3 + E using it basically anywhere at the Company building will result in death. This is because pressing E on the water normally will kill you.

I can't find anything water has to do with the `Interact` method :( It'll probably take a while to fix.

**Comment by winstxnhdw** [comment]
> > This shouldn't even be possible..
> 
> 
> 
> Sorry, but this confuses me a little bit.
> 
> Are you saying that you can't replicate it yourself or something like that?

Can't replicate, and that I am really confident this cannot happen unless I am misunderstanding what you mean. When you are in `Phantom`, we are only moving the camera and not the player. The camera has no colliders and can never be hit. However, your real body can still take damage of course.

**Comment by winstxnhdw** [comment]
Your real body is being shot. Don't forget that the Nutcracker's bullets can pierce through walls and hit you from an infinite distance away.

**Comment by winstxnhdw** [comment]
![image](https://github.com/winstxnhdw/lc-hax/assets/56998716/cc0e740e-dc5f-4082-b1e5-c7f48000ead5)

The code clearly shows that it can hit you as long as you are within 30 degrees of the weapon.

**Comment by winstxnhdw** [comment]
Okay, I'll look into it. Weird.

**Comment by winstxnhdw** [comment]
> When nutcrackers are prompted, their eye comes out but they don't attack, really funny to scare people though.

Not actually a bug, but this shouldn't be the behaviour anymore.

**Comment by winstxnhdw** [comment]
> Can't pull the horn with this mod without /horn

If you mean you can't pull after calling this command once, that should be intended. But if you haven't called the command or the horn has stopped horning. You should still be able to pull the horn.

**Comment by GigglingMinister** [comment]
it seems like teleporter won't drop items [specify ; inverse] and infinite uses [specify ; gifts ] won't work for now and atleast for me
I might re-check again

**Comment by GigglingMinister** [comment]
also processing outdoor enemies flung them out of the map for me

**Comment by winstxnhdw** [comment]
> it seems like teleporter won't drop items [specify ; inverse]

Ah, I took a look at this, it's probably true. I'll have to rethink how I handle the teleport patch.

> also processing outdoor enemies flung them out of the map for me

Like when you are possessing giants?

**Comment by winstxnhdw** [comment]
Is it simply you are just moving too fast, hitting the terrain and flying off?

**Comment by winstxnhdw** [comment]
> /enter /exit /home all have one shared bug. It's hard to explain without a demonstration so let me explain. But to put it simply, it doesn't update your "inside" or "outside" state.

Fixed in #208

**Comment by winstxnhdw** [comment]
> Infinite deposit in practice does not work.

but `sell` works?

> Placing something outside with /build /ct /pumpkin in what is a normally invalid position, and you can't place it back. It's stuck forever. 

Yeah, I could replicate this too. No idea yet why it happens. Seems like we can only put it in an invalid position when the ship is moving.

> Weird bug with godmode and fall damage. Falling from a lethal height in godmode, and then turning off godmode, you will take some fall damage no matter how small the gap is. To put it simply godmode caches falldamage in a way.

Happens with follow mod as well.  A real mystery.

**Comment by winstxnhdw** [comment]
> Should I delete old completed bugs after some time?

Yeah, why not.

> Could it possibly be an issue with the map itself rather than the code?

I think some level of code still has to be involved though.

**Comment by winstxnhdw** [comment]
> Upd: Turrets seem to share a LOT of similarity with Nutcracker AI. Could you check the game's code for me and see if this is true?

Maybe it's the way bullets work. I'll take a look.

**Comment by winstxnhdw** [comment]
> Usually in my experience, placing an object while the ship is moving isn't registered for other clients. I was originally going to report this long before Zeekerss fixed placing objects outside of the ship, but I didn't bother since it was most likely a bug with the game itself

I think it's because the ship colliders are constantly moving about when landing so we are able to slightly clip out. If not, `void` would work while landing but it doesn't :(

**Comment by winstxnhdw** [comment]
Just merged the new untargetable patch, so blocking enemies could be better now.

**Comment by winstxnhdw** [comment]
Can you try latest again? If it’s still broken, it’s probably not on our side anymore.

**Comment by winstxnhdw** [comment]
> Infinite deposit in practice does not work.

Fixed in latest.

**Comment by winstxnhdw** [comment]
> Gifts will be un-droppable after multiple usage either ranging from 2-3 absolutely erratic amount of uses before breaking, only way to remove is via the cupboard. 

Fixed in latest.

**Comment by winstxnhdw** [comment]
> Sell command doesn't sell masks

This is intentional. For some reason, masks act really differently from other scraps and it breaks the `sell` command.

**Comment by winstxnhdw** [comment]
> https://github.com/winstxnhdw/lc-hax/issues/66#issuecomment-1883266937

Fixed.

> Placing something outside with /build /ct /pumpkin in what is a normally invalid position, and you can't place it back. It's stuck forever.

Not fixable.

> Clear command prevents all and any messages from being shown, even after the command is executed. Also have to double-tap enter to send something

Fixed

**Comment by winstxnhdw** [comment]
> Sometimes you just flat out die when pressing SHIFT + = in phantom mode. Usually occurs over long distances. d0b5852 6/1/2024 13:08

> Probably not related to the issue above, but phantom'ing midair and the game will think you're still falling and building up fall damage. 332800f 13:48 11/1/2024

> Weird bug with godmode and fall damage. Falling from a lethal height in godmode, and then turning off godmode, you will take some fall damage no matter how small the gap is. To put it simply godmode caches falldamage in a way. 332800f 13:48 11/1/2024

I can't replicate these anymore. Probably auto-fixed by the devs.

**Comment by winstxnhdw** [comment]
> The nutcracker's gun will damage you if you're close to it in phantom mode 6607092 1/7/2024 8:07

I've decided that a possible fix for this would affect the gameplay experience in other areas, so I will not be fixing this one.

**Comment by winstxnhdw** [comment]
If the user is using `FollowMod` and is under possession, I'd still like them to be shot and killed by a player or the nutcracker.

**Comment by winstxnhdw** [comment]
> After the recent update to M3 + E using it basically anywhere at the Company building will result in death. This is because pressing E on the water normally will kill you. d5ab9d6 4/1/2024 10:37

Everything except this has been fixed. I think we can close this issue and start a new one when you're back or when the next update comes. Thanks for the help all this time!

**Comment by joep26020** [comment]
> Yeah, sorry for slowing down a little bit, most bugs in this project got fixed because v49 has been here for quite a while. Will definitely come back when v50 releases though.

do you know when v50 will be released?
