### ISSUE TITLE
[Feature Request]: Infinite battery

### ISSUE THREAD

**Issue by armorfid** [winstxnhdw/lc-hax#68]
### What happened?

title

### Current Commit Hash

f45b67c

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Tried it before, tried it just now. Still no clue how to get it working. If you got a reference, I'd love to see it.

**Comment by armorfid** [comment]
never modded LC before but managed to cobble up something from scratch, here you go my good sir, thank you for this project

```
[HarmonyPatch(typeof(GrabbableObject))]
class UnlimitedBatteryPatch {
    [HarmonyPatch(nameof(GrabbableObject.Update))]
    static void Prefix(ref Battery ___insertedBattery) {
        if (___insertedBattery != null) {
            ___insertedBattery.empty = false;
            ___insertedBattery.charge = 1.0f;
        }
    }
}
```

**Comment by winstxnhdw** [comment]
Yeah, that’s what I tried before. Didn’t work. I thought it was because I was patching the base classes, so I tried pathing the Zap Gun’s charge method directly. Still no go.

**Comment by winstxnhdw** [comment]
@Quesoteric I haven’t given that way a try. Might give it a shot later.

**Comment by armorfid** [comment]
> Didn’t work. I thought it was because I was patching the base classes, so I tried patching the Zap Gun’s charge method directly. Still no go.

wdym? this works perfectly for me online when joining as of now, i got infinite jetpack flashlight talkie etc.

**Comment by winstxnhdw** [comment]
Strange. Guess I'll give it one more go.

**Comment by armorfid** [comment]
yep thats the one running every frame

**Comment by winstxnhdw** [comment]
Done. Thank you for the reference @armorfid :) Maybe it would've been better if you submitted a PR for credits.

**Comment by armorfid** [comment]
next time fo sho
