### ISSUE TITLE
what does /beta do?

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#72]

**Comment by AverageVirusTotalEnjoyer** [comment]
@winstxnhdw

**Comment by winstxnhdw** [comment]
It unlocks the badge that's supposedly only given to beta players.

**Comment by AverageVirusTotalEnjoyer** [comment]
i dont see any difference

**Comment by winstxnhdw** [comment]
Neither do I, honestly. But it's in the game code.

**Comment by AverageVirusTotalEnjoyer** [comment]
probably gonna be added in next update, or maybe its the vip badge who knows
