### ISSUE TITLE
make entities not attack players

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#76]

**Comment by winstxnhdw** [comment]
Might be possible but it doesn't look trivial, so I am going to put this on the backlog.

**Comment by AverageVirusTotalEnjoyer** [comment]
alright

**Comment by winstxnhdw** [comment]
Which method is this?

**Comment by winstxnhdw** [comment]
Okay. I have added this. It's `/block enemy`.
