### ISSUE TITLE
bug list and questions

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#77]
> whats the realistic possesion and why do entities disappear when i enable it? (they do come back when i disable it)

if i use  triggermod on something sometimes this appears and prevents me from using it entirely until i restart the game
![image](https://github.com/winstxnhdw/lc-hax/assets/118130921/2c0584b7-02ea-4e92-b355-7feb3e0f0c36)

**Comment by AverageVirusTotalEnjoyer** [comment]
@winstxnhdw

**Comment by winstxnhdw** [comment]
Yeah `possession` seems broken in latest. Will fix soon.

**Comment by AverageVirusTotalEnjoyer** [comment]
alright

**Comment by AverageVirusTotalEnjoyer** [comment]
oh and @winstxnhdw whats realistic possession?

**Comment by winstxnhdw** [comment]
I believe it's more convincing without the option to fly.

**Comment by winstxnhdw** [comment]
It's fixed in latest.
