### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Panda4234** [winstxnhdw/lc-hax#8]
i can't download those packages while lauch 'requirements.bat',is there another way?

**Comment by winstxnhdw** [comment]
Please describe why you are unable to download the packages? In fact, the `requirements.bat` doesn’t install anything.

**Comment by winstxnhdw** [comment]
If you have .NET 8.0 installed, that shouldn't be a problem.

**Comment by winstxnhdw** [comment]
Great! Maybe you can describe how you solve it for others with the same issue as yourself.
