### ISSUE TITLE
[Bug]: While in phantom mode during spectating I can't open or close the big doors.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#89]
### What happened?

Also can't see door percentages during phantom mode in spectating.

### Current Commit Hash

231454

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Are you sure you can't using `M3` + `E`?

**Comment by winstxnhdw** [comment]
@joep26020 I need you to be certain of the bugs you are filing. You are one of the most frequent bug filers but with the highest invalid rate. Investigating them takes a lot of time, which means less time is allocated solving other real bugs and adding new features.

**Comment by joep26020** [comment]
> Are you sure you can't using `M3` + `E`?

Yep doesn't work either. Also apparatus hasn't been collected. But on top of that when you get the apparatus, you can't open or close the big doors. Not sure if you can fix that or if it's a server thing.

**Comment by joep26020** [comment]
> @joep26020 I need you to be certain of the bugs you are filing. You are one of the most frequent bug filers but with the highest invalid rate. Investigating them takes a lot of time, which means less time is allocated solving real bugs and adding new features.

Ok, will retest in another server.

**Comment by winstxnhdw** [comment]
> Not sure if you can fix that or if it's a server thing.

This is not fixable. It might be useful to check if the circuit breaker has been activated as well. It's hard to tell with `ClearVision` on.

**Comment by joep26020** [comment]
> > Not sure if you can fix that or if it's a server thing.
> 
> This is not fixable. It might be useful to check if the circuit breaker has been activated as well. It's hard to tell with `ClearVision` on.

Works in another server by the way. I will promise to check other servers and update every time I have issue.

**Comment by winstxnhdw** [comment]
> Also can't see door percentages during phantom mode in spectating.

This happens when no one is near the ship. The game stops running anything outside of the factory.

**Comment by winstxnhdw** [comment]
> Works in another server by the way. I will promise to check other servers and update every time I have issue.

That would be great, thank you.

**Comment by joep26020** [comment]
> > Also can't see door percentages during phantom mode in spectating.
> 
> This happens when no one is near the ship. The game stops running anything outside of the factory.

Somebody was in the ship and still doesn't show up.

**Comment by winstxnhdw** [comment]
I could've misunderstood. Perhaps the game doesn't render any processes if it deems the player isn't near, regardless of whether there are other players nearby.
