### ISSUE TITLE
/tphere command

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#9]
One thing I have tested is phantom and tp. I would fly with phantom to a location. I don't like how annnoying it is to type /xyz and then type /tp x y z. It would be convient if you type /tphere and it takes you there and disabled phantom or doesn't.

**Comment by winstxnhdw** [comment]
@LTYGUY

**Comment by winstxnhdw** [comment]
I have added this feature but a bit differently. If you deactivate with `Shift` + `=`, you will teleport to where you are in `Phantom`.

**Comment by MythicalTrashcan** [comment]
Very cool. Will test this out in 10 minutes.
