### ISSUE TITLE
[Bug]: Kill doesn't work nor does /pumpkin.

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#93]
### What happened?

adadasddwa

### Current Commit Hash

asda

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment]
Please see #91
